### ISSUE TITLE
How to access without SSL ?

### ISSUE THREAD

**Issue by vipera7** [linuxserver/docker-nextcloud#100]
I'm trying to configure a docker which should work without SLL for testing purpose.  I tried to access throught port 80 without success. Here is the command I'm using

`docker run --name=nextcloud -e PUID=1000 -e PGID=1000 -e TZ=Europe/Paris -p 443:443 -v /home/foo/nextcloud/config:/config -v /home/foo/data:/data --restart unless-stopped linuxserver/nextcloud`

I know that port 443 is for https but how can I access in http ?

Similar issue : https://github.com/linuxserver/docker-nextcloud/issues/65

**Comment by j0nnymoe** [comment]
edit the included nginx config to allow access on port 80 then map that port to the container.

**Comment by vipera7** [comment]
I mapped the port 80 like : 

`docker run --name=nextcloud -e PUID=1000 -e PGID=1000 -e TZ=Europe/Paris  -p 80:80 -p 443:443 -v /home/foo/nextcloud/config:/config -v /home/foo/data:/data --restart unless-stopped linuxserver/nextcloud`

 and I checked `config/nginx/site-confs/default` from the volume and it containe the following lines : 

```
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://$server_name$request_uri;
}
```


And still not working

**Comment by vipera7** [comment]
@j0nnymoe I did it. I can access to the login page. When I enter the correct values I'm redirected to https. I edited in `config.php ` to remove https to :  
`'overwrite.cli.url' => 'http://192.168.0.1:8080',`

**Comment by CHBMB** [comment]
@vipera7 We've closed this issue as it isn't a bug.  We try to not to use Github for support, but rather our Discord server or forum.

Having said that, this currently isn't something we support ourselves so you'll probably be reliant on any other community members offering their help.
