### ISSUE TITLE
Unable to connect using http

### ISSUE THREAD

**Issue by vipera7** [linuxserver/docker-nextcloud#101]
I'm sorry to create a new issue, the last one didn't resolve it. I created a new image. The file default contain this :  
```
upstream php-handler {
    server 127.0.0.1:9000;
}
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 http://$server_name$request_uri;
}
```

And I mapped the port 80 like :

`docker run --name=nextcloud -e PUID=1000 -e PGID=1000 -e TZ=Europe/Paris -p 80:80 -p 443:443 -v /home/foo/nextcloud/config:/config -v /home/foo/data:/data --restart unless-stopped nextcloud`

 I can't access it on port 80.

I'm always redirected to https://_/

**Comment by CHBMB** [comment]
This is an Nginx config issue.  Not an issue with the container.  

You need to configure Nginx to listen and respond on port 80, not return a 301

Discord is more appropriate for support, we try and reserve Github for actual issues with the Docker containers themselves, so drop by there if you need help.

**Comment by vipera7** [comment]
When I try to run I have the following error  `/usr/sbin/nginx -c /config/nginx/nginx.conf`: 

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] still could not bind()
```

**Comment by tobbenb** [comment]
Didn't you read what he said?
And don't try to run any commands in the container. Hop on to discord or our forum for support.

**Comment by vipera7** [comment]
@tobbenb Where can I find the forum ? I searched on the official website can't find it

**Comment by tobbenb** [comment]
You find it at https://discourse.linuxserver.io/

**Comment by loganto** [comment]
Ugh. I would agree with others in this and other similar tickets.
SSL should be optional. I dont care about ssl on my internal network.
Nor am i gonna be configuring SSL per application - reverse proxy is preferred route anyways.
