### ISSUE TITLE
This version of Nextcloud is not compatible with > PHP 7.2. 

### ISSUE THREAD

**Issue by jwillmer** [linuxserver/docker-nextcloud#103]
After updating the docker image I get the following error:

```
This version of Nextcloud is not compatible with > PHP 7.2.
You are currently running 7.3.6.
```

**Comment by aptalca** [comment]
What is your nextcloud version?

**Comment by jwillmer** [comment]
It is probably related to this commit: c55ce843e457ad8e0fb6d7cf4001c8a00b6a8f84

My docker-compose file:
```

  nextcloud:
    image: linuxserver/nextcloud
    ...
```

**Comment by aptalca** [comment]
If you can access the gui, it should tell you the version

If not, go back to the previous tag (you can see them on docker hub).

Nextcloud is one of a few apps you need to uodate inside the container. I suspect you have been updating the docker image but not the nextcloud app inside.

After you go back to the older tag, you can use the web gui updater to update nextcloud

**Comment by jwillmer** [comment]
O.K. I will try. How do I get/replace the image with latest-1 ?

**Comment by jwillmer** [comment]
Image `image:  linuxserver/nextcloud:16.0.1-ls23` does work for me.

**Comment by jwillmer** [comment]
Nextcloud version is `'version' => '13.0.1.1',` so I guess I can't upgrade. The latest image just does not work.

**Comment by aptalca** [comment]
That's a really old version but you should be able to upgrade nextcloud in the webgui. It will do one increment at a time, and once you get to 15 or 16, you can resume the docker image updates

**Comment by jwillmer** [comment]
I don't get any new version proposed in the webgui and I have a feeling that the version number is faulty.

**Comment by aptalca** [comment]
Deactivated by you or the app?

If the gui updater doesn't work, there is also a command line option:

**Comment by jwillmer** [comment]
Now I upgraded via web to the latest version and the `:latest` docker image works. Thanks for your help @aptalca

**Comment by renlord** [comment]
this issue still exist for the `arm32v7-latest` tag.

**Comment by aptalca** [comment]
Did you read the comment above yours?

**Comment by renlord** [comment]
> Did you read the comment above yours?

Yes I did. I tried both `latest` and `arm32v7-latest` tags and I see:

```
This version of Nextcloud is not compatible with > PHP 7.2.
You are currently running 7.3.6.
```

Running `docker images | grep linuxserver/nextcloud`:

```
linuxserver/nextcloud                      arm32v7-latest      39cd639a6ead        2 days ago          265MB
linuxserver/nextcloud                      latest              39cd639a6ead        2 days ago          265MB
```

**Comment by Tacitus2k** [comment]
Hi there!
I am running Netxcloud on a QNap- NAS... I am not sure which version (should be 12.x?). After firmware update on the QNap I do get the 

> This version of Nextcloud is not compatible with > PHP 7.2.
You are currently running 7.3.7.

error.

I cannot access the nextcloud GUI and while attempting to update netxcloud via ssh the same error occurs.

Any ideas/ solutions?!

**Comment by j0nnymoe** [comment]
You need to roll back your container to a previous tag related to the version you were using then upgrade nextcloud within the webui (As discussed above).

**Comment by Tacitus2k** [comment]
Ok... but is there a chance to perform the update manually?
(without downgrading the container)
Thank you!

**Comment by j0nnymoe** [comment]
I think this is it. I'm not responsible for anything that goes wrong.
##Open terminal in container
docker exec -it nextcloud bash

##Run CLI Update
sudo -u abc php7 /config/www/nextcloud/updater/updater.phar

**Comment by namacoconut** [comment]
I'm having this issue 
`This version of Nextcloud is not compatible with > PHP 7.3.
You are currently running 8.0.0rc1.`
i down graded the version it doesn't work
any help please

**Comment by j0nnymoe** [comment]
@namacoconut the fix is literally above your comment.

**Comment by TiloHeidasch** [comment]
> 
> 
> I think this is it. I'm not responsible for anything that goes wrong.
> ##Open terminal in container
> docker exec -it nextcloud bash
> 
> ##Run CLI Update
> sudo -u abc php7 /config/www/nextcloud/updater/updater.phar

This did the job for me!
Thanks for sharing 👍

**Comment by namacoconut** [comment]
> @namacoconut the fix is literally above your comment.

for my question I wasn't using docker for installation i was trying to install it without docker

**Comment by j0nnymoe** [comment]
@namacoconut so if you're using an install without docker, how come you're commenting on an issue for a docker container for nextcloud?

**Comment by namacoconut** [comment]
> @namacoconut so if you're using an install without docker, how come you're commenting on an issue for a docker container for nextcloud?

my bad :\

**Comment by chainofhonor** [comment]
“/lib/versioncheck.php”  
edit this file
