### ISSUE TITLE
New install "File not found."

### ISSUE THREAD

**Issue by X2LR** [linuxserver/docker-nextcloud#104]
New install "File not found."
Provide a general summary of the issue in the Title above

Host OS 

OMV
Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings.

![2019-07-12](https://user-images.githubusercontent.com/52667481/61160593-e35e5b80-a4f7-11e9-88d7-e5cce5594d44.png)

Docker log output, docker log <container-name>
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
........+++++
...................................................................................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  4 58.7M    4 2720k    0     0  5250k      0  0:00:11 --:--:--  0:00:11 5240k 80 58.7M   80 47.0M    0     0  30.9M      0  0:00:01  0:00:01 --:--:-- 30.9M100 58.7M  100 58.7M    0     0  33.1M      0  0:00:01  0:00:01 --:--:-- 33.1M
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing...
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

Mention if you're using symlinks on any of the volume mounts. 
None

https://10.0.0.22:444/ gives File not found.

**Comment by Misi0** [comment]
Had the same issue when downloaded 'latest' Docker image. Then I've tried with amd64-latest and it worked without issues.

**Comment by CHBMB** [comment]
Sounds like docker pulled the wrong arch or the particular build the OP was pulling was dodge
