### ISSUE TITLE
Update from 16.0.3 to 16.0.4

### ISSUE THREAD

**Issue by bonovski** [linuxserver/docker-nextcloud#110]
Nextcloud settings tell me that I'm running **16.0.3.**

![image](https://user-images.githubusercontent.com/9703732/64853565-ebcc3300-d61b-11e9-94e1-76adabca020d.png)

But portainer tells me that I have the latest image pulled and running:

![image](https://user-images.githubusercontent.com/9703732/64853658-2766fd00-d61c-11e9-9e9f-77196e99e4e0.png)

Do I have to manually update the app in the webGUI? Shouldn't the new image reflect in the settings?

**Comment by j0nnymoe** [comment]
Yes you have to manually update within the image. The version tag references what you'll get on initial install.
