### ISSUE TITLE
Php 7.X upgrade

### ISSUE THREAD

**Issue by nicoxygen** [linuxserver/docker-nextcloud#111]
hello I would like to know if it is possible to upgrade the php version beyond the 7.0.33 because this version of nextclous needs the minimum version 7.1 to work with certain applications.
Thank you.

**Comment by aptalca** [comment]
Update the image and recreate the container. The latest image has php 7.3.9: https://github.com/linuxserver/docker-nextcloud/blob/master/package_versions.txt#L126

**Comment by nicoxygen** [comment]
i have installed end version nextcloud:latest ( 1 day ago ) and php -v give:

PHP 7.0.33-0+deb9u5 (cli) (built: Sep 18 2019 09:55:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u5, Copyright (c) 1999-2017, by Zend Technologies

**Comment by nicoxygen** [comment]
image nextcloud:
latest: Pulling from linuxserver/nextcloud
Digest: sha256:f520b0beda35ca8e5bea6704c26178e3be2b108580b98dc5ad88c17bd09426a3
Status: Image is up to date for linuxserver/nextcloud:latest
docker.io/linuxserver/nextcloud:latest

**Comment by j0nnymoe** [comment]
Getting the correct version here - fresh pull.

![image](https://user-images.githubusercontent.com/10374553/65774730-c1f42f80-e136-11e9-999d-0a99c90db861.png)

**Comment by nicoxygen** [comment]
ok excuse me i have work on ssh but not in docker directely

**Comment by nicoxygen** [comment]
end questions it's possible to install on port 80 redirect but not with port 443
Impossible to found ip address _
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by j0nnymoe** [comment]
By default, it runs on https/443 - if you want to run it on http/80, you will need to edit the nginx configuration within the container first.
