### ISSUE TITLE
cant sudo in nextcloud container

### ISSUE THREAD

**Issue by antipiot** [linuxserver/docker-nextcloud#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
execute command
docker exec -it test sudo -u abc php /config/www/nextcloud/occ files:cleanup
should start file cleanup

## Current Behavior
Command return error 
docker exec -it test sudo -u abc php /config/www/nextcloud/occ files:cleanup
sudo: unable to open /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

## Steps to Reproduce
Start a new Nextcloud container
try to sudo

sudo: unable to open /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by CHBMB** [comment]
You need to use php7

```
docker exec nextcloud sudo -u abc php7 /config/www/nextcloud/occ
```

**Comment by antipiot** [comment]
Hello, Thanks for your answer. But this dont solve my error for the sudo part :-)

docker exec test sudo -u abc php7 /config/www/nextcloud/occ files:cleanup
sudo: unable to open /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by CHBMB** [comment]
Works for me on the latest build and has worked for me since I added `sudo` to the container a few years ago.

```
root@server:~# docker exec nextcloud sudo -u abc php7 /config/www/nextcloud/occ files:cleanup
0 orphaned file cache entries deleted
```

**Comment by CHBMB** [comment]
Is your container called `test` and is it actually running?

**Comment by antipiot** [comment]
Sure it does, else i wont have the error :-)
Will try on another host with sudo - anyway i got it working using
docker exec -u abc test php7 /config/www/nextcloud/occ files:cleanup

Thnaks for your answers

**Comment by antipiot** [comment]
There was something wrong with the container: redownloaded image: working fine now

**Comment by antipiot** [comment]
edit: this was related with the rights of the folder  who contains the docker images.
