### ISSUE TITLE
docker script failed on first run

### ISSUE THREAD

**Issue by kt1024** [linuxserver/docker-nextcloud#114]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

docker run failed, tag: amd64-latest. (first run, have tried remove folder/contrainer and start over; /opt is on local disk)

------------------------------

## Expected Behavior

docker star correctly. 
## Current Behavior
container failed to setup. (did not manually stop the script or  container during "docker start")
using docker-compose also failed. 

## Environment
**OS:**      Debian buster
**CPU architecture:** x86_64/      
<code>curl https://nextcloud.com</code> can load page without error, so network should be OK.
<pre>
root@x86:~# docker -v
Docker version 19.03.4, build 9013bf583a
root@x86:~# uname -a
Linux x86 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
root@x86:~# docker-compose -v
docker-compose version 1.24.1, build 4667896b
</pre>
## Docker logs
<pre>
root@x86:~# docker rm nextcloud 
nextcloud
root@x86:~# docker run -d --name nextcloud -v /opt/nextcloud/data:/data -v /opt/nextcloud/config:/config -e PUID=1000 -e PGID=1000 -p 1580:80 -p 15443:443 --restart unless-stopped linuxserver/nextcloud:amd64-latest
4fecaaf7b09471bc17afd45ee6437b0d0b8a8c585d4751ad0b30b9a2376c88ac
root@x86:~# docker logs -f nextcloud 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
...........................................+++++
........................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing... 
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing... 
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
</pre>

**Comment by aptalca** [comment]
What makes you think it failed? The logs show that it started up correctly. Access it at the https port you used

**Comment by kt1024** [comment]
my bad, it works. I mixed error of running against nfs volume settings. thank you.
