### ISSUE TITLE
"X-Frame-Options" HTTP header is not set to "SAMEORIGIN"

### ISSUE THREAD

**Issue by BobWs** [linuxserver/docker-nextcloud#119]
Hi,

I've install this image on docker / Synology NAS and I'm keep getting this error "X-Frame-Options" HTTP header is not set to "SAMEORIGIN"

![Screen Shot 2019-11-15 at 11 49 47](https://user-images.githubusercontent.com/5485820/68939831-dd2c0480-07a1-11ea-8171-4dcb884e0fa7.png)

Any idea how to fix this?

Thanks in advanced

**Comment by aptalca** [comment]
New install or update from older version?

**Comment by BobWs** [comment]
> New install or update from older version?

A new fresh first time install.

**Comment by watson387** [comment]
I have the same. Fresh linuxserver Docker container.

**Comment by MollyBe** [comment]
If you would like to enable iFrames please read [this](https://help.nextcloud.com/t/solved-nextcloud-16-how-to-allow-iframe-usage/52278).

If you would like to set the X-Frame-Options header to SAMEORIGIN add the following line to your nginx configuration file. It should be located inside your container at **config/nginx/site-confs/default**
`add_header X-Frame-Options "SAMEORIGIN" always;`

Nextcloud 17 now requires this header the nginx configuration file. There is a pull request to reflect this change in their release notes, [here](https://github.com/nextcloud/documentation/pull/1630/files).

It seems this line needs to be added to linuxserver/docker-nextcloud/blob/master/root/defaults/default

There is already pull request discussing if this change is required [here](https://github.com/linuxserver/docker-nextcloud/pull/112).
