### ISSUE TITLE
High memory usage (13.1GB!)

### ISSUE THREAD

**Issue by kxpler442b** [linuxserver/docker-nextcloud#126]
Hello!
After recently checking through my containers after seeing very high memory usage, I discovered that this docker image was using upwards of 13GB of my RAM. This surely isn't necessary, so I would like to ask why this is happening? 
------------------------------

## Expected Behavior
Memory usage at least below 2GB

## Current Behavior
Container starts at around 53MB and increases continuously with usage.

## Steps to Reproduce
1. Create new instance using documentation
2. Use Nextcloud normally (syncing, webUI etc)
3. Observe insane RAM usage.

## Environment
**OS:**  Ubuntu 18.04.4 Server    
**CPU architecture:** x86_64    
**How docker service was installed:**      
Using docker-compose

## Command used to create docker container (run/create/compose/screenshot)
version: '3.1'

services:
  app:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud_app
    links:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/nextcloud/config:/config
      - /srv/nextcloud/data:/data
    ports:
      - 5005:443
    restart: unless-stopped

  db:
    image: linuxserver/mariadb:latest
    container_name: nextcloud_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - TZ=Europe/London
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=PASSWORD
    volumes:
      - /srv/nextcloud/db:/config
    restart: unless-stopped

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing... 
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing... 
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done

**Comment by CHBMB** [comment]
I don't see how we can answer this realistically.  I'm certainly not seeing the same issue on my Nextcloud install.  Mine is currently idling at 98mb with the odd spike to around 160mb

**Comment by realies** [comment]
Container has a memory leak when downloading large files. Currently, have one at 27GiB when I tried to sync a 114GB file through the Nextcloud Desktop Client. When the client crashes with Operation canceled, php-fpm processes seem to continue to read from the disks at full speed.

**Comment by debian-user-france1** [comment]
I experience the same with my local nextcloud installation

**Comment by j0nnymoe** [comment]
Nextcloud (nginx) uses memory for caching.

**Comment by debian-user-france1** [comment]
Are you dumb?
That's not caching, that's threwing

**Comment by debian-user-france1** [comment]
It doesn't even release anything

**Comment by j0nnymoe** [comment]
Infact, please create a new issue and provide all the information that's been requested but please also add some extra info on stuff you've added/modified to nextcloud.
