### ISSUE TITLE
Error message after update image to latest and update to version 18.0.1

### ISSUE THREAD

**Issue by BobWs** [linuxserver/docker-nextcloud#134]
Hi,
I'm getting an error message after I updated the image and nextcloud to version 18.0.1 (coming from version 17.0.1)

Any idea how to solve this?

![Screen_Shot 2](https://user-images.githubusercontent.com/5485820/75254893-5bf0fe80-57e1-11ea-997a-66e201fbb40e.png)

**Comment by BobWs** [comment]
Solved it!

Just download and install the OCC Web app with your nextcloud admin account.
Link:https://apps.nextcloud.com/apps/occweb

After the app is installed enter the next two commands one by one:
`db:convert-filecache-bigint`
`db:add-missing-indices`

If everything is finished the error should be gone and you have a green checkmark.

![Screen_Shot 3](https://user-images.githubusercontent.com/5485820/75256333-99ef2200-57e3-11ea-967f-c8ff7d112da7.png)

![Screen_Shot 4](https://user-images.githubusercontent.com/5485820/75256343-9d82a900-57e3-11ea-9a67-3990d250e855.png)

![Screen_Shot 5](https://user-images.githubusercontent.com/5485820/75256348-a1aec680-57e3-11ea-822b-94b6bea53755.png)

**Comment by aptalca** [comment]
OCC web app was news to me. I thought you had to do it all from command line. Thanks for coming back and letting us know. Much appreciated.
