### ISSUE TITLE
Expose the crontab

### ISSUE THREAD

**Issue by fletchto99** [linuxserver/docker-nextcloud#135]
I'd like to be able to modify the crontab file so that plugins such as [Preview Generator](https://apps.nextcloud.com/apps/previewgenerator) are able to run in the background. Currently the crontab is setup each time the container is run, perhaps it could be exposed in the mounted volume and setup during the initial run but then allows for modification after that?

**Comment by MarianRychtecky** [comment]
Hi, I have upgraded to version 27.0.0-ls254, and I can see the crontab file exposed in /config/crontabs/root, but all changes are overwritten with container startup. Am I missing something? Thanks for your help.

**Comment by drizuid** [comment]
> Hi, I have upgraded to version 27.0.0-ls254, and I can see the crontab file exposed in /config/crontabs/root, but all changes are overwritten with container startup. Am I missing something? Thanks for your help.

If it is overwriting, you've done something wrong. Open your own issue and fully fill out the template, or visit us on discord.
