### ISSUE TITLE
Nextcloud External storage support not respecting UnRaid Permission scheme

### ISSUE THREAD

**Issue by JoschaMiddendorf** [linuxserver/docker-nextcloud#136]
I'm using the External storage support 1.9.0 App to mount local Unraid shares via Docker mapping into Nextcloud 18.0.3. I'm not using SMB to map them because it is more than one share and SMB turned out to be much slower in navigating into them via Nextcloud. 

## Current Behavior
When Syncing data to these mapped shares via Web DAV, or when I'm creating a folder via Web GUI, permissions of created folders are not 777 (drwxrwxrwx) but 755 (drwxr-xr-x).
Permissions of a txt file created via Web GUI are 644 (-rw-r--r--) and not 666 (-rw-rw-rw-) as expected for Unraid. 

## Expected Behavior
Setup of the propper UMASK to make Nextcloud respect Unraid's permission scheme?

## Steps to Reproduce
1. Map external storage folder into the container
2. Via "External storage support" integrate that "Local" folder into Nextcloud
3. Create any file via Web Frontend
4. Check Permissions of that file or folder in UnRaid Console

## Environment
UnRaid
x86_64   
UnRaid Docker Management 

## Command used to create docker container (run/create/compose/screenshot)
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='nextcloud' --net='br0.10' --ip='10.1.10.50' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -v '/mnt/user/30_NextCloud/':'/data':'rw' -v '/mnt/user/':'/shares/':'rw' -v '/mnt/user/appdata/nextcloud':'/config':'rw' 'linuxserver/nextcloud'

**Comment by JoschaMiddendorf** [comment]
Furthermore, when transferring large files 3GB via Mobile App to external storage folders, Docker Image is growing rapidly while uploading.

**Comment by JoschaMiddendorf** [comment]
The issue is stil present.

**Comment by j0nnymoe** [comment]
Regarding the UMASK issue, see this here: https://github.com/linuxserver/docker-nextcloud#umask-for-running-applications

With large file issue, I believe there is a tmp folder that needs to be mapped to your host to stop this from happening. I'll try and investigate this soon as I have experienced the same issue in the past.

**Comment by JoschaMiddendorf** [comment]
Thanks for pointing me to the UMASK option. That solved the Permission Issue for me.
Let me know which folder has to be mapped to the host.

**Comment by david-kalbermatten** [comment]
@JoschaMiddendorf What UMASK did you end up using? When I try to set it to any of these "007, 000, 022" Nextcloud still ends up writing a file with 644 instead of 666...

**Comment by Memes11** [comment]
similar issue her, I tried UMASK=000 on the container, also UMASK_SET=777 on the container, none work.

**Comment by david-kalbermatten** [comment]
How has this not been addressed yet?! I find people posting about this about 5 years back :/

Also, can this be re-opened? It's clearly not fixed or the solution hasn't been shared in a way that is understandable to me and at least someone else...

Posting on the [Nextcloud forums](https://help.nextcloud.com/t/external-storage-files-dirs-created-with-wrong-permissions/68969/24) hasn't yielded anything either

**Comment by j0nnymoe** [comment]
@david-kalbermatten it went slightly offtopic, I asked for a question and then go no further update so it got closed due to inactivity.

Also my recommendation is to always add the shares via SMB within external applications so it repects the correct user.

**Comment by david-kalbermatten** [comment]
That causes its own issues in form of caching the requested files, also it seems a little ridiculous to use a protocol with overhead to access files that are already locally available just to work around permission issues. I tried both. Right now, I have a cron-job running on the affected shares that searches for files with wrong permissions and adjusts them accordingly but that too is a sub-optimal workaround...

```bash
find /mnt/user/Media -type f ! -perm -220 -exec chmod 666 {} \;  # Searches for affected files
find /mnt/user/Media -type d ! -perm -220 -exec chmod 777 {} \;  # Searches for affected folders
```

**Comment by Memes11** [comment]
@david-kalbermatten thanks for the idea, I implemented that for now too.
