### ISSUE TITLE
Option to disable HTTPS?

### ISSUE THREAD

**Issue by bramceulemans** [linuxserver/docker-nextcloud#142]
I am trying to run `linuxserver/nextcloud` behind a Traefik reverse proxy, however it is a pain to do so because by default `linuxserver/nextcloud` runs over https with a self signed certificate. Would it be possible to add an option to disable this behaviour and just allow plain http without having to change the `config/nginx/default` file.

------------------------------

## Steps to Reproduce

1. Make docker-compose file with linuxserver/nextcloud
2. Expose port 80/443
3. Try to access port 80
4. Redirected to 443

**Comment by aptalca** [comment]
No plans for it.

Any reverse proxy should easily be able to proxy https endpoints. Our letsencrypt solution does this with the built in proxy conf.

You can contact traefik to figure out how to do that

**Comment by bramceulemans** [comment]
I don't get why it would be needed though, all of the other applications from linuxserver are plain HTTP by default.

**Comment by aptalca** [comment]
No, plenty are https by default. It depends on the upstream decisions and various other considerations by the dev/maintainer

**Comment by noaho** [comment]
I'm trying to run this on a raspberry pi and finding huge performance issues downloading large files (eg 1gb+). I'm guessing it's trying to encrypt twice (once in linuxserver/letsencrypt) and maybe using compression too?

**Comment by BartKoppers** [comment]
> No plans for it.
> 
> Any reverse proxy should easily be able to proxy https endpoints. Our letsencrypt solution does this with the built in proxy conf.
> 
> You can contact traefik to figure out how to do that

I think the request is legitimate.
The [(more) official Nextcloud (NC) docker](https://github.com/nextcloud/docker) provides http as an endpoint, not https, and offers additional parameters you can use to get it properly working behind proxies (like Nginx/Traefik) etc . `(OVERWRITEPROTOCOL, TRUSTEDPROXIES)`. 
Using selfsigned certificates in the container itself (like LS.io does here) lead to all kind of issues in my setup, and made me decide to switch to the NC-supported version

**Comment by timdonovanuk** [comment]
This is a real bummer. There are other apps that can sync with nextcloud, but stupidly their implementations don't allow for "invalid" HTTPS certificates, so using this version of Nextcloud means:

- you cannot connect those apps locally over HTTP
- you cannot connect those apps locally over HTTPS
- the only way to connect them is to expose Nextcloud publically and get an actual HTTPS letsencrypt certificate

By trying to be more secure, its now massively less secure.

**Comment by aptalca** [comment]
You don't have to publish publicly for letsencrypt. You can do that internally via dns validation. Then you can have those apps connect locally via https with a valid cert

**Comment by BartKoppers** [comment]
> > No plans for it.
> > Any reverse proxy should easily be able to proxy https endpoints. Our letsencrypt solution does this with the built in proxy conf.
> > You can contact traefik to figure out how to do that
> 
> I think the request is legitimate.
> The [(more) official Nextcloud (NC) docker](https://github.com/nextcloud/docker) provides http as an endpoint, not https, and offers additional parameters you can use to get it properly working behind proxies (like Nginx/Traefik) etc . `(OVERWRITEPROTOCOL, TRUSTEDPROXIES)`.
> Using selfsigned certificates in the container itself (like LS.io does here) lead to all kind of issues in my setup, and made me decide to switch to the NC-supported version

Closing doesn't help. Here it is again : #206
