### ISSUE TITLE
[feature] Please add PHP Imagick extension for HEIC to JPG conversion plugin

### ISSUE THREAD

**Issue by alzawada** [linuxserver/docker-nextcloud#145]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Be able to use imageConverter app in nextcloud to convert HEIC to JPG files in application.

## Current Behavior
When trying to use the plugin i'm getting error, probably b.c.: there are no HP Imagick extension as decribed here: https://github.com/major-mayer/imageConverter

## Steps to Reproduce
1. In nextcloud, install APP: HEIC/HEIF Image Converter ( https://apps.nextcloud.com/apps/imageconverter )
2. uplod to nextcloud HEIC file
3. right clik on file and try to convert ot JPG
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
Both the php7-imagick and the imagemagick packages are included here: https://github.com/linuxserver/docker-nextcloud/blob/master/Dockerfile#L30-L42

**Comment by alzawada** [comment]
I see...so looks that I have an issue with app for HEIC to JPG conversion: right click on a HEIC file, pic 'Convert this image to JPG' and I'm getting 'ERROR. An error occured!' message. Any advice how to check why it does not work?

**Comment by CHBMB** [comment]
I just ran `docker exec -it nextcloud php -i` and it appears that imagick has been compiled with `heic` support

```
imagick

imagick module => enabled
imagick module version => 3.4.4
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 7.0.10-10 Q16 x86_64 2020-05-03 https://imagemagick.org
Imagick using ImageMagick library version => ImageMagick 7.0.10-12 Q16 x86_64 2020-05-21 https://imagemagick.org
ImageMagick copyright => © 1999-2020 ImageMagick Studio LLC
ImageMagick release date => 2020-05-21
ImageMagick number of supported formats:  => 233
ImageMagick supported formats => 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FLV, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV

Directive => Local Value => Master Value
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0
```

Maybe ask the dev of the addon?

**Comment by alzawada** [comment]
Just asked the dev of the addon, and they suggest to check network response in browser.
This this the error I'm getting: 

{error: "Imagick failed to convert the images, check if you fulfill all requirements.",…}
details: "Invalid input: No 'ftyp' box `/tmp/magick-16665vZDGSDjfpaIB' @ error/heic.c/IsHeifSuccess/136"
error: "Imagick failed to convert the images, check if you fulfill all requirements."

Isn't something with imagick lib?

**Comment by TSURC314** [comment]
Has anyone solved why HEIC are not able to convert? I remember seeing another forum somewhere that this issue is unique to the linuxserver docker build

**Comment by eroji** [comment]
Having this issue. No preview is generated and can't view HEIC extension files. Also convert to JPEG doesn't work.

**Comment by johnnyasantoss** [comment]
By manually installing imagemagick on the Nextcloud container (alpine) with `docker exec apk add imagemagick` I'm being able to view but still can't convert the image.

`# php -r 'phpinfo();'| grep HEIC`

After:
```
# php -r 'phpinfo();'| grep HEIC
ImageMagick supported formats => 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVS, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, KERNEL, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YAML, YCbCr, YCbCrA, YUV
```

**Comment by xLorak** [comment]
Here the same.
I even compiled all libs manually inside container.

**Comment by jontyms** [comment]
Any update?

**Comment by Wdavery** [comment]
1 month stale is a waste of everyone's time. 
1 year or even 6 months is far more reasonable. 

...unstale.

**Comment by aptalca** [comment]
The container contains imagemagick as well as php imagick. If the addon is not working, you can report it to the addon maintainer and/or imagick devs
