### ISSUE TITLE
Rar PHP extension for Extract application

### ISSUE THREAD

**Issue by EVOTk** [linuxserver/docker-nextcloud#152]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior

Since installing Extract Addons, it asks me for the php extension "Rar PHP extension (pecl -v install rar)"

## Steps to Reproduce

Listed in Requirements for Extract application
Error with Extract .7z archive :

> Error extracting IMGP2613.7z
>p7zip and p7zip-full are not installed or available DEBUG(127)Array

## Environment
**OS:** Synology DSM 6.2.3 
**CPU architecture:** x86_64
**Nextcloud :** 19.0.0

**Comment by CHBMB** [comment]
This is an unofficial addon, so I think the way forward is for the customisation of the container option be used.
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

I'd try this and see if it works.
```
#!/bin/bash

echo "**** installing unrar and p7zip ****"
apk add --no-cache \
    p7zip \    
    unrar
```

**Comment by Wdavery** [comment]
Would love to see these requirements implemented

**Comment by Wdavery** [comment]
That script ran into some errors.
This works great for me! Thanks for the tip.

```
#!/bin/bash

echo "**** installing p7zip and unrar ****"
apk add --no-cache p7zip    
apk add --no-cache unrar
```

**Comment by aptalca** [comment]
probably because of line endings (if you used windows)
you can put them on the same line
```
#!/bin/bash

echo "**** installing p7zip and unrar ****"
apk add --no-cache p7zip unrar
```
