### ISSUE TITLE
Permission error when trying to put nextcloud in maintenance mode.

### ISSUE THREAD

**Issue by gaining** [linuxserver/docker-nextcloud#158]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

When running `php occ maintenance:mode --on` I get error `Cannot write into "config" directory!
This can usually be fixed by giving the webserver write access to the config directory`
------------------------------

## Expected Behavior

Should be able to put nextcloud in maintenance mode

## Current Behavior

Unable to put nextcloud in maintenance mode.

![image](https://user-images.githubusercontent.com/7690230/90447341-1981ed80-e0b1-11ea-8be3-ca6bc5fb2525.png)

It shows that I have user "911" I don't know why. This user isn't in my system's user list.

## Steps to Reproduce

1.Type `php occ maintenance:mode --on` and wait for the error to show
2.
3.
4.

## Environment
Linux SERVER 4.4.184-1220-rockchip-ayufan-g5fe46b4c9a4a #1 SMP Sun Jul 7 13:45:25 UTC 2019 aarch64 GNU/Linux   
**How docker service was installed:**     
via apt

**Comment by j0nnymoe** [comment]
use just `occ` as it's setup to be an alias. For example:  `occ maintenance:mode --on`
