### ISSUE TITLE
Passwords app will soon require php 7.4

### ISSUE THREAD

**Issue by asonix** [linuxserver/docker-nextcloud#160]
The Passwords Nextcloud App has started complaining to me that version 2021.1.0 will require php 7.4. It seems that the version number implies it will be released next year, so there's not a whole lot of pressure, although it seems alpine's php packages are only at 7.4 on the edge channel right now, so that's something to maybe keep an eye on

**Comment by aptalca** [comment]
You should perhaps open an issue on their gitlab because they had php 7.4 in edge for a long time, but it never got merged to the stable releases
