### ISSUE TITLE
[FEATURE] Any possibility of adding a debian variant of this container?

### ISSUE THREAD

**Issue by ndanyluk** [linuxserver/docker-nextcloud#161]
Hi, I've been using this docker image on my ARM64-based system for 2 years and it's been rock solid.  Recently I tried to add the Collabora CODE server for ARM64 to use with Nextcloud Hub, however, I haven't been able to get it to run.

Apparently the issue stems from AppImage not being compatible with Alpine (see https://github.com/AppImage/AppImageKit/issues/1015).

Is there any chance that a debian or Ubuntu base image could be developed as an alternative to alpine? The latest tag could still point to Alpine, but for cases like this it would allow for some flexibility.

**Comment by aptalca** [comment]
No, this image is based on our nginx baseimage, which is alpine based. Not worth the effort to rebase that to ubuntu. You're better off installing a standalone version of code, or onlyoffice, etc. and they have full features (compared to the feature limited built-in ones). That's what we do for our team nextcloud.

**Comment by ndanyluk** [comment]
Fair enough - thanks for the clarification.  I agree that would be a ton of work for an add-on feature.  I'll look into running code direct on the server instead :)
