### ISSUE TITLE
Increase PHP timeout on Setup

### ISSUE THREAD

**Issue by hardwareadictos** [linuxserver/docker-nextcloud#162]
When i try to install nextcloud on one of my Pi4s i get a 504 error while installing forcing me to reboot containers and re-running the setup process again to end the installation having to create various users on the process.... Seems theres a timeout wich makes the setup frontend to crash:

https://www.reddit.com/r/NextCloud/comments/br1pxp/error_504_during_initial_installation_why/

![image](https://user-images.githubusercontent.com/20403906/96719589-df331600-13a9-11eb-810c-6bf4e4528b3a.png)

Please let me know if you need any log or any more info 

Kind regards

**Comment by schinivision** [comment]
Also happens to me.. Using a Pi 4.. Even if I have a disk attached with >100MB/s read write performance initial setup fails with Gateway Timeout

**Comment by aptalca** [comment]
fixed in #176
