### ISSUE TITLE
add param to enable reverseproxy subdir

### ISSUE THREAD

**Issue by mzramna** [linuxserver/docker-nextcloud#164]
just add a parameter with the supbir url and add the lines at the end ot the nextcloud config file:
`'overwrite.cli.url' => 'https://$url/$subdir',
  'overwritewebroot'=> '/$subdir',`
just add this before the last `)` is enough to enable this

**Comment by aptalca** [comment]
Config.php is in the config folder, which is persistent and it needs to be edited manually for such changes

**Comment by mzramna** [comment]
could be created an script to edit this file just after the container installs the nextclous,like delete last line and add this 2 lines i sugested

**Comment by aptalca** [comment]
We're not fans of touching upstream app config files, especially ones that are user customizable. You need to edit multiple things in that file to set up your reverse proxy anyway, you can edit the base url as well while editing others.

**Comment by mzramna** [comment]
i've made this:
``` head -n -1 $nextcloud_config_dir/www/nextcloud/config/config.php
	echo "'overwrite.cli.url' => 'https://$ip/nextcloud', 'overwritewebroot'=> '/nextcloud',);">>$nextcloud_config_dir/www/nextcloud/config/config.php
```
it seems to work if anyone wants to do so
i'm just using linuxserver.io containers,and just with letsencrypt,heimdall and nextcloud made by your own apears to work fine.
you could consider to add this procedure at the documentation,i've spent some time in research to discover how to configure the nextcloud you've made to work with your other containers,at last a link to the official doc to how to do so
