### ISSUE TITLE
Nextcloud 20 requires PHP 7.4.

### ISSUE THREAD

**Issue by mracreep** [linuxserver/docker-nextcloud#168]
It seems like Nextcloud 20 needs PHP 7.4, as well as the upcoming updates of the Nextcloud Passwords app.
The container is still 7.3, so i cant get the Update for NC20...

**Comment by JonathanTreffler** [comment]
I updated to Nextcloud 20 with PHP 7.3 and it works.
But you are right. The Passwords app will need PHP 7.4 after version 2021.1.

**Comment by mracreep** [comment]
Actually Nextcloud in general is quite behind with that, the actual Stable PHP Version is 8 i guess.
For my normal Webserver i used 7.5 years ago...

**Comment by tobbenb** [comment]
The container will not have PHP 7.4 until Alpine release 3.13

**Comment by mracreep** [comment]
Ah ok, i didnt know Alpine is the Problem here...

**Comment by aptalca** [comment]
`For my normal Webserver i used 7.5 years ago...`
There is no php 7.5
7.4 is the latest in the 7 series and 8 was just released a month ago (it will take a long time for admins and devs to migrate to 8)

**Comment by mracreep** [comment]
> `For my normal Webserver i used 7.5 years ago...`
> There is no php 7.5
> 7.4 is the latest in the 7 series and 8 was just released a month ago (it will take a long time for admins and devs to migrate to 8)

sry typo, i meant 7.4 :)
