### ISSUE TITLE
richdocuments Exception: Could not find urlsrc in WOPI

### ISSUE THREAD

**Issue by splifter** [linuxserver/docker-nextcloud#172]
Dear Linuxserver team,

first of all thanks a lot for your great work!

## Expected Behavior
Opening a docx file should open this file and make it editable via collabora built in code server.

I've fresh installed nextcloud with a postgresql database. I was trying to open the sample docx file on the server after i've installled the build in CODE_Server. 

## Current Behavior
But opening the file fails and i my logs following exception is beeing logged:
`[richdocuments] Error: Exception: Could not find urlsrc in WOPI at <<closure>>

0. /config/www/nextcloud/apps/richdocuments/lib/TokenManager.php line 210
   OCA\Richdocuments\WOPI\Parser->getUrlSrc("application/vnd ... t")
1. /config/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php line 256
   OCA\Richdocuments\TokenManager->getToken("*** sensitive parameters replaced ***")
2. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Richdocuments\Controller\DocumentController->index("*** sensitive parameter replaced ***", null)
3. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocument ... {}, "index")
4. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "index")
5. /config/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Richdocume ... r", "index", OC\AppFramework\ ... {}, {action: null,_r ... "})
6. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/richdocuments/index")
7. /config/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /apps/richdocuments/index?fileId=10&requesttoken=OGV8oAfDgr4jH5priXIJ1Z%2BKQziGWvtx3s5h30G90a8%3D%3AfSs%2F6FT2svlGbNch2SFZlO66dk6%2BNK0UkZwzuBXulMA%3D
from 192.168.178.74 by admin at 2021-01-06T07:18:51+00:00`

I've updated nextcloud now to 20.0.4 but the issue is persistent.
On my research it seemed there might be an issue with the nginx proxy config but it seems to be correct already.

## Steps to Reproduce

1. Open docx file stored under space folders --> documents

## Environment
**OS: Debian
**CPU architecture:** x86_64
**How docker service was installed:**
via docker repo.

## Command used to create docker container (run/create/compose/screenshot)
![screencapture-192-168-178-24-9000-2021-01-06-09_53_01](https://user-images.githubusercontent.com/406867/103748902-10b09a80-5005-11eb-97f8-aed9f8c9af1e.png)

## Docker logs
-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    911

User gid:    911

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

using keys found in /config/keys

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 40-config: executing... 

[cont-init.d] 40-config: exited 0.

[cont-init.d] 50-install: executing... 

[cont-init.d] 50-install: exited 0.

[cont-init.d] 60-memcache: executing... 

[cont-init.d] 60-memcache: exited 0.

[cont-init.d] 70-aliases: executing... 

[cont-init.d] 70-aliases: exited 1.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

Would appreciate any help.

Thank you!

**Comment by tobbenb** [comment]
If Code server is the same thing as only office, it will not work in our container as we use Alpine Linux and the binaries from nextcloud are compiled only for Ubuntu/glibc.

**Comment by splifter** [comment]
Hey @tobbenb,

i mean the collabora online thing. Quickly googling seems it something else then only office?
Following a screenshot of the setting i mean:
![image](https://user-images.githubusercontent.com/406867/103763099-a3f3cb00-5019-11eb-8daa-00a4a38f5345.png)

**Comment by aptalca** [comment]
The implementation is similar for both. Nextcloud made a (difficult to comprehend) decision to bundle them (first onlyoffice, then switched to collabora) by pulling in a binary that only works on some platforms (amd64 and glibc). That binary does not work on arm32/arm64 systems and/or musl based systems which our alpine based image is using.

Ironically, nextcloud also publishes an alpine based version, which I'm assuming also doesn't work with the built in collabora.

You'll need to install the separate collabora container and enter its details into the collabora addon in nextcloud.

**Comment by splifter** [comment]
Thanks @aptalca a lot for the extensive explanation. This might be worth to note in the readme? Or did I missed it?

I've pulled the docker image from collabora and it's working just fine now.
