### ISSUE TITLE
20.0.5 wrong PHP version

### ISSUE THREAD

**Issue by XenorPLxx** [linuxserver/docker-nextcloud#174]
My nextcloud docker image was just updated to 20.0.5-ls113 and was greeted with:
```
This version of Nextcloud is not compatible with > PHP 7.3.
You are currently running 7.4.14.
```

**Comment by j0nnymoe** [comment]
Have you been updating nextcloud itself within the container and not just the image?

**Comment by XenorPLxx** [comment]
I didn't log into nextcloud I forever - I just use caldav and contacts services and my phone started spitting errors, so I went to investigate, noticed the update watchtower made to the docker and the message about Php version being too high when I try to visit the nextcloud website.

**Comment by j0nnymoe** [comment]
You need to be updating nextcloud within the container aswell the image updates, as per the readme: https://github.com/linuxserver/docker-nextcloud#application-setup

**Comment by XenorPLxx** [comment]
Woah I was at version 16.0.1 while current is 20.0.5. Thanks for the explanation!
