### ISSUE TITLE
Cannot load certificate error and time is in the future

### ISSUE THREAD

**Issue by kanintesova** [linuxserver/docker-nextcloud#178]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Be able to connect to docker container

## Current Behavior
Connection is refused. When I attached to container as it was starting I can see a lot of warnings about "time is in the future".

Then it loops with this output: nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

## Steps to Reproduce

1. Fired up the latest image
2.
3.
4.

## Environment
**OS:** Raspbian Buster
**CPU architecture:** arm64
**How docker service was installed:**

Installed via docker compose file.

## Command used to create docker container (run/create/compose/screenshot)
---
version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /appdata/nextcloud:/config
      - /appdata/nextcloud:/data
    ports:
      - 9430:443
    restart: unless-stopped

## Docker logs

-------------------------------------

GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

generating self-signed keys in /config/keys, you can replace these with your own keys if required

Generating a RSA private key

...........................................+++++

............................+++++

writing new private key to '/config/keys/cert.key'

-----

3069834128:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:

[cont-init.d] 30-keygen: exited 1.

[cont-init.d] 40-config: executing... 

[cont-init.d] 40-config: exited 0.

[cont-init.d] 50-install: executing... 

[cont-init.d] 50-install: exited 0.

[cont-init.d] 60-memcache: executing... 

[cont-init.d] 60-memcache: exited 0.

[cont-init.d] 70-aliases: executing... 

[cont-init.d] 70-aliases: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by tobbenb** [comment]
https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

You are probably hitting the above.
