### ISSUE TITLE
/usr/bin/occ is different than /config/www/nextcloud/occ, some commands don't work correctly.

### ISSUE THREAD

**Issue by stavros-k** [linuxserver/docker-nextcloud#179]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Command `occ config:app:set previewgenerator squareSizes --value="32 256"` shouldn't return errors.

## Current Behavior
Command returns the following error
```
root@574c879ea78c:/config/www/nextcloud# occ config:app:set previewgenerator squareSizes --value="32 256"

                                                                                    
  Too many arguments to "config:app:set" command, expected arguments "app" "name".  
                                                                                    

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```

## Steps to Reproduce
1. Bash in to container
2. run `occ config:app:set previewgenerator squareSizes --value="32 256"`
3. if you try `sudo -u abc occ config:app:set previewgenerator squareSizes --value="32 256"`, "abc is not in the sudoers file
4. You get the above error (Too many arguments).

## Possible solution
1. Bash in to container
2. `cd /config/www/nextcloud`
3. `chmod a+x occ`
4. `sudo -u abc ./occ config:app:set previewgenerator squareSizes --value="32 256"`
5. Now it works

## Environment
**OS:** Unraid
**CPU architecture:** x86_64
**How docker service was installed:** Installed from the communtity apps (which pulls from the official repo)

## Command used to create docker container (run/create/compose/screenshot)
`docker run -d --name='nextcloud' --net='bridge' -e TZ="Europe/Athens" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -p '9443:443/tcp' -v '/mnt/user/nextcloud/':'/data':'rw' -v '/mnt/user/appdata/nextcloud':'/config':'rw' 'linuxserver/nextcloud'`

## Docker logs
```
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing...
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing...
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 70-aliases: executing...
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by stavros-k** [comment]
Linking the issue i created on the rullzer/previewgenerator repo for more info.

**Comment by tobbenb** [comment]
/usr/bin/occ is just an alias for "php7 /config/www/nextcloud/occ". What happens if you run the full path in the alias instead of occ or /usr/bin/occ?
You could also exec into the container by using the abc user `docker exec -it -u abc nextcloud bash` and try the command again.

**Comment by stavros-k** [comment]
> /usr/bin/occ is just an alias for "php7 /config/www/nextcloud/occ". What happens if you run the full path in the alias instead of occ or /usr/bin/occ?
> You could also exec into the container by using the abc user `docker exec -it -u abc nextcloud bash` and try the command again.
> 
> Just looked at your command and error again and in the last line with the command syntax it says that --value= should be before previewgenerator squareSizes. So the command should be:
> `sudo -u abc occ config:app:set --value"32 256" previewgenerator squareSizes`
First, i have a typo, it must be --value="32 256". But other than that. the order of this flag doesn't really matter. 

running occ without sudo -u abc, doens't allow mutiple valeues on `--value`, but single values are accepted, here you can see order doesn't matter.
```
root@574c879ea78c:/# occ config:app:set previewgenerator heightSizes --value="256"
Config value heightSizes for app previewgenerator set to 256
```
Running the aliased command with `sudo -u abc`  says abc is not in sudoers.
```
root@574c879ea78c:/# sudo -u abc occ config:app:set --value="32 256" previewgenerator squareSizes
abc is not in the sudoers file.  This incident will be reported.
```
Here is the error without `sudo -u abc` (even with the correct order)
```
root@574c879ea78c:/# occ config:app:set --value="32 256" previewgenerator squareSizes

                                                                                    
  Too many arguments to "config:app:set" command, expected arguments "app" "name".  
                                                                                    

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```
Tried to run command from the path without any specified user 
```
root@574c879ea78c:/# ./config/www/nextcloud/occ config:app:set --value="32 256" previewgenerator squareSizes
Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 99
Try adding 'sudo -u #99' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 99' to the docker command (without the single quotes)
```
Running with `sudo -u abc` from the path, works 
```
root@574c879ea78c:/# sudo -u abc ./config/www/nextcloud/occ config:app:set --value="32 256" previewgenerator squareSizes
Config value squareSizes for app previewgenerator set to 32 256
```
Also with the flag in different order also works
```
root@574c879ea78c:/# sudo -u abc ./config/www/nextcloud/occ config:app:set previewgenerator squareSizes --value="32 256"
Config value squareSizes for app previewgenerator set to 32 256
```
occ is located here
```
root@574c879ea78c:/# type -a occ
occ is /usr/bin/occ
```
But looks like its different from the path here
```
root@574c879ea78c:/# cmp /usr/bin/occ /config/www/nextcloud/occ 
/usr/bin/occ /config/www/nextcloud/occ differ: char 4, line 1
```
`/usr/bin/occ` doesn't look like it's symlinked to `/config/www/nextcloud/occ`
```
root@574c879ea78c:/usr/bin# ls -al | grep occ
-rwxr-xr-x   1 root root       76 Jan 24 19:40 occ
```

**Comment by tobbenb** [comment]
Either I'm not explaining this good enough or you are not reading what I write and go off doing whatever you feel like.

1. You did not exec into the container as the abc user as I asked you to do. `docker exec -it -u abc nextcloud bash`
2. You did not run the full path as in the alias. `php7 /config/www/nextcloud/occ config:app:set --value="32 256" previewgenerator squareSizes`

Since you are running the alias (/usr/bin/occ), which is just an alias for the `php7 /config/www/nextcloud/occ` and not a symlink, it might be as simple as the quotes messing it up.

So please follow our guidance if you want help troubleshooting.

**Comment by stavros-k** [comment]
> 1. You did not exec into the container as the abc user as I asked you to do. `docker exec -it -u abc nextcloud bash`
Bashing as abc and running the full path works.
```
root@Prometheus:~# docker exec -it -u abc devNextcloud bash
bash: /root/.bashrc: Permission denied
abc@574c879ea78c:/$ php7 /config/www/nextcloud/occ config:app:set --value="32 256" previewgenerator squareSizes
Config value squareSizes for app previewgenerator set to 32 256
abc@574c879ea78c:/$ 
```

**Comment by tobbenb** [comment]
I had a look at the creation of the alias and it already has the sudo -u abc command and since you are running sudo -u abc also, you get the error message about abc not on the sudoers list.

So you can exec into the container without using -u abc and only run `occ config:app:set --value="32 256" previewgenerator squareSizes` and it should work.

**Comment by stavros-k** [comment]
> So you can exec into the container without using -u abc and only run `occ config:app:set --value="32 256" previewgenerator squareSizes` and it should work.

It does not work..
```
root@Prometheus:~# docker exec -it devNextcloud bash
root@574c879ea78c:/# occ config:app:set --value="32 256" previewgenerator squareSizes

                                                                                    
  Too many arguments to "config:app:set" command, expected arguments "app" "name".  
                                                                                    

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```

**Comment by tobbenb** [comment]
Might be your quotes. Try single quotes.

**Comment by stavros-k** [comment]
> Might be your quotes. Try single quotes.

Still no..

```
root@574c879ea78c:/# occ config:app:set --value='32 256' previewgenerator squareSizes

                                                                                    
  Too many arguments to "config:app:set" command, expected arguments "app" "name".  
                                                                                    

config:app:set [--output [OUTPUT]] [--value VALUE] [--update-only] [--] <app> <name>
```
But doing single value works...
```
root@574c879ea78c:/# occ config:app:set --value="32" previewgenerator squareSizes
Config value squareSizes for app previewgenerator set to 32
```

**Comment by tobbenb** [comment]
Why do you set it to two different ones?

**Comment by stavros-k** [comment]
> Why do you set it to two different ones?

I want thumbnails for both 32 and 256 pixels, 
32x32 are for the Files app in list mode and 256x256 for grid mode. 
Also thoses sizes are for android app also.

**Comment by stavros-k** [comment]
The command should take more than 2 values (according to the developer's [repo](https://github.com/rullzer/previewgenerator))

Also i'm following this [guide](https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/) to reduce thumbnail footprint and have only the needed thumnails

**Comment by tobbenb** [comment]
If you use a comma between the number the command works here. Does it create the correct thumbs then?

**Comment by stavros-k** [comment]
> If you use a comma between the number the command works here. Does it create the correct thumbs then?

Yes with comma command doens't produce errors, 
but it does not create correct thumbs, it takes the comma separeted values as one.

**Comment by tobbenb** [comment]
So it produce a 32,256 thumb?
How do you check what it creates?

**Comment by stavros-k** [comment]
> So it produce a 32,256 thumb?
> How do you check what it creates?

With the correct values
```
├── d
│   └── 9
│       └── 8
│           └── d
│               └── 1
│                   └── 3
│                       └── b
│                           └── 39758
│                               ├── 118-256.jpg
│                               ├── 256-256-crop.jpg
│                               ├── 256-555.jpg
│                               ├── 64-64-crop.jpg
│                               └── 945-2048-max.jpg
```

With comma sepparated values
```
├── d
│   └── 9
│       └── 8
│           └── d
│               └── 1
│                   └── 3
│                       └── b
│                           └── 39758
│                               ├── 118-256.jpg
│                               ├── 256-256-crop.jpg
│                               ├── 256-555.jpg
│                               ├── 64-64-crop.jpg
│                               ├── 945-2048-max.jpg
│                               └── 945-945-crop.jpg
```
It creates an extra thumbnail.

**Comment by tobbenb** [comment]
I'm just getting 256-256-crop.jpg here after running with commas and then uploading a photo.

Shouldn't the "32 256" that worked only make 32-32-crop.jpg and 256-256-crop.jpg?

Anyways, seems like you just have to use the full command to set these parameters as it doesn't work using the alias. Do a cat /usr/bin/occ to see what the bash files content is. If you know how to fix the occ command, please do so.

**Comment by stavros-k** [comment]
> I'm just getting 256-256-crop.jpg here after running with commas and then uploading a photo.
> 
> Shouldn't the "32 256" that worked only make 32-32-crop.jpg and 256-256-crop.jpg?
> 
> Anyways, seems like you just have to use the full command to set these parameters as it doesn't work using the alias. Do a cat /usr/bin/occ to see what the bash files content is. If you know how to fix the occ command, please do so.

I don't know exactly how generation works, i just see different results. If it's fixable with the alias, maybe add a note on the docs so others won't have to search (i've been looking why its not working for 2 weeks). I'm not an expert with linux, so it wasn't easy to see what was going on.

I'll check the occ bash, maybe i can figure out something and propose something at nextcloud repos.

Again, if not viable to fix it, i'm ok with it (also close the issue if thats the case)! Anyway it's not a config you do every day, i can do it without the alias! 
Thanks for your time!

**Comment by stavros-k** [comment]
just found that if you put the space separated values in single quotes and double quotes, works correctly.
```
root@574c879ea78c:/# occ config:app:set previewgenerator squareSizes --value='"32 256"'
Config value squareSizes for app previewgenerator set to 32 256
root@574c879ea78c:/# occ config:app:get previewgenerator squareSizes
32 256
```

I'll try after work if i can figure something out for the alias. But this is also a easier workaround and easier to document maybe.

**Comment by stavros-k** [comment]
Honestly, i don't believe there is a way to parse arguments with `$@` or `$*` and preserve the double quotes. I don't know much about bash, but from what i'm reading it's not possible.

Anyways. The most sane thing i can propose to this kind of problem is to update the documentation, that any double quoted argument must be inside single quotes.

e.g. `--value="32 256"` must be ``` --value=`"32 256"` ```

**Comment by aptalca** [comment]
Can you try escaping the quotes? `--value=\"32 256\"`

**Comment by stavros-k** [comment]
> Can you try escaping the quotes? `--value=\"32 256\"`

It works also.

**Comment by aptalca** [comment]
Ok thanks. That's what we should recommend in the readme.

That is why using spaces in bash arguments is a bad idea. Comma separated values would be much more appropriate and wouldn't require quotes

**Comment by Loader23** [comment]
Iam also having problems with adding a user with occ command:
`docker exec -it nextcloud occ user:add --display-name="'UT est'" --group="Test" --password-from-env --no-interaction utest`
It does not work because he wants to have the OC_PASS variable. `export OC_PASS=newpassword`
But even bash inside the container and executing the commands does not work. He does not recognize the export command.
Is this a bug?

**Comment by aptalca** [comment]
Either set the var as a container argument or set it in the same command

**Comment by Loader23** [comment]
I want to create a bunch of users so setting it as a container argument would result in the same password for everyone.
`docker exec -it -e OC_PASS="newpassword" nextcloud occ user:add --display-name="'UT est'" --group="Test" --password-from-env --no-interaction utest` is also not working.

**Comment by aptalca** [comment]
Try `docker exec -it nextcloud /bin/sh -c 'export OC_PASS=newpassword && occ user:add --display-name=\"UT est\" --group="Test" --password-from-env --no-interaction utest'`

**Comment by Loader23** [comment]
Sadly no, same error `--password-from-env given, but OC_PASS is empty!`

**Comment by aptalca** [comment]
From [nextcloud docs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#user-commands-label): 
`To use password-from-env you must run as “real” root, rather than sudo, because sudo strips environment variables.`
That's the issue.

Our occ implementation runs as the user running nextcloud via sudo, but you need to run as root.

So just exec in, do your export and then run `php7 /config/www/nextcloud/occ user:add blah`

**Comment by Loader23** [comment]
Thanks alot, thats working. I had to change ownership of config.php because of `Console has to be executed with the user that owns the file config/config.php` but then it worked :-)

**Comment by aptalca** [comment]
Good to hear. 

That's a nextcloud restriction. On the one hand, they want you to run occ as the unprivileged user, and on the other it says to run it as root for env vars.

**Comment by Loader23** [comment]
I want to add or warn that the user creation does not work as expected. The User creation via console is working but the Icon is broken and a login with the user is also not possible. There is still something not working right :-(

**Comment by tobbenb** [comment]
Use the full path to the occ instead of using our convenience script for easy use.

**Comment by Loader23** [comment]
I did that. As aptalca has written above:
`So just exec in, do your export and then run php7 /config/www/nextcloud/occ user:add blah`

**Comment by tobbenb** [comment]
Then it's probably something you should report to nextcloud

**Comment by Loader23** [comment]
And then they will say its a docker problem because its working with a "normal" installation...

**Comment by stavros-k** [comment]
> Ok thanks. That's what we should recommend in the readme.
> 
> That is why using spaces in cli arguments is a bad idea. Comma separated values would be much more appropriate and wouldn't require quotes

Should i close this issue? Or leave it as reminder to update the readme?

**Comment by crazygolem** [comment]
The issue is that parameter expansion is not done correctly in the `occ` alias; `/usr/bin/occ` created by https://github.com/linuxserver/docker-nextcloud/blob/3e35d88fd65d0e2158169603ab9b47aef5a3e185/root/etc/cont-init.d/70-aliases#L5

This makes commands like `occ theming:config --value="dis gonna gud." slogan` actually be executed as `php7 .../occ theming:config --value=dis gonna gud. slogan`.

To fix this, the `occ` alias should be changed to:
```sh
#!/bin/bash
sudo -u abc -s /bin/bash -c 'php7 /config/www/nextcloud/occ "$@"' - "$@"
```
so the positional arguments to the `occ` alias are properly passed as positional arguments to the script executed by sudo, which in turns expands them as properly quoted arguments.

so with proper quoting https://github.com/linuxserver/docker-nextcloud/blob/3e35d88fd65d0e2158169603ab9b47aef5a3e185/root/etc/cont-init.d/70-aliases#L5 should be rewritten as:
```sh
echo -e '#!/bin/bash\nsudo -u abc -s /bin/bash -c '\''php7 /config/www/nextcloud/occ "$@"'\'' - "$@"' > /usr/bin/occ
```

The `updater.phar` alias suffers from the same issue.

Not sure if it counts as a typo or is worthy of a PR, let me know.

**Comment by tobbenb** [comment]
If you are sure your fixes work, then please do make a PR.
