### ISSUE TITLE
Nextcloud 21 - Web Server is not properly set up to resolve "./well-known/..."

### ISSUE THREAD

**Issue by HannesJo0139** [linuxserver/docker-nextcloud#185]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Nextcloud 21 - Warning: 
There are some warnings regarding your setup.

- Your web server is not properly set up to resolve "/.well-known/webfinger". Further information can be found in the documentation.

- Your web server is not properly set up to resolve "/.well-known/nodeinfo". Further information can be found in the documentation.

------------------------------

## Expected Behavior
Nextcloud Security & Setup Warnings should pass all checks.

## Current Behavior
Nextcloud Security & Setup Warnings throws a warning that "/.well-known/..." is not solved properly by web server.

## Steps to Reproduce
1. Update Nextcloud instance to v. 21.
2. Go to Admin -> Settings -> Administration Overview

## Steps to Solve the Issue
1. Edit nginx config file /nginx/site-confs/default
2. Around line 45, find and delete:
```
    location = /.well-known/carddav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host:$server_port/remote.php/dav;
    }
    location = /.well-known/webfinger {
      return 301 $scheme://$host:$server_port/public.php?service=webfinger;
    }
    location = /.well-known/host-meta {
      return 301 $scheme://$host:$server_port/public.php?service=host-meta;
    }
    location = /.well-known/host-meta.json {
      return 301 $scheme://$host:$server_port/public.php?service=host-meta-json;
    }
```
3. According to [Nextcloud Docs NGINX config](https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html), insert the following:
```
    # Rule borrowed from `.htaccess` to handle Microsoft DAV clients
    location = / {
        if ( $http_user_agent ~ ^DavClnt ) {
            return 302 /remote.php/webdav/$is_args$args;
        }
    }
    # Make a regex exception for `/.well-known` so that clients can still
    # access it despite the existence of the regex rule
    # `location ~ /(\.|autotest|...)` which would otherwise handle requests
    # for `/.well-known`.
    location ^~ /.well-known {
        # The following 6 rules are borrowed from `.htaccess`

        location = /.well-known/carddav     { return 301 /remote.php/dav/; }
        location = /.well-known/caldav      { return 301 /remote.php/dav/; }
        # Anything else is dynamically handled by Nextcloud
        location ^~ /.well-known            { return 301 /index.php$uri; }

        try_files $uri $uri/ =404;
    }
```
4. Save and close file
5. Restart container

A pull request has been created: https://github.com/linuxserver/docker-nextcloud/pull/186

**Comment by EVOTk** [comment]
It's okay for me ! Thx

**Comment by aptalca** [comment]
#188

**Comment by reloxx13** [comment]
this does not respect another mapped port in docker eg 8888:80     
`mydomain.com:8888/.well-known/carddav` will redirect to `mydomain.com/remote.php/dav/`   

to fix it, u have to use `$scheme://$http_host`, $http_host will include the port.
`location = /.well-known/caldav  { return 301 $scheme://$http_host/remote.php/dav/; }`

this is missing everywhere in the nginx config with redirects.    
i dont use a reverse proxy, someone should test and confirm that this is still working with a reverse proxy.

**Comment by aptalca** [comment]
> this does not respect

What is `this` you're referring to? It's a 3 year old issue report. Much has changed in the confs since then

**Comment by reloxx13** [comment]
> > this does not respect
> 
> What is `this` you're referring to? It's a 3 year old issue report. Much has changed in the confs since then

the linked pullrequest, the redirects are still the same in the site conf (i edited my top post)

**Comment by j0nnymoe** [comment]
This isn't an issue, many of us run this with this without the error. If you're experiencing this, please open a new issue and provide the requested information.

**Comment by reloxx13** [comment]
of course its an issue if the mapped port is getting lost and this issue and pull request here from years ago caused it, as you can see the port was repected before.   
many are not changing the port and if you use the search function just like me youll find enough issues with it.   

you have all informations you need in this issue here.

**Comment by djodars89** [comment]
@reloxx13 was right, this is still an issue (1,2,3) and fixed by adding the missing "$scheme://$http_host" to lines 95, 96 and 103 of the default.conf (3,4,5)

BEFORE:
(1)
![image](https://github.com/linuxserver/docker-nextcloud/assets/30188668/f9719ed8-7345-42e8-8d13-5c5ccb69712f)

(2)
![image](https://github.com/linuxserver/docker-nextcloud/assets/30188668/aeab2a23-bb6a-4405-ac65-5f4e4a13c1f3)

(3)
![image](https://github.com/linuxserver/docker-nextcloud/assets/30188668/0e2c2d50-6c31-4b27-8b47-b33b6e0fa1fb)

AFTER:
(4)
![image](https://github.com/linuxserver/docker-nextcloud/assets/30188668/45f6d34c-984c-471c-9862-bbd6809d643d)

(5)
![image](https://github.com/linuxserver/docker-nextcloud/assets/30188668/db7f74ae-5dde-46c0-9778-d6f95f282b42)

(6)
![image](https://github.com/linuxserver/docker-nextcloud/assets/30188668/2c5b1a0c-8ce5-4476-818e-78b2a5e7e88b)

**Comment by sgtcoder** [comment]
This modification fixed it for me, it was a bit of changes, but it's working now

```
    location ^~ /.well-known {
        # The rules in this block are an adaptation of the rules
        # in `.htaccess` that concern `/.well-known`.

        location = /.well-known/carddav { return 301 https://$http_host/remote.php/dav; }
        location = /.well-known/caldav  { return 301 https://$http_host/remote.php/dav; }

        location = /.well-known/webfinger { return 301 https://$http_host/index.php/.well-known/webfinger; }
        location = /.well-known/nodeinfo  { return 301 https://$http_host/index.php/.well-known/nodeinfo; }

        location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
        location /.well-known/pki-validation    { try_files $uri $uri/ =404; }

        # Let Nextcloud's API for `/.well-known` URIs handle all other
        # requests by passing them to the front-end controller.
        return 301 https://$http_host/index.php$request_uri;
    }
```

**Comment by procoprobocop** [comment]
> Эта модификация исправила это для меня, было немного изменений, но теперь все работает
> 
> ```
>     location ^~ /.well-known {
>         # The rules in this block are an adaptation of the rules
>         # in `.htaccess` that concern `/.well-known`.
> 
>         location = /.well-known/carddav { return 301 https://$http_host/remote.php/dav; }
>         location = /.well-known/caldav  { return 301 https://$http_host/remote.php/dav; }
> 
>         location = /.well-known/webfinger { return 301 https://$http_host/index.php/.well-known/webfinger; }
>         location = /.well-known/nodeinfo  { return 301 https://$http_host/index.php/.well-known/nodeinfo; }
> 
>         location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
>         location /.well-known/pki-validation    { try_files $uri $uri/ =404; }
> 
>         # Let Nextcloud's API for `/.well-known` URIs handle all other
>         # requests by passing them to the front-end controller.
>         return 301 https://$http_host/index.php$request_uri;
>     }
> ```

Thank you very much! Only this could solve my problem!

**Comment by VeloAddict** [comment]
The problem is this:
```
curl -i https://my.public.domain/.well-known/webfinger  ✔  at 07:15:27 PM  HTTP/2 301 access-control-allow-headers: authorization,content-type access-control-allow-methods: GET,OPTIONS,PUT access-control-allow-origin: * alt-svc: h3=":443"; ma=2592000 content-type: text/html date: Mon, 25 Aug 2025 16:15:28 GMT location: http://my.public.domain/index.php/.well-known/webfinger referrer-policy: no-referrer server: nginx strict-transport-security: max-age=31536000; includeSubDomains; preload x-content-type-options: nosniff x-frame-options: SAMEORIGIN x-permitted-cross-domain-policies: none x-robots-tag: noindex, nofollow x-xss-protection: 1; mode=block content-length: 162 <html> <head><title>301 Moved Permanently</title></head> <body> <center><h1>301 Moved Permanently</h1></center> <hr><center>nginx</center> </body> </html>
```

It redirects to HTTP instead of HTTPS
