### ISSUE TITLE
PHP Broken

### ISSUE THREAD

**Issue by RFBomb** [linuxserver/docker-nextcloud#190]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Docker container just works

## Current Behavior
Docker container errors out with this message when viewing nextcloud in web browser:

```
This version of Nextcloud is not compatible with > PHP 7.3.
You are currently running 7.4.15.
```

## Environment
**OS:** OpenMediaVault
**CPU architecture:** x86_64
**How docker service was installed:** 

 

## Command used to create docker container (run/create/compose/screenshot)

Launching via Portainer Stack using stack below:

 nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    networks:
      - Bridge
    environment:
      - PUID=1002
      - PGID=995
      - TZ=America/New_York
    volumes:
      - /sharedfolders/DockerConfigs/NextCloud/NextCloud:/config
      - /sharedfolders/BackupDrive_1/NextCloud:/data
    ports:
      - 443:443
    restart: unless-stopped

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1002,
User gid:    995,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
using keys found in /config/keys,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 40-config: executing... ,
[cont-init.d] 40-config: exited 0.,
[cont-init.d] 50-install: executing... ,
[cont-init.d] 50-install: exited 0.,
[cont-init.d] 60-memcache: executing... ,
[cont-init.d] 60-memcache: exited 0.,
[cont-init.d] 70-aliases: executing... ,
[cont-init.d] 70-aliases: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
```

**Comment by Roxedus** [comment]
Roll back your image, then upgrade nextcloud itself until you reach nextcloud 20, as noted in the application setup part of the readme. Then you can update the image, and it won't complain.

**Comment by RFBomb** [comment]
is this not the whole idea behind updating the docker image itself?

**Comment by Roxedus** [comment]
This one is a exception, we don't want to mess things up for the user, as nextcloud has a update process that sometimes needs delicate hands.

**Comment by RFBomb** [comment]
ok, so I'm working my way through the update process. But it is a slog to get through. 
Mostly because I cannot use the self-updater, nor can I use the command line updater. 

![Capture](https://user-images.githubusercontent.com/20431767/110061224-3cb27880-7d35-11eb-89e0-f5951b439ba0.PNG)

It appears that it is failing to ever download the updates file. Where is it supposed to download this file into? I have been unable to find any information on the destination. 

For now, I've been manually downloading the zip and replacing the 'www\nextcloud' folder on the nas to go between versions.
