### ISSUE TITLE
Traefik configuration with nextcloud image

### ISSUE THREAD

**Issue by Whisper40** [linuxserver/docker-nextcloud#191]
So again a report for this..

Why this image is not using like others HTTP...
I'm using Traefik V2 behind containers, i redirect each traffic from http to https, but with this image it fails..
I would like to request a correction of this or an environment variable that can be used in order to be able to use http.

Thanks for your consideration

I'm using those labels in my traefik global configuration : 
```
    # Http -> Https
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
```

And in my app configuration i would like to use it : 
```
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud_{{ user }}-router.entrypoints=websecure"
      - "traefik.http.routers.nextcloud_{{ user }}-router.rule=Host(`{{ user }}-${NEXTCLOUD_BASE_URL}-${BASE_URL}`)"
      - "traefik.http.routers.nextcloud_{{ user }}-router.service=nextcloud_{{ user }}-service"
      - "traefik.http.routers.nextcloud_{{ user }}-router.tls=true"
      - "traefik.http.services.nextcloud_{{ user }}-service.loadbalancer.server.port=443"
```

**Comment by tobbenb** [comment]
This shouldn't be a problem to do using træfik. Closing as this is not an issue with this container.

**Comment by Whisper40** [comment]
It souldn't be a problem but why don't you purpose a solution for this ?
It's better for everyone that will encouter the problem..

It's a stragic issue of this image yes, it's the only one i'm using that is https only..

**Comment by aptalca** [comment]
The solution is telling your reverse proxy to use https

**Comment by Whisper40** [comment]
For everyone (in traefik global) : 
- "--serverstransport.insecureskipverify=true" Needed because there is a self signed certificate into nextcloud

In my app : 
- "traefik.http.services.nextcloud_{{ user }}-service.loadbalancer.server.scheme=https" ( what said @aptalca )

**Comment by justuspfaue** [comment]
Hey @Whisper40 , you are the hero of my life. I wasn't able to recover my nextcloud after a "accident" due to the same error you encountered. As I am more or less a monkey hitting the keyboard with his head, I spent like 25 hours hitting my head against a wall and setting up a vm with snap-nextcloud to get access to my stuff. You just made my day so much better. Do you want a beer? If so, text me mate.

**Comment by Whisper40** [comment]
Hello <3 I hope your message will show @aptalca that by giving a simple information, we can solve the problem of many people ;)
Have fun ;)

**Comment by aptalca** [comment]
> Hello <3 I hope your message will show @aptalca that by giving a simple information, we can solve the problem of many people

Nope, all it shows me is you're still missing the purpose of this `Issues` section. Perhaps you need to read the issue template again.

**Comment by cver** [comment]
@Whisper40 I can't make it work, can you point me what's wrong is this code, thanks
```
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.nextcloud.tls.true
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=https
      - traefik.http.services.nextcloud.loadbalancer.server.port=443
```

**Comment by Whisper40** [comment]
@cver Hello, i suggest you to look this repository : [Github Repo](https://github.com/Merrick28/seedbox-docker)

[Nextcloud File](https://github.com/Merrick28/seedbox-docker/blob/master/dockers/nextcloud/nextcloud.yml)
[Traefik Global Config](https://github.com/Merrick28/seedbox-docker/blob/master/docker-compose.yml)

**Comment by MOIS3Y** [comment]
Hello!
Something that many may miss.
There are two options:
**static configuration** - will be applied to all backends
**dynamic configuration** - for a specific backend (lsio nextcloud)

Static you can globally declare ignoring certificate verification in traefik.yml
https://doc.traefik.io/traefik/routing/overview/
`serversTransport:
    insecureSkipVerify: true`


Dynamic (you need to give it a meaningful name) I have this ignorecert
https://doc.traefik.io/traefik/routing/providers/docker/
`http:
    serversTransports:
       ignorecert:
          insecureSkipVerify: true     # for linuxserver-nextcloud container`

Labels for your nextcloud container:
`    labels:
      - "traefik.enable=true" <---- enable detection of this container by traefik
      - "traefik.http.routers.nextcloud.entrypoints=web,websecure" <--- my name entrypoints 80, 443
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.server.domain`)"  <--- domain smatch
      - "traefik.http.routers.nextcloud.tls=true" <--- complete the handshake with the client on the traffic side
      - "traefik.http.routers.nextcloud.tls.certresolver=production" <--- my name is let's encrypt
      - "traefik.http.routers.nextcloud.service=nextcloud" <--- tell the router which service to use for the backend
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https" # It is typical for nextcloud, because the container works on the https protocol.
      - "traefik.http.services.nextcloud.loadbalancer.serverstransport=ignorecert@file" <--- what we defined in the dynamic configuration
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443" <--- port on which nextcloud container listens`
