### ISSUE TITLE
NextCloud 21: High Performance Backend

### ISSUE THREAD

**Issue by ntompson** [linuxserver/docker-nextcloud#194]
It's not clear to me whether the new [NextCloud 21 High Performance Backend](https://nextcloud.com/blog/nextcloud-hub-21-out-with-up-to-10x-better-performance-whiteboard-and-more-collaboration-features/) is supported in the LinuxServer image. If it is, do I need to do something to invoke it? There seems to be a [ton of confusion](https://help.nextcloud.com/t/setting-up-files-high-performance-backend/108651) on the NextCloud forums, and I can't see anything that describes it here. I'm holding off upgrading to v21 until it is clear.

**Comment by aptalca** [comment]
In the last few releases, in desperate attempts to position themselves as a free open source Google Drive alternative, Nextcloud has gone into marketing overdrive with tremendous PR mumbo jumbo so it is difficult discern what some of these improvements or additions really are.

The whole thing with `Nextcloud Hub` branding, and building in various half baked solutions that don't work everywhere, and switching one for the other (first onlyoffice as `documentserver` and then replacing it with collabora), etc. it's getting more and more confusing.

It looks like what they're referring to with the new buzzwords `High Performance Backend` is a combination of redis cache and push notifications to clients: https://github.com/nextcloud/notify_push

But I could be wrong

**Comment by ntompson** [comment]
I agree - it's all confusing. But what does it mean for the LSIO container?

**Comment by AndreaPro** [comment]
> In the last few releases, in desperate attempts to position themselves as a free open source Google Drive alternative, Nextcloud has gone into marketing overdrive with tremendous PR mumbo jumbo so it is difficult discern what some of these improvements or additions really are.
> 
> The whole thing with `Nextcloud Hub` branding, and building in various half baked solutions that don't work everywhere, and switching one for the other (first onlyoffice as `documentserver` and then replacing it with collabora), etc. it's getting more and more confusing.
> 
> It looks like what they're referring to with the new buzzwords `High Performance Backend` is a combination of redis cache and push notifications to clients: https://github.com/nextcloud/notify_push
> 
> But I could be wrong

I've tried ti enable It in nextcloud 21.0.1 and systemd is required ti make It running. Is possibile to enable it in the docker container?

**Comment by j0nnymoe** [comment]
Not in it's current form, no.

**Comment by AndreaPro** [comment]
So I guess that the answer to the OP is: no, High Performance Backend is not supported in the Linux server image right now because it requires systems.
My question is: it will be supported in next releases?

**Comment by j0nnymoe** [comment]
As @aptalca mentioned already `High Performance Backend` is just buzz words/marketing. 

In all honestly, just adding redis caching to nextcloud and also switching over to our PHP8 image already makes a massive improvement. The thing you're trying to install is just for android notifications. It likely would need to be released as a docker mod with then some manual intervention I guess.

**Comment by AndreaPro** [comment]
Redis and PHP8 are a big improvement for sure, but one big issue with the nextcloud clients especially on big folders is that the sync happens by checking all the files periodically, if they are moving to a sync that happens only when a file is modified I think that is a big performance improvement for all clients

**Comment by ntompson** [comment]
So I've been using redid for a long time but PHP8 I'm not sure about. Is this part of the standard LSIO image or a modification?

**Comment by j0nnymoe** [comment]
We have a php8 tag for nextcloud: `docker pull ghcr.io/linuxserver/nextcloud:php8-version-21.0.1` - just make sure you're on the latest version of nextcloud already.

**Comment by milch** [comment]
You can get notify_push to work by using s6 to launch the `notify_push` daemon. You can do this by placing a script like this in `/etc/services.d/notify_push/run` after creating the folder `/etc/services.d/notify_push/`:

```bash
#!/bin/sh
NEXTCLOUD_BASE="/config/www/nextcloud"
NOTIFY_PUSH_BIN="$NEXTCLOUD_BASE/apps/notify_push/bin/x86_64/notify_push"
if [ -f "$NOTIFY_PUSH_BIN" ]; then
  "$NOTIFY_PUSH_BIN" "$NEXTCLOUD_BASE/config/config.php"
fi
```

Make sure it has the execute bit set (`chmod +x /etc/services.d/notify_push/run`). 

Other than that just make sure to follow the [remaining setup guide](https://github.com/nextcloud/notify_push/blob/main/README.md#reverse-proxy). After that you can restart the docker container, and s6 should automatically launch the daemon. To troubleshoot you can also run the script above directly.

Regarding whether this actually improves performance or not: I'm using it to sync my Lightroom catalog. LR creates a ton of small files which makes a full sync take a VERY long time (~15min on my laptop via wifi). As expected with `notify_push` a full sync is almost never triggered, and I can see updated files getting pushed between my laptop and my desktop in real time.

**Comment by j0nnymoe** [comment]
@milch nice work - for the script location, you'll want to put it in the folder as described here : https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

Otherwise it'll get knocked out when you do an image update.

**Comment by AndreaPro** [comment]
> You can get notify_push to work by using s6 to launch the `notify_push` daemon. You can do this by placing a script like this in `/etc/services.d/notify_push/run` after creating the folder `/etc/services.d/notify_push/`:
> 
> ```shell
> #!/bin/sh
> NEXTCLOUD_BASE="/config/www/nextcloud"
> NOTIFY_PUSH_BIN="$NEXTCLOUD_BASE/apps/notify_push/bin/x86_64/notify_push"
> if [ -f "$NOTIFY_PUSH_BIN" ]; then
>   "$NOTIFY_PUSH_BIN" "$NEXTCLOUD_BASE/config/config.php"
> fi
> ```
> 
> Make sure it has the execute bit set (`chmod +x /etc/services.d/notify_push/run`).
> 
> Other than that just make sure to follow the [remaining setup guide](https://github.com/nextcloud/notify_push/blob/main/README.md#reverse-proxy). After that you can restart the docker container, and s6 should automatically launch the daemon. To troubleshoot you can also run the script above directly.
> 
> Regarding whether this actually improves performance or not: I'm using it to sync my Lightroom catalog. LR creates a ton of small files which makes a full sync take a VERY long time (~15min on my laptop via wifi). As expected with `notify_push` a full sync is almost never triggered, and I can see updated files getting pushed between my laptop and my desktop in real time.

I've tried following your instructions but I get this error:

```
The application panicked (crashed).
Message:  error binding to 0.0.0.0:7867: error creating server listener: Address in use (os error 98)
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.1/src/server.rs:283
```

I have nextcloud in a docker compose together with mariadb and redis on default ports

**Comment by Loader23** [comment]
After setting the url with occ notify_push:setup https://cloud.example.com/push i get this error:
```
✓ redis is configured
🗴 push server is not receiving redis messages (received 439268216, got 0)
```

**Comment by J4gQBqqR** [comment]
Help needed:
Can I or should I add the following lines to config/php/php-local.ini:
```
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.max_accelerated_files=10000
opcache.huge_code_pages=1
opcache.enable_file_override=1 
opcache.jit_buffer_size=128M
opcache.jit=1255
```

I am not very familiar with php configs. 
Can someone advice? Thank you for your help.

**Comment by OmarWazzan** [comment]
Was looking to implement this, and appears it can actually take the form of a docker. Refer to:

https://hub.docker.com/r/icewind1991/notify_push

https://www.reddit.com/r/NextCloud/comments/m3emm9/nextcloud_with_hpb_dockercompose_example/

**Comment by 2fst4u** [comment]
> We have a php8 tag for nextcloud: `docker pull ghcr.io/linuxserver/nextcloud:php8-version-21.0.1` - just make sure you're on the latest version of nextcloud already.

Is the PHP version a requirement for redis to work? And are there any limitations to deploying this version?

**Comment by darkorb** [comment]
>  The thing you're trying to install is just for android notifications.

This is no longer the case - it's used by VFS as outlined in https://github.com/nextcloud/desktop/issues/1337 to improve the usability of it. May also be required under other OS's for the same (Windows supports VFS apparently).
