### ISSUE TITLE
Last update of nginx config breaks rainloop and ldap_user apps

### ISSUE THREAD

**Issue by sepo83** [linuxserver/docker-nextcloud#195]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Rainloop app shows up. ldap_user app shows current  configuration in settings.

## Current Behavior

Rainloop app only shows a blank screen. ldap_user app shows an empty configuration in settings.

Reason seems to be the updated `nginx/site-confs/default`. I know that it was done according to official nextcloud documentation.
Issues are already discussed e.g.:
* https://github.com/pierre-alain-b/rainloop-nextcloud/issues/230
* https://github.com/nextcloud/documentation/pull/2197
* https://github.com/nextcloud/documentation/pull/6221

## Steps to Reproduce

1. apply  https://github.com/linuxserver/docker-nextcloud/commit/868122601b205aa6f8a25d92fba8c0bf3c1e806d to `nginx/site-confs/default` resp. update the docker-image, delete `nginx/site-confs/default` and restart the container
2. reverting `nginx/site-confs/default` to previouse version makes rainloop and ldap_user apps work again

## Environment
**OS:** Linux  5.6.0-0.bpo.2-amd64 #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) x86_64 GNU/Linux
**CPU architecture:** x86_64
**How docker service was installed:**

as provided by OpenMediaVault

## Docker logs

e.g. log/nginx/error.log
````
2021/03/28 17:12:24 [error] 413#413: *117 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /config/www/nextcloud/apps/rainloop/app/index.php:8
Stack trace:
#0 /config/www/nextcloud/apps/rainloop/app/rainloop/v/1.15.0/include.php(57): __get_custom_data_full_path()
#1 /config/www/nextcloud/apps/rainloop/app/index.php(23): include('/config/www/nex...')
#2 {main}
  thrown in /config/www/nextcloud/apps/rainloop/app/index.php on line 8" while reading response header from upstream, client: 192.168.xxx.xxx, server: _, request: "GET /apps/rainloop/app/?OwnCloudAuth HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxx"
````

**Comment by sepo83** [comment]
I found this workaround https://github.com/nextcloud/documentation/pull/2197#issuecomment-721432337 which works for me.

**Comment by llasse** [comment]
Not sure if this is related, however I do have a problem when trying to use the ldap / ad integration app in nextcloud, which does not let me proceed further when entering my ldap-credentials (doesnt show any error either, just locks me without any further messages)
as far as I understand it this is an nginx-config related problem:
https://github.com/nextcloud/server/issues/24314
https://github.com/nextcloud/server/issues/16194

**Comment by docfactory37** [comment]
im also having this isssue
