### ISSUE TITLE
Cant download from SMB share, PHP error

### ISSUE THREAD

**Issue by MrToast72** [linuxserver/docker-nextcloud#198]
Hey everyone, first time posting here so hopefully I can explain this all right. 

Recently setup my Linux server/docker-nextcloud image using the dockercompose template. Going through the setup was all fine and dandy, even setting up my SMB share was perfect. I can see everything in my SMB share from nextcloud and I can upload anything. When I try to download anything from the SMB share I get an error both from the webpage and app that I can't download that right now and when I check the logs I get a huge error. Any help would be appreciated. 

**Expected Behavior**
Should be able to download anything from SMB share.

**Current Behavior**
Anytime I try to download anything from my SMB share, I get these 2 errors listed below.

**Steps to Reproduce**
1. Tap the 3 dots next too file I want to download
2. Tap download.
3. Recive an error saying "can't download image"
4. Same goes for web page.

**Environment**
Windows server 2019, running latest Docker Desktop. I use Protainer to manage all my docker compose files and what not.

**Command used to create docker container (run/create/compose/screenshot)**
I use Docker Compose to create my nextcloud server, my file is below.

`
version: "2.1" 
services: 
   nextcloud: 
    image: ghcr.io/linuxserver/nextcloud 
    container_name: nextcloud1 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Regina 
    volumes: 
      - /path/to/appdata:/config 
      - /path/to/data:/data 
    ports: 
      - 8081:443 
    restart: unless-stopped
`

`   

    Error: fread(): Icewind\SMB\Native\NativeReadStream::stream_read - read 87615 bytes more data than requested (95807 read,  

    8192 max) - excess data will be lost at /config/www/nextcloud/apps/files_external/3rdparty/icewind/streams

    /src/Wrapper.php#55

    <<closure>>

    OC\Log\ErrorHandler::onError()

    /config/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php - line 55:

    fread()

    /config/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php - line 96:

    Icewind\Streams\Wrapper->stream_read()

    <<closure>>

    Icewind\Streams\CallbackWrapper->stream_read()

    /config/www/nextcloud/lib/private/Preview/ProviderV2.php - line 92:

    file_put_contents()

    /config/www/nextcloud/lib/private/Preview/Image.php - line 50:

    OC\Preview\ProviderV2->getLocalFile()

    /config/www/nextcloud/lib/private/Preview/GeneratorHelper.php - line 63:

    OC\Preview\Image->getThumbnail()

    /config/www/nextcloud/lib/private/Preview/Generator.php - line 244:

    OC\Preview\GeneratorHelper->getThumbnail()

    /config/www/nextcloud/lib/private/Preview/Generator.php - line 140:

    OC\Preview\Generator->getMaxPreview()

    /config/www/nextcloud/lib/private/Preview/Generator.php - line 109:

    OC\Preview\Generator->generatePreviews()

    /config/www/nextcloud/lib/private/PreviewManager.php - line 190:

    OC\Preview\Generator->getPreview()

    /config/www/nextcloud/apps/files/lib/Controller/ApiController.php - line 130:

    OC\PreviewManager->getPreview()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Files\Controller\ApiController->getThumbnail()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController()

    /config/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /config/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /config/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match()

    /config/www/nextcloud/index.php - line 37:

    OC::handleRequest()`

And 

` 

    Error
    PHP
    2021-04-12T11:53:38-0600
    Error: imagealphablending() expects parameter 1 to be resource, bool given at /config/www/nextcloud/lib/private/legacy    
    /OC_Image.php#588

    <<closure>>

    OC\Log\ErrorHandler::onError()

    /config/www/nextcloud/lib/private/legacy/OC_Image.php - line 588:

    imagealphablending()

    /config/www/nextcloud/lib/private/Preview/Image.php - line 52:

    OC_Image->loadFromFile()

    /config/www/nextcloud/lib/private/Preview/GeneratorHelper.php - line 63:

    OC\Preview\Image->getThumbnail()

    /config/www/nextcloud/lib/private/Preview/Generator.php - line 244:

    OC\Preview\GeneratorHelper->getThumbnail()

    /config/www/nextcloud/lib/private/Preview/Generator.php - line 140:

    OC\Preview\Generator->getMaxPreview()

    /config/www/nextcloud/lib/private/Preview/Generator.php - line 109:

    OC\Preview\Generator->generatePreviews()

    /config/www/nextcloud/lib/private/PreviewManager.php - line 190:

    OC\Preview\Generator->getPreview()

    /config/www/nextcloud/apps/files/lib/Controller/ApiController.php - line 130:

    OC\PreviewManager->getPreview()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Files\Controller\ApiController->getThumbnail()

    /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController()

    /config/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /config/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /config/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match()

    /config/www/nextcloud/index.php - line 37:

    `OC::handleRequest()`

Please ignore the terrible formatting, im inept and cant format for crap lol

**Comment by aSpeX2009** [comment]
Hey,
it's a problem with Nextcloud 21.0.1 (or 20.0.9), not a problem with the container: [https://github.com/nextcloud/server/issues/26457](url)
Solution: Use an older "apps/files_external/3rdparty/icewind" folder from Nextcloud 21.0.0 or something.

**Comment by MrToast72** [comment]
> Hey,
> it's a problem with Nextcloud 21.0.1 (or 20.0.9), not a problem with the container: [https://github.com/nextcloud/server/issues/26457](url)
> Solution: Use an older "apps/files_external/3rdparty/icewind" folder from Nextcloud 21.0.0 or something.

Thanks for the reply man. I'm not sure I understand how to go about that? Plus your link doesn't go anywhere lll

**Comment by aSpeX2009** [comment]
Sorry, link's fixed now.
Download an older version of Nextcloud (21.0.0) and replace your "config-volume/_data/www/nextcloud/app/files_external/3rdparty/icewind"-folder with the downloaded (older) one.

**Comment by MrToast72** [comment]
> Sorry, link's fixed now.
> Download an older version of Nextcloud (21.0.0) and replace your "config-volume/_data/www/nextcloud/app/files_external/3rdparty/icewind"-folder with the downloaded (older) one.

Ohhhh ok that makes sense then. How would you do that with it installed in docker? Do I just mount that folder and download the older version and then replace it in that bound folder? Sorry for all the questions, I'm fairly new to docker and self hosting 😅

**Comment by j0nnymoe** [comment]
It will be in your `/config/www/nextcloud` folder you mounted.

**Comment by MrToast72** [comment]
> It will be in your `/config/www/nextcloud` folder you mounted.

And this is why I have a staples button lol, thank you for confirming that for me Jonny

**Comment by MrToast72** [comment]
So after mounting a couple other SMB drives, it seems it's just 1 drive that is causing this issue. I still haven't reloaded the older Icewind file, I just wanted to test if it happens with all drives attached and it doesn't. I'm going to reload that old file later today and see if that helps.

**Comment by MrToast72** [comment]
Just wanted to come back and make sure I close this. Installing the older `config-volume/_data/www/nextcloud/app/files_external/3rdparty/icewind` Indeed worked. I downloaded 19.0.10 and it works great! Thank you @aSpeX2009 and @j0nnymoe for your help on this! 

Ill end it on a meme,
If your bro ever asks you "am I fat" your only response should be "bro I know 5 fat people and your 4 of them"
