### ISSUE TITLE
permanently banned for attempting to report issue

### ISSUE THREAD

**Issue by Motophan** [linuxserver/docker-nextcloud#200]
6 months ago I was permanently banned from the discord for reporting an issue with this container.

no swear words were used on any occasion by either party. 

can I be unbanned?
there are other people reporting issues who are not being banned.

**Comment by aptalca** [comment]
`permanently banned from the discord for reporting an issue with this container`
That was not at all the reason for your ban. You were told this before.

You were banned for your behavior, more specifically, you were combative, arrogant and rude. After several warnings, you continued your unacceptable behavior, which resulted in your ban.

Seeing as you are still oblivious to that fact (or in complete denial), the ban stays.

Please stop opening github issues to discuss your discord ban as this is not appropriate. The issue template explains what these issues are for. Not following the rules will result in a ban from our github. Consider this an official warning.
