### ISSUE TITLE
Storage is temporarily not available after upgrade

### ISSUE THREAD

**Issue by callahan22** [linuxserver/docker-nextcloud#201]
Hi,

I've just upgraded my Nextcloud instance using the following process that I've always used to update in the past:

1. sudo docker stop nextcloud
2. sudo docker-compose pull nextcloud
3. sudo docker-compose up -d nextcloud
4. sudo docker image prune
5. sudo docker exec -it nextcloud updater.phar
6. Keep maintenance mode active? N

The update went fine but now, when accessing my NC instance, I get the warning:

```
Storage with mount id 2 is not available
Storage is temporarily not available
```

Checking the error log file at: 

`./docker/nextcloud/config/log/nginx/error.log`

shows:
```
2021/06/02 10:57:31 [error] 396#396: *331 FastCGI sent in stderr: "PHP message: PHP Warning:  filemtime(): stat failed for /config/www/nextcloud/version.php in /config/www/nextcloud/lib/private/legacy/OC_Util.php on line 557PHP$
Stack trace:
#0 /config/www/nextcloud/lib/private/Log/ErrorHandler.php(92): OC\Log->logException()
#1 /config/www/nextcloud/remote.php(167): OC\Log\ErrorHandler::onError()
#2 /config/www/nextcloud/remote.php(167): require_once()
#3 {main}
  thrown in /config/www/nextcloud/lib/private/Log.php on line 318PHP message: PHP Fatal error:  main(): Failed opening required '/appinfo/v1/webdav.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www$
2021/06/02 10:57:31 [error] 396#396: *333 FastCGI sent in stderr: "PHP message: PHP Warning:  filemtime(): stat failed for /config/www/nextcloud/version.php in /config/www/nextcloud/lib/private/legacy/OC_Util.php on line 557PHP$
Stack trace:
#0 /config/www/nextcloud/lib/private/Log/ErrorHandler.php(92): OC\Log->logException()
#1 /config/www/nextcloud/remote.php(167): OC\Log\ErrorHandler::onError()
#2 /config/www/nextcloud/remote.php(167): require_once()
#3 {main}
```
I can't tell if this is the cause of the issue however. Trying to access my installtion from my Android client, I am informed that the server is in Maintenance mode. Ironically, this "maintanence mode" was the reason I upgraded. Over the last month, the Android client has been playing up and refusing to auto upload my synced folders from the phone. Using the Android app manually however worked fine. this update was an attempt to fix this issue. It's instead broken things completely! :-)

If anyone can point me at what the issue might be, I'd appreciate it.

**Comment by tobbenb** [comment]
Please use the issue template

**Comment by callahan22** [comment]
Apologies, will do so in the future. However, I've just gone back to the instance and it's now up. From looking at the docker logs -f, it was not showing anything pending and was to all appearances, up and running. Whether there were pending changes being made to the backend DB, I can't say but for whatever reason, the instance now seems to be up. Will leave this here in case anyone else has the same issue.

Thanks.
