### ISSUE TITLE
Issue with certificate of Nextcloud

### ISSUE THREAD

**Issue by bmcunha** [linuxserver/docker-nextcloud#202]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
To work as usual 😀

## Current Behavior
Can't create the certificate

## Steps to Reproduce

1. Normal procedural (followed all the instructons)

## Environment
**OS:** Raspbian
**CPU architecture:** arm32 
**How docker service was installed:** Portainer

## Command used to create docker container (run/create/compose/screenshot)

![sdasdsdsssss](https://user-images.githubusercontent.com/34158123/121678273-e6c93b80-caae-11eb-821b-9dbb56bc11c0.jpg)

## Docker logs

-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
Brought to you by linuxserver.io,
-------------------------------------,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
User uid:    1000,
User gid:    1000,
-------------------------------------,
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,
Your DockerHost is most likely running an outdated version of libseccomp,
To fix this, please visit https://docs.linuxserver.io/faq#libseccomp,
Some apps might not behave correctly without this,
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
generating self-signed keys in /config/keys, you can replace these with your own keys if required,
Generating a RSA private key,
......+++++,
................+++++,
writing new private key to '/config/keys/cert.key',
-----,
1996415888:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:,
[cont-init.d] 30-keygen: exited 1.,
[cont-init.d] 40-config: executing... ,
[cont-init.d] 40-config: exited 0.,
[cont-init.d] 50-install: executing... ,
[cont-init.d] 50-install: exited 0.,
[cont-init.d] 60-memcache: executing... ,
[cont-init.d] 60-memcache: exited 0.,
[cont-init.d] 70-aliases: executing... ,
[cont-init.d] 70-aliases: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file),
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file),
nginx: [emerg] cannot load certificate "/config/keys/cert.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/config/keys/cert.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file),

**Comment by Roxedus** [comment]
From your logs: 
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,
Your DockerHost is most likely running an outdated version of libseccomp,
To fix this, please visit https://docs.linuxserver.io/faq#libseccomp,
Some apps might not behave correctly without this,
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
Patch your host
