### ISSUE TITLE
Nextcloud is spawning endless cron jobs that never ends with 100% CPU usage.

### ISSUE THREAD

**Issue by Dominik-1980** [linuxserver/docker-nextcloud#204]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Cronjob should finish within some minutes.

## Current Behavior
Cronjob hangs forever going to D state (uninterruptible sleep) and spawns a new one ever 5 minutes.
No chance to kill the process because of the D state.
Even no chance to kill the docker nextcloud container.
It prevents my whole system to shutdown regularly.

## Steps to Reproduce
Just run nextcloud docker image

## Environment
OS: Raspbian
CPU architecture: armhf
How docker service was installed: Native on Raspbian

## Command used to create docker container (run/create/compose/screenshot)

`version: "2"
services:

  nextcloud:
    image: linuxserver/nextcloud:version-21.0.2
    container_name: nextcloud
    networks:
      - homeserver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /srv/dev-disk-by-uuid-77365390-c57e-4b8a-846f-42fa099bf411/docker/appdata/nextcloud/config:/config
      - /srv/dev-disk-by-uuid-77365390-c57e-4b8a-846f-42fa099bf411/docker/appdata/nextcloud/data:/data
    links:
      - mariadb
    labels:
      - "diun.enable=true"
    restart: unless-stopped
    
  mariadb:
    image: yobasystems/alpine-mariadb:armhf
    container_name: mariadb
    networks:
      homeserver:
        ipv4_address: 172.18.0.20
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=xxx
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - /srv/dev-disk-by-uuid-77365390-c57e-4b8a-846f-42fa099bf411/docker/appdata/mariadb/logs:/var/lib/mysql/mysql-bin
      - /srv/dev-disk-by-uuid-77365390-c57e-4b8a-846f-42fa099bf411/docker/appdata/mariadb/mysql/_data:/var/lib/mysql
    restart: unless-stopped
    
  phpmyadmin:
    container_name: phpmyadmin-nextcloud
    image: phpmyadmin
    networks:
      - homeserver
    restart: unless-stopped
    environment:
      - PMA_HOST=172.18.0.20
      - PMA_PORT=3306
    ports:
      - 8182:80
      
networks:
  homeserver:
    external:
      name: homeserver
`

**Comment by Dominik-1980** [comment]
No one else with this problem??

Any chance to find out which part of the cronjob doesn't respond?

**Comment by j0nnymoe** [comment]
Are you able to provide any logs from the container? This is the first time we've heard of an issue like this.

**Comment by Dominik-1980** [comment]
There are many people with this problem. 
But most is related to the maps app…
If you type „nextcloud cronjob hangs“ into google, there are many discussions on the nextcloud forum.
But for me, I got no workaround…
How can I provide some logs from the cronjob?

**Comment by j0nnymoe** [comment]
Logs from the `/config/logs` also an output of all the processes that keep spawning please.

**Comment by aptalca** [comment]
> If you type „nextcloud cronjob hangs“ into google, there are many discussions on the nextcloud forum.

I clicked on a few of those links and it seems it's not an issue with our image. The culprit seems to be the maps app. Not sure if there is anything we can do as it's an upstream issue.

**Comment by homerr** [comment]
If you are able to find any further information on this one to give us a steer on if we have a container issue or not, please reopen. Until then closing this one down.

**Comment by Bodenseematze** [comment]
I currently also have this problem - with Nextcloud 22.2.3 and I don't have the maps app installed!
I have the following two errors in my log - which I think are not related to the problem:
----------------------------------------------
{"reqId":"5vKYh0f4vESMq12cJ79e","level":3,"time":"2021-12-15T10:51:27+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Function libxml_disable_entity_loader() is deprecated at /home/www/nextcloud-22/lib/private/Updater/VersionCheck.php#100","userAgent":"--","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Function libxml_disable_entity_loader() is deprecated at /home/www/nextcloud-22/lib/private/Updater/VersionCheck.php#100","Code":0,"Trace":[{"file":"/home/www/nextcloud-22/lib/private/Updater/VersionCheck.php","line":100,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8192,"Function libxml_disable_entity_loader() is deprecated","/home/www/nextcloud-22/lib/private/Updater/VersionCheck.php",100]},{"file":"/home/www/nextcloud-22/apps/updatenotification/lib/Notification/BackgroundJob.php","line":101,"function":"check","class":"OC\\Updater\\VersionCheck","type":"->","args":[]},{"file":"/home/www/nextcloud-22/apps/updatenotification/lib/Notification/BackgroundJob.php","line":86,"function":"checkCoreUpdate","class":"OCA\\UpdateNotification\\Notification\\BackgroundJob","type":"->","args":[]},{"file":"/home/www/nextcloud-22/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\UpdateNotification\\Notification\\BackgroundJob","type":"->","args":[null]},{"file":"/home/www/nextcloud-22/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/home/www/nextcloud-22/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/home/www/nextcloud-22/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61b9be1c9f10e"}
----------------------------------------------

[no app in context] Error: Repair step 'OCA\Mail\Command\RepairMailTheads' is unknown

GET /settings/apps/update/mail
----------------------------------------------

**Comment by nerozero** [comment]
I have same issue, logs are empty.
