### ISSUE TITLE
Cannot start the app, Issue with PHP

### ISSUE THREAD

**Issue by zaggash** [linuxserver/docker-nextcloud#21]
2017/03/12 02:54:06 [error] 305#305: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /config/www/nextcloud/lib/private/Security/SecureRandom.php:81
Stack trace:
#0 /config/www/nextcloud/lib/private/Security/SecureRandom.php(81): random_int(0, 63)
#1 /config/www/nextcloud/lib/private/AppFramework/Http/Request.php(576): OC\Security\SecureRandom->generate(20)
#2 /config/www/nextcloud/lib/private/Log/File.php(93): OC\AppFramework\Http\Request->getId()
#3 [internal function]: OC\Log\File::write('PHP', 'Exception: Coul...', 3)
#4 /config/www/nextcloud/lib/private/Log.php(301): call_user_func(Array, 'PHP', 'Exception: Coul...', 3)
#5 /config/www/nextcloud/lib/private/Log.php(159): OC\Log->log(3, 'Exception: Coul...', Array)
#6 /config/www/nextcloud/lib/private/Log/ErrorHandler.php(81): OC\Log->critical('Exception: Coul...', Array)
#7 [internal function]: OC\Log\ErrorHandler::onException(Object(Exception))
#8 {main}
  thrown in /config/www/nextcloud/lib/private/Security/SecureRandom.php on line 81
PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /config/www/nextcloud/lib/private/Security/SecureRandom.php:81
Stack trace:
#0 /config/www/nextcloud/lib/private/Security/SecureRandom.php(81): random_int(0, 63)
#1 /config/www/nextcloud/lib/private/AppFramework/Http/Request.php(576): OC\Security\SecureRandom->generate(20)
#2 /config/www/nextcloud/lib/private/Log/File.php(93): OC\AppFramework\Http\Request->getId()
#3 [internal function]: OC\Log\File::write('PHP', 'Uncaught Except...', 3)
#4 /config/www/nextcloud/lib/private/Log.php(301): call_user_func(Array, 'PHP', 'Uncaught Except...', 3)
#5 /config/www/nextcloud/lib/private/Log.php(159): OC\Log->log(3, 'Uncaught Except...', Array)
#6 /config/www/nextcloud/lib/private/Log/ErrorHandler.php(68): OC\Log->critical('Uncaught Except...', Array)
#7 [internal function]: OC\Log\ErrorHandler::onShutdown()
#8 {main}
  thrown in /config/www/nextcloud/lib/private/Security/

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Debian 8

Default docker command in README

Nothing in the docker log

**Comment by CHBMB** [comment]
@zaggash I've installed this a lot, not had any issues.  Was this before or after you setup the database?

**Comment by zaggash** [comment]
Actually, its at the really beginning.
When I try to access the first webpage after the container is started.

I's a fresh new container with fresh new folders.

**Comment by CHBMB** [comment]
@zaggash What's your docker run command and I'll see if I can reproduce.  Only time I've seen anything like that was when I started my container up without my mariadb running.  But that was after setup...

**Comment by zaggash** [comment]
nextcloud:
    image: linuxserver/nextcloud
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      PUID: 1000
      PGID: 55555
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nextcloud:/config
      - ./data:/data
    ports:
      - 8443:443


I do not start a mysql container since I plan to use sqlite which is enough for my own usage.
It worked well with the lsiodev container, but now there is no more updates on it and it is deleted from the dockerhub :/

**Comment by sparklyballs** [comment]
what is the host os and kernel ?

**Comment by CHBMB** [comment]
Debian 8, he doesn't mention the kernel @sparklyballs

**Comment by sparklyballs** [comment]
https://github.com/docker-library/php/issues/376#issuecomment-282285050

**Comment by zaggash** [comment]
Yep might be it indeed.

**Comment by zaggash** [comment]
Yep might be it indeed.

**Comment by zaggash** [comment]
I tried to downgrade php7, but I cannot downgrade to php 7.0.15-r0 on alpine, it is not available on 3.5 isn't it ?

**Comment by Dukestep** [comment]
I am experiencing the same issue on a Synology DS216+ running DSM 6.1.

**Comment by zaggash** [comment]
Solved with new PHP version.
@sparklyballs, feel free to close the issue when you'll push the update :)

**Comment by sparklyballs** [comment]
the update has been pushed. 

i'll close.
