### ISSUE TITLE
version 22 not being retrieved using portainer

### ISSUE THREAD

**Issue by z-vap** [linuxserver/docker-nextcloud#210]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Version 22 should be retrieved and started
## Current Behavior

build_version 	Linuxserver.io version:- 18.0.4-ls78 Build-date:- 2020-05-06T11:37:58+00:00

## Steps to Reproduce

1.  Stop current nextcloud Container
2.  Pull linuxserver/docker-nextcloud 
3.  Start container
4. Version in nextcloud client is reported as 18.0.4.2

## Environment
**OS: Windows 10 **
**CPU architecture:** x86_64
**How docker service was installed:**

Installed via Portainer 
https://hub.docker.com/r/linuxserver/nextcloud

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1002
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing... 
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing... 
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 70-aliases: executing... 
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by j0nnymoe** [comment]
I don't have any experience on how portainer works but when updating containers, you should be pulling the new image then re-creating the container for it to pickup the new image. This is how it's done via docker run commands and docker-compose.

**Comment by cravas** [comment]
After you upload the image from linuxserver, you need to update the Nextcloud via the WebGUI (NOT Portainer) or via CLI with the occ command.
The warning that a new update is available will show on an "Admin" notifications.

Although, not entirely sure but from version v18, I think you need to update gradually (v19 then v20, v21,etc) until you reach the latest version.

**Comment by z-vap** [comment]
OK thanks. I did not think of that.   I will try using the gui first then try gradual updates using docker.

**Comment by homerr** [comment]
This concerns me though;

`build_version Linuxserver.io version:- 18.0.4-ls78 Build-date:- 2020-05-06T11:37:58+00:00`

Doesn't look like it's even attempting to pull the latest image down... might be worth looking into this a little more. If Portainer mucks you around too much go into shell and issue the commands manually to pull the latest image. Might turn up an error you can work with...

**Comment by homerr** [comment]
Gonna close this off as I'm pretty sure it's an issue in portainer. If I'm wrong, please reopen.

**Comment by z-vap** [comment]
Sorry I have not been able to test since.   real life has been keeping me busy.   Thanks
