### ISSUE TITLE
mail App - KItinerary binary adapter is not available, can't extract information

### ISSUE THREAD

**Issue by Jonas-itquirks** [linuxserver/docker-nextcloud#212]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
I think it may be related to this: https://github.com/nextcloud/mail/issues/2765
It´s no big deal, but I thought I should mention it as it seems to be related to alpine and from the comments it looks like it is fixable. Nextcloud version is 21.04. docker image version is latest: Linuxserver.io version:- 22.1.0-ls148 Build-date:- 2021-08-15T17:36:06+02:00

## Expected Behavior

Well it should work and no warning should be shown in the logs.
## Current Behavior

A warning is shown in the nextcloud logs if I open the mail app from the dashboard.
## Steps to Reproduce

1. fresh install with added groupware features including mailapp
2. connect mail account
3. open mail app
4. maybe some mails with attachments are needed as that is what the KItinerary binary adapter is needed for

## Environment
**OS:**
**CPU architecture:** 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
**How docker service was installed:**
official docker repo
Docker version 20.10.8, build 3967b7d

## Docker logs

- nothing wrong here

## Nextcloud log entry
{... ,"app":"mail","method":"GET","url":"/apps/mail/api/messages/13796/body","message":"KItinerary binary adapter is not available, can't extract information","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"21.0.4.1", ...}

**Comment by Jonas-itquirks** [comment]
Could someone verify if this is really a problem with current alpine image?

**Comment by hugalafutro** [comment]
Hi, this is happening to me on Nextcloud 22.2.3 and Mail App version 1.11.5 running off `linuxserver/nextcloud:latest` with this [docker-compose.yml](https://o.o5.ddns.net/kV3ol). For what it's worth it does not seem to affect any functionality, it just keep s popping up in logs. I've skimmed other issues and on my install the `<...>vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor` file was chmod 764. Message in log is identical to OP.

**Comment by musti71189** [comment]
Hi, i have the same problem on Nextcloud 23.0.0 with Mail App v. 1.11.15. Also running on linuxserver/nextcloud:latest with unraid.
I recognize that i havent the files vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor. What can i do for find a solution for this warning.
