### ISSUE TITLE
cannot connect to mariadb with ip:port port is not default 

### ISSUE THREAD

**Issue by hppyworld** [linuxserver/docker-nextcloud#214]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
connect to 192.168.1.1:1234
port 1234 which is not default for maria db can not connect

## Steps to Reproduce

1. docker-compose up

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    ports:
      - 443:443
    restart: unless-stopped

## Docker logs

nextcloud    | [cont-init.d] 30-keygen: exited 0.
nextcloud    | [cont-init.d] 40-config: executing... 
nextcloud    | [cont-init.d] 40-config: exited 0.
nextcloud    | [cont-init.d] 50-install: executing... 
nextcloud    | [cont-init.d] 50-install: exited 0.
nextcloud    | [cont-init.d] 60-memcache: executing... 
nextcloud    | [cont-init.d] 60-memcache: exited 0.
nextcloud    | [cont-init.d] 70-aliases: executing... 
nextcloud    | [cont-init.d] 70-aliases: exited 0.
nextcloud    | [cont-init.d] 90-custom-folders: executing... 
nextcloud    | [cont-init.d] 90-custom-folders: exited 0.
nextcloud    | [cont-init.d] 99-custom-files: executing... 
nextcloud    | [custom-init] no custom files found exiting...
nextcloud    | [cont-init.d] 99-custom-files: exited 0.
nextcloud    | [cont-init.d] done.
nextcloud    | [services.d] starting services
nextcloud    | [services.d] done.

**Comment by GregHilston** [comment]
I've been running into the same situation

**Comment by j0nnymoe** [comment]
I believe this should be a question for upstream. Nextcloud would need to support it. If it does end up being an issue with our container and it works elsewhere, please report back.
