### ISSUE TITLE
Adding Apps within Nextcloud gives error

### ISSUE THREAD

**Issue by JoeStratton** [linuxserver/docker-nextcloud#22]
When I try to add any app inside of nextcloud (External Storage support for example) it sits for a minute then says "Error while enabling app"

Are apps supported with this container? Am I missing something? Thanks!

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

unRAID
![nextcloud](https://cloud.githubusercontent.com/assets/6180439/24000835/9b307d3c-0a19-11e7-8684-877a491fb786.PNG)

**Comment by CHBMB** [comment]
When you set the container up what did you set the nextcloud data location as?  ie what is your variable in **config.php** for this?

`  'datadirectory' => '/data',`

**Comment by JoeStratton** [comment]
Hi,
in /appdata/nextcloud/www/nextcloud/config/config.php:

'datadirectory' => '/data',

**Comment by CHBMB** [comment]
@JoeStratton Following that logic the way your shares are mapped you should have multiple folders in '/mnt/user' like `files` `files_external` and files like `index.html`  I can't help but wonder that it would have been better/solved this issue if `/data` was mapped to `/mnt/user/nextcloud` when you set this up.

**Comment by JoeStratton** [comment]
Yes, i misunderstood the point of /data, this solved it. Thanks

**Comment by CHBMB** [comment]
@JoeStratton Glad to hear it....
