### ISSUE TITLE
Ensure there is a file called ".ocdata" in the root of the data directory

### ISSUE THREAD

**Issue by gowthamnatarajan** [linuxserver/docker-nextcloud#220]
## Expected Behavior
When I click Web UI it should open the dashboard.

## Current Behavior
If I open webUI I get the error mentioned in the title

## Steps to Reproduce
Install NextCloud from linuxserver in Unraid 6.9.2. 
Click Open Web UI

## Environment
**OS:Unraid 6.9.2
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
From Unraid Apps page

**Comment by MRobi1** [comment]
Seeing the same thing here.
Any time the container restarts, I need to connect to the container and run "touch .ocdata" which creates a blank file otherwise nextcloud cannot be accessed.  Not sure what causes the file to be continuously removed on start, but I need to do this every single time.

**Comment by smailpouri** [comment]
Same here

**Comment by j0nnymoe** [comment]
Commenting on an issue that got marked as invalid isn't helpful. Please open a fresh issue and provide the issue requested.
