### ISSUE TITLE
gateway time-out

### ISSUE THREAD

**Issue by changliangta** [linuxserver/docker-nextcloud#223]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Submission invalid due to ignoring the requested information in the issue template. Please fill this in first so we can provide support.
