### ISSUE TITLE
PHP Fatal Error:

### ISSUE THREAD

**Issue by shaade381** [linuxserver/docker-nextcloud#227]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

**Comment by shaade381** [comment]
After installing the Docker for UNRAID, everything was working for that about 24 hours and then the Nexcloud woud not respond and I started getting the following errors the logs:


[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing...
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing...
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 70-aliases: executing...
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
PHP Warning: require(/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Fatal error: require(): Failed opening required '/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Warning: require(/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Fatal error: require(): Failed opening required '/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Warning: require(/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Fatal error: require(): Failed opening required '/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Warning: require(/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Fatal error: require(): Failed opening required '/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Warning: require(/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Fatal error: require(): Failed opening required '/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Warning: require(/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

PHP Fatal error: require(): Failed opening required '/config/www/nextcloud/3rdparty/composer/../symfony/polyfill-intl-normalizer/bootstrap.php' (include_path='/config/www/nextcloud/3rdparty/pear/archive_tar:/config/www/nextcloud/3rdparty/pear/console_getopt:/config/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/config/www/nextcloud/3rdparty/pear/pear_exception:/config/www/nextcloud/apps') in /config/www/nextcloud/3rdparty/composer/autoload_real.php on line 66

**Comment by j0nnymoe** [comment]
I'm going to assume you haven't setup you appdata folder correctly and it's moved all your data off your cache drive onto your array thus breaking the container.

**Comment by shaade381** [comment]
That is a valid assumption,  it was installed in the the wrong locaation and it was physically moved to the .....cache/appdata/docker/nextcloud location
