### ISSUE TITLE
Add postgresql-client to the packages that are included with the docker container

### ISSUE THREAD

**Issue by brayrobert201** [linuxserver/docker-nextcloud#228]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
pg_dump is installed, which is used by https://github.com/nextcloud/backup

## Current Behavior
pg_dump is not installed. So the above backup plugin doesn't work.

## Alternatives Considered
None. Difficult to think of any that don't include creating processes outside of the above backup plugin.

**Comment by mhahl** [comment]
It has been suggested that we should be using this instead:

https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by brayrobert201** [comment]
I like it.
