### ISSUE TITLE
Error when assembling chunks, status code 504

### ISSUE THREAD

**Issue by hppyworld** [linuxserver/docker-nextcloud#232]
Hello, 

When uploading huge video file via webbrowser, at the end of upload, error pops up in browser 
"Error when assembling chunks, status code 504"

Please tell how to fix it? thanks

**Comment by j0nnymoe** [comment]
Please provide all the information that was requested when you opened this issue.

**Comment by wmutschl** [comment]
https://github.com/linuxserver/docker-nextcloud/issues/52#issuecomment-1074067489 might be related!

**Comment by Evgeny-SPB** [comment]
> [#52 (comment)](https://github.com/linuxserver/docker-nextcloud/issues/52#issuecomment-1074067489) might be related!

To upload big files you need to increase client_max_body_size and timeouts. This two issues combined solve one problem :)
