### ISSUE TITLE
support for fail2ban needed

### ISSUE THREAD

**Issue by hppyworld** [linuxserver/docker-nextcloud#233]
Hello, 

Please provide support for fail2ban so it can survive containers update or new container creation. May be from docker-compose ? Thanks.

**Comment by j0nnymoe** [comment]
We won't be adding fail2ban to the container itself. We offer fail2ban via our SWAG reverse proxy solution.
Otherwise, you can customise this container and install it yourself: https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
