### ISSUE TITLE
PHP OPcache module is not properly configured: OPcache interned strings buffer is nearly full

### ISSUE THREAD

**Issue by masterwishx** [linuxserver/docker-nextcloud#235]
Using docker for (Unraid) (Linux x64)
The issue is opened in official nextcloud:
https://github.com/nextcloud/docker/issues/1692

**Comment by aptalca** [comment]
for now you can edit the `php-local.ini` in your config folder and the change will be persistent

**Comment by masterwishx** [comment]
> for now you can edit the `php-local.ini` in your config folder and the change will be persistent

you mean to add ?
opcache.interned_strings_buffer=16';

**Comment by masterwishx** [comment]
but this will be fixed in next versions of this docker ?

**Comment by aptalca** [comment]
whatever's suggested there to make it work. `php-local.ini` appends `php.ini` on container start

**Comment by aptalca** [comment]
> but this will be fixed in next versions of this docker ?

we'll follow nextcloud's lead since it's an upstream issue

**Comment by masterwishx** [comment]
i have this message after update to 23.0.4

![image](https://user-images.githubusercontent.com/28630321/165777469-7b42ad30-5a50-4c87-8cc4-2a63722954b6.png)
