### ISSUE TITLE
nginx command within the container fails. pid is in wrong location.

### ISSUE THREAD

**Issue by horriblenoises** [linuxserver/docker-nextcloud#242]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Send `nginx -s reload` command to within the container should reload nginx.

## Current Behavior

```
nginx: [error] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
```
The pid file is in `/run/nginx.pid`

## Steps to Reproduce

1. From host, run command `docker exec -it nextcloud /usr/sbin/nginx -s reload`
2. Bask in disappointment

## Environment
**OS:** Rasbian Bullseye
**CPU architecture:** arm32
**How docker service was installed:**

distro repo

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d \
  --name=nextcloud \
  --restart unless-stopped \
  -e PUID=1024 \
  -e PGID=1024 \
  -e TZ=America/New_York \
  -p 80:80 \
  -p 443:443 \
  -v /docker/nxt/config:/config \
  -v /docker/nxt/data:/data \
  -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro \
  lscr.io/linuxserver/nextcloud
```

**Comment by j0nnymoe** [comment]
Don't use nginx within the container to reload the config, just restart the container.

**Comment by horriblenoises** [comment]
My motivation for "reloading" nginx is a certificate update while not interrupting current up/downloads. If I'm mistaken and current file transfers are halted, then yes, that obvious sledgehammer approach would suffice.

**Comment by aptalca** [comment]
> Send nginx -s reload command to within the container should reload nginx.

It might work on a bare metal default Ubuntu installation, but you can't expect it to work universally. It has to do with how the service is configured and supervised.

**Comment by drizuid** [comment]
this is not a bug we don't support restarting in this manner. OP needs to look into how to use s6 to restart a service. As a note, we do not support doing so, our suggestion is to restart the container to avoid issues.
