### ISSUE TITLE
Release image update for Nextcloud v24

### ISSUE THREAD

**Issue by cravas** [linuxserver/docker-nextcloud#247]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Updated image based on latest Nextcloud version 24.

## Current Behavior

Your latest release is stil on v23.0.4

## Steps to Reproduce

1. Check github linuxserver image and it's on v23.0.4
2. On nextcloud, there is already the warning that there's an update to stable v24
3. Don't know if it will be OK to update Nextcloud to a Major higher version prior to have the corresponding updated image container (to the same version)

## Environment
**OS: RaspiOS 10 buster
**CPU architecture: arm64
**How docker service was installed:**

Running docker via an OpenMediaVault installation

**Comment by aptalca** [comment]
Here's an issue about it: https://github.com/nextcloud/nextcloud.com/issues/1647
and a related one here: https://github.com/nextcloud/server/issues/31198

**Comment by aptalca** [comment]
> Now, the question remains:
Will it be OK to update NC version on their GUI while the linuxserver image is still 1 Major version behind?

I'm surprised you're even given an option to update (unless you're on the beta/unstable track). Nextcloud doesn't usually make a major version update available to existing users until a point release.

Feel free to try it out. Unless they had some major changes with new deps in the new release (hasn't been the case in the last few), it should be fine.

Make sure to have a proper backup first, though (as with any update).

**Comment by cravas** [comment]
> I'm surprised you're even given an option to update (unless you're on the beta/unstable track). Nextcloud doesn't usually make a major version update available to existing users until a point release.

I was surprised also and it's on STABLE release:
![image](https://user-images.githubusercontent.com/21242022/167660791-45c29cf3-2880-464e-9c1b-787d00064475.png)

> Feel free to try it out. Unless they had some major changes with new deps in the new release (hasn't been the case in the last few), it should be fine.

I do have backups but since I'm on the imminence of migrating the server, I prefer to postpone any hiccups for later.
Nonetheless, I'll keep this updated in the case I do the update.

I'll close this issue since it's something that needs only a small change to the php from Nextcloud to mark the v24 as STABLE.

Thank you for the support and for these great images, ;)

**Comment by cravas** [comment]
Just some info, after running the NC update to v24, this error came up:
![image](https://user-images.githubusercontent.com/21242022/167677684-7199b241-2ebd-40db-b502-1617cd714e74.png)

Bashed into the container and ran the command:
`occ db:add-missing-indices`

Now, all is normal, ;)

**Comment by aptalca** [comment]
Thanks for the confirmation. Yeah, database indexes may need to be added when updating. Nextcloud doesn't do it automatically because they don't want things to break (if you restart in the middle of it for instance, thinking it crashed). We wouldn't do that either (for the same reason), so it's a manual operation.
