### ISSUE TITLE
PHP 8.1 for Nextcloud 24.0.1

### ISSUE THREAD

**Issue by J4gQBqqR** [linuxserver/docker-nextcloud#251]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Nextcloud 24 now supports PHP8.1.

## Current Behavior

There is no PHP8 nor PHP8.1 image for Nextcloud 24. I just updated from PHP8 branch of 23.0.4 to 24.0.1, and was not able to use a PHP8 image for this version.

## Alternatives Considered

Support Nextcloud 24 with PHP8.0.

**Comment by j0nnymoe** [comment]
Our PHP8 image will work with v24 fine but at the moment you have to deploy v23 then upgrade within the image to v24.

The source we were checking for updates is no longer being updated by the nextcloud Devs so we've had to change how the check works. It's been done on the main branch but not been done on the PHP8 branch yet.

**Comment by martabal** [comment]
Php 7.3 is no more supported https://github.com/nextcloud/server/pull/29286

Would be nice to officially move to php 8.

**Comment by flipponweb** [comment]
I updated the app 24.02.23 at my unraid server to the latest version and got:

This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.

How can I fix this ?

**Comment by thespad** [comment]
> I updated the app 24.02.23 at my unraid server to the latest version and got:
> 
> This version of Nextcloud is not compatible with > PHP 8.0. You are currently running 8.1.16.
> 
> How can I fix this ?

https://github.com/linuxserver/docker-nextcloud/issues/288

**Comment by thespad** [comment]
Image is now running PHP 8.1

**Comment by flipponweb** [comment]
lscr.io/linuxserver/nextcloud:latest

This one ?

**Comment by nemchik** [comment]
> lscr.io/linuxserver/nextcloud:latest
> 
> This one ?

Please read all of https://github.com/linuxserver/docker-nextcloud/issues/288

**Comment by DrHugs** [comment]
Was this resolved?

Force updated but still received the same error message.

"This version of Nextcloud is not compatible with > PHP 8.0. You are currently running 8.1.16."
