### ISSUE TITLE
External Storage not in sync with the physical storage

### ISSUE THREAD

**Issue by ambarusa** [linuxserver/docker-nextcloud#256]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Guys, I'm so happy how Nextcloud container provided from _linuxserver_ works, it was so much straight-forward to configure addresses, proxies after launch. Only thing for me to solve is keeping in sync my storages mapped as Local External Storage. They are not getting up-to-date never, only if I run `occ files-scan` command. Can you give a hint, how is the best to solve this issue combined with this container?

Thank you.
------------------------------

## Expected Behavior

External storage directory within Nextcloud should be in sync with the actual physical storage, after a shorter period of time.

## Current Behavior

External storage directory within Nextcloud is not in sync with the actual physical storage at all.

## Steps to Reproduce

1. Add a larger directory External storage in the Nextcloud (Local was used in my case)
2. Make changes on the storage externally.
3. Check if the changes are available in the Nextcloud after a shorter period of time.

## Environment
**OS:** Ubuntu 20.04.4 LTS
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

compose

**Comment by BigRrred** [comment]
Yes, please resolve this one. I've been having the same issue, but on Intel x64, not arm. 
It is running in portainer, make through docker compose. Changes in nextcloud immediately update in the SMB share, but never the other way around. I find I have to open a document (I use collabora), and when that gets saved, everything updates.

**Comment by Limoniak** [comment]
Same problem for me
