### ISSUE TITLE
Setting up Postgres database on first install doesn't input details correctly

### ISSUE THREAD

**Issue by 2fst4u** [linuxserver/docker-nextcloud#257]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Inputting postgres database details on the first boot should correctly pass details to the config.php file.

## Current Behavior
Inputting postgres database details on the first boot results in the NextCloud administrator account details being used as the postgres user, and the postgres database name gets "oc_" appended to the front. These details are verified in the config.php file and need to be manually fixed.

## Steps to Reproduce

1. Create postgres database instance
2. Start linuxserver/docker-nextcloud instance fresh
3. Input postgres details
4. After clicking "install" NextCloud will not load as the information is wrong. 
5. Manually edit the config.php file and note the details for postgres are wrong.

## Environment
**OS:** Ubuntu 21.10 and Ubuntu 22.04 as the host
**CPU architecture:** arm64
**How docker service was installed:** via kubernetes as a StatefulSet

## Command used to create docker container (run/create/compose/screenshot)
Kubernetes statefulset on K3S

## Docker logs
Nil logs of this event. 

I have tried this twice on different occasions and it has stumped me. I'm not sure if it's an upstream NextCloud issue or if it's specific to this container.

**Comment by 2fst4u** [comment]
Bump

**Comment by alejandro-angulo** [comment]
I'm experiencing the same issue on version `25.0.1-ls211`. I think none of the environment variables listed in the "Auto configuration via environment variables" section [here](https://hub.docker.com/_/nextcloud) are being respected.

I was using nextcloud-maintained docker image and those environment variables worked there (I didn't see a message in the web UI warning me about using sqlite and I was able to set an admin username/password). I guess this is something specific to their docker image and not the app itself.

**Comment by j0nnymoe** [comment]
Our container isn't configurable via env variables.
