### ISSUE TITLE
ERROR: unsatisfiable constraints while do Docker build

### ISSUE THREAD

**Issue by Homer-Sim** [linuxserver/docker-nextcloud#26]
Hello,

I copied github files and did build image
with
docker build -t nextcloud .

But I am receiving this error:

fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
so:libcrypto.so.41 (missing):
required by:
php7-ftp-7.0.17-r5[so:libcrypto.so.41]
so:libssl.so.43 (missing):
required by:
php7-ftp-7.0.17-r5[so:libssl.so.43]

**Comment by sparklyballs** [comment]
we provide prebuilt images

**Comment by Homer-Sim** [comment]
I know but I wanted to disable SSL and just let container listen on 80.
It worked some weeks ago in the same way and normally your Dockerfile should work shouldn't it?

**Comment by sparklyballs** [comment]
the dockerfile worked at the last time the image was built, we built the image from the Dockerfile after all.

alpine repositories often have updates etc and package dependencies change and sometimes those changes take time to propagate or need fixing by alpine.

if you want to disable ssl then just edit the local copies of nginx.conf and the default file for nextcloud virtualhost.

**Comment by Homer-Sim** [comment]
you hint with editing local conf files sounds great! I will give it a try. 
Could I run into troubles with exposed port?

**Comment by Homer-Sim** [comment]
Sorry for coming up with this issue again.
I adjusted default config file like this but now I am not able to access it

`server {
  listen 80;
  server_name _;
  # enforce https
#  return 301 https://$server_name$request_uri;
#}

#server {
#  listen 443 ssl;
#  server_name _;

#  ssl_certificate /config/keys/cert.crt;
#  ssl_certificate_key /config/keys/cert.key;

`

This is create command:
`docker create \
    --name=nextcloud \
    --restart=always \
    -p 88:80 \
    -p 4438:443 \
    -e PUID=33 -e PGID=33 \
    -e TZ=Europe/Berlin \
    -v /media/usbhdd1/nextcloud/config/:/config \
    -v /media/usbhdd1/cloud/nextcloud/:/data \
    linuxserver/nextcloud`

with 192.168.100.39:88 I am not able to reach it ...

Any suggestion?

**Comment by aptalca** [comment]
If you try to connect on port 80 (88 from the lan/wan), nginx will redirect you to https, which is port 443. But your container is not available from the lan/wan at port 443, it is available at port 4438

**Comment by aptalca** [comment]
try this instead `return 301 https://$host:1234$request_uri;`

**Comment by Homer-Sim** [comment]
Sorry I just recognized change of default config want displayed correctly:
this is how I changed it, because I do not need SSL
 

> server {
  listen 80;
  server_name _;
  # enforce https
#  return 301 https://$server_name$request_uri;
#}

#server {
#  listen 443 ssl;
#  server_name _;

#  ssl_certificate /config/keys/cert.crt;
#  ssl_certificate_key /config/keys/cert.key;

**Comment by Homer-Sim** [comment]
I hate it! I make maybe a mistake pasting my code. hashtag is just making following line big ...

So what I wanted to show you is (**=hashtag )

`server {
  listen 80;
  server_name _;
  ** enforce https
**  return 301 https://$server_name$request_uri;
**}

**server {
**  listen 443 ssl;
**  server_name _;

**  ssl_certificate /config/keys/cert.crt;
**  ssl_certificate_key /config/keys/cert.key;

`

**Comment by aptalca** [comment]
You did not close the "server" tag with a `}`

**Comment by Homer-Sim** [comment]
the rest of default file is unchanged s the closing } originally used for server 443 part is still there 
can I add a txt file here?

btw many thanks for your help and patience
