### ISSUE TITLE
Add exiftool for Memories App

### ISSUE THREAD

**Issue by EVOTk** [linuxserver/docker-nextcloud#262]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Add exiftool for Memories App

https://apps.nextcloud.com/apps/memories

## Current Behavior
Memories App not run ( no exiftool in dockerfile )

## Alternatives Considered

Thx !

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install
