### ISSUE TITLE
Nextcloud 25 is not 25 version 😅

### ISSUE THREAD

**Issue by TheNexter** [linuxserver/docker-nextcloud#263]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. Push latest 25.0.0 image

## Environment
**OS:**
**CPU architecture:** arm64
**How docker service was installed:**
. docker repo
 The 25.0.0 is not nextcloud 25 version on the latest push 😅

## Command used to create docker container (run/create/compose/screenshot)

Normal docker compose (sorry I am on my phone)

## Docker logs

Docker logs are normal (I do this bug report on my phone sorry)

**Comment by Roxedus** [comment]
It is. Look at our update notes for this container <https://github.com/linuxserver/docker-nextcloud#application-setup>

**Comment by MilesTEG1** [comment]
Hello,
I update my image with your latest, with a docker-compose.yml file, but in the Web UI, there isn't a 25.0 version, still only the 24.0.6 :
![image](https://user-images.githubusercontent.com/29298312/196767671-f05c1607-be0a-4a20-b1d2-1565824a52a3.png)

25.0 is it still in beta ?

**Comment by aptalca** [comment]
Nextcloud decides when to make new versions available to you in its gui. They usually wait until the first point relase to make it available for updates, but it's entirely up to them.

**Comment by itsprakashp** [comment]
![Nextcloud-25 0 0](https://user-images.githubusercontent.com/51423001/197172440-7774811e-a66c-4c76-91df-4fbbcf64b88a.png)

Updating the nextcloud using CLI method provided by Linuxserver is working
```shell
docker exec -it nextcloud updater.phar
```

**Comment by itsprakashp** [comment]
> Hello, I update my image with your latest, with a docker-compose.yml file, but in the Web UI, there isn't a 25.0 version, still only the 24.0.6 : ![image](https://user-images.githubusercontent.com/29298312/196767671-f05c1607-be0a-4a20-b1d2-1565824a52a3.png)
> 
> 25.0 is it still in beta ?

25.0.0 is in Stable, but need to update using the below command provided by Linuxserver. On the Gui it still showing 24.0.6.
```shell
docker exec -it nextcloud updater.phar
```

**Comment by thespad** [comment]
> ![Nextcloud-25 0 0](https://user-images.githubusercontent.com/51423001/197172440-7774811e-a66c-4c76-91df-4fbbcf64b88a.png)
> 
> Updating the nextcloud using CLI method provided by Linuxserver is working
> 
> ```shell
> docker exec -it nextcloud updater.phar
> ```

That looks like it's working to me
