### ISSUE TITLE
ERROR: '...WebDAV interface seems to be broken'

### ISSUE THREAD

**Issue by zimmra** [linuxserver/docker-nextcloud#264]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Files should sync properly, and WebDAV shouldn't be reporting problems

## Current Behavior
Files don't sync properly (for instance, I cannot even export a Cospend project, the export fails), and at https://{nextcloud.instance}/settings/admin/overview the following error is reported:
```
Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken.
```

## Steps to Reproduce

1. Navigate to https://{nextcloud.instance}/settings/admin/overview

## Environment
**OS:** `Ubuntu 22.04.1 LTS`
**CPU architecture:** `x86_64`
**Image:** `Linuxserver.io version:- 25.0.0-ls206 Build-date:- 2022-10-19T14:03:42+00:00`
**How docker service was installed:** `Official Docker Repo`

## Command used to create docker container (compose):
```yaml
version: '2.1'
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=py3-pip|python3|aria2|youtube-dl
    volumes:
      - /media/docker/configs/nextcloud/config:/config
      - /media/docker/configs/nextcloud/data:/data
    ports:
      - 7443:443
    restart: unless-stopped
```

## Docker logs

Nothing out of the ordinary
```log
[mod-init] linuxserver/mods:universal-package-install at sha256:e21b4e41f9b56bd0d26b32b81b1ffc11e4877b131bde4153e343a6c0f1fbc9fa has been previously applied skipping
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
using keys found in /config/keys
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/40-config
cont-init: info: /etc/cont-init.d/40-config exited 0
cont-init: info: running /etc/cont-init.d/50-install
cont-init: info: /etc/cont-init.d/50-install exited 0
cont-init: info: running /etc/cont-init.d/60-memcache
cont-init: info: /etc/cont-init.d/60-memcache exited 0
cont-init: info: running /etc/cont-init.d/70-aliases
cont-init: info: /etc/cont-init.d/70-aliases exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
/config/nginx/site-confs/default.conf
/config/nginx/nginx.conf
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mod-universal-package-install-add-package: starting
**** Adding py3-pip to OS package install list ****
**** Adding python3 to OS package install list ****
**** Adding aria2 to OS package install list ****
**** Adding youtube-dl to OS package install list ****
s6-rc: info: service init-mod-universal-package-install-add-package successfully started
s6-rc: info: service init-mods-package-install: starting
**** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
OK: 367 MiB in 245 packages
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```

**Comment by nemchik** [comment]
> ```
> **** The following active confs have different version dates than the samples that are shipped. ****
> **** This may be due to user customization or an update to the samples. ****
> **** You should compare the following files to the samples in the same folder and update them. ****
> **** Use the link at the top of the file to view the changelog. ****
> /config/nginx/site-confs/default.conf
> /config/nginx/nginx.conf
> ```

Could you try updating these files? If you have not customized them you can simply delete them and restart the container. If you have customized them, you can review the accompanying `.sample` file of the same name in the same folder as the file in question and apply your customizations as needed.

**Comment by zimmra** [comment]
> > ```
> > **** The following active confs have different version dates than the samples that are shipped. ****
> > **** This may be due to user customization or an update to the samples. ****
> > **** You should compare the following files to the samples in the same folder and update them. ****
> > **** Use the link at the top of the file to view the changelog. ****
> > /config/nginx/site-confs/default.conf
> > /config/nginx/nginx.conf
> > ```
> 
> Could you try updating these files? If you have not customized them you can simply delete them and restart the container. If you have customized them, you can review the accompanying `.sample` file of the same name in the same folder as the file in question and apply your customizations as needed.

Was just typing a reply as you commented this, I noticed that too. My issue is technically resolved, but I am unsure why/how

- I ended up renaming/backing up my /config/nginx and /config/php directories and .htaccess file and recreating the container
  - The issue still persisted even after the new directories and .htaccess were made

- I then looked in the nginx error log for more clues and saw the following error:
    - `PHP Fatal error: Declaration of OCA\Deck\Sharing\DeckShareProvider::getSharesInFolder($userId, OCP\Files\Folder $node, $reshares) must be compatible with OCP\Share\IShareProvider::getSharesInFolder($userId, OCP\Files\Folder $node, $reshares, $shallow = true) in /var/www/html/apps/deck/lib/Sharing/DeckShareProvider.php on line 494`

- I then updating the Deck plugin to the beta channel, and tried again. 
  - The WebDAV error persisted

- I then disabled the plugin entirely, restarted container
  - WebDAV error persisted. 
  - Turned container off while looking for solution

- Turned container back on, and the issue was gone and everything works as intended. Re-enabled the Deck plugin and restarted the container once more to check for issues and all seems well

I wish I knew why the error happened to help others and to prevent in the future, but I haven't a clue.
