### ISSUE TITLE
php8-25.0.0-ls92 - "PHP module OpenSSL not installed."

### ISSUE THREAD

**Issue by radiochild577** [linuxserver/docker-nextcloud#265]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Nextcloud start correctly

## Current Behavior
When accessing the webpage I get this warning - "PHP module OpenSSL not installed."

## Steps to Reproduce
Create the container with php8-25.0.0-ls92. 
Works fine with php8-25.0.0-ls91, but ls92 causes this issue. 
I've tried with and without the ' --security-opt seccomp=unconfined' flag and the result is the same.

## Environment
**OS:** TOS 4.2.39 (TerraMaster OS - its a POS)
**CPU architecture:** x64
**How docker service was installed:**
From the TOS app store - v17.05.5 (latest available to me through TOS)

## Command used to create docker container (run/create/compose/screenshot)
docker run -d \
 -p 0.0.0.0:4443:4443 \
 --name=nextcloud \
 --net=host \
 --hostname=nextcloud \
 -v /appdata/docker/volumes/nextcloud/_data/data:/data \
 -v /appdata/docker/volumes/nextcloud/_data/config:/config \
 -e TZ=America/Chicago \
 -e PUID=1000 \
 -e PGID=1000 \
 -l com.centurylinklabs.watchtower.enable=false \
 --security-opt seccomp=unconfined \
 --restart=unless-stopped \
 linuxserver/nextcloud:php8

## Docker logs
s6-rc: info: service 99-ci-service-check: starting

[ls.io-init] done.

s6-rc: info: service 99-ci-service-check successfully started

[23-Oct-2022 12:58:36] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl.so' (tried: /usr/lib/php8/modules/openssl.so (Error relocating /usr/lib/php8/modules/openssl.so: zend_argument_error_variadic: symbol not found), /usr/lib/php8/modules/openssl.so.so (Error loading shared library /usr/lib/php8/modules/openssl.so.so: No such file or directory)) in Unknown on line 0

**Comment by jsbear** [comment]
I'm having the exact same issue after applying an update today.

**Comment by aptalca** [comment]
Try switching back to the `latest` tag as it is now rebased on php8

**Comment by jsbear** [comment]
> Try switching back to the `latest` tag as it is now rebased on php8

Will do

**Comment by radiochild577** [comment]
> Try switching back to the `latest` tag as it is now rebased on php8

That did it thank you!

**Comment by jsbear** [comment]
> > Try switching back to the `latest` tag as it is now rebased on php8
> 
> That did it thank you!

Ditto, thank you

**Comment by C8opmBM** [comment]
Thanks, was looking for the same answer!
