### ISSUE TITLE
[FEAT] Indroduce increased fastcgi_read_timeout in site-confs/default.conf.sample

### ISSUE THREAD

**Issue by HannesJo0139** [linuxserver/docker-nextcloud#279]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

In `site-confs/default.conf.sample` you already set some config options to enable uploading of big files. 
```
# set max upload size and increase upload timeout:
client_max_body_size 512M;
client_body_timeout 300s;
fastcgi_buffers 64 4K;
```

However, when uploading I encountered `Error when assembling chunks, status code 504`. A solution to my issue was adding
```
fastcgi_read_timeout 300s;
```

Perhaps you would want to add it to the sample file.

### Reason for change

..

**Comment by nemchik** [comment]
Everything we provide in `site-confs/default.conf.sample` is from https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

We wrap it in our standard config structure that all of our nginx based images use. I don't think there is a problem with individuals adding `fastcgi_read_timeout 300s;` to their own configs, but I'd like to avoid adding it to the image unless it's added to the official documentation for nextcloud.

**Comment by HannesJo0139** [comment]
Well it actually comes from the official NC docs. https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html#nginx

They say nothing specific about it but at least mention it and so I tried and was able to solve my issue with it ;)

**Comment by nemchik** [comment]
The documentation does mention what you can change, but not what value to use. Since this could be subjective and nextcloud does not provide a specific recommendation it still falls outside the realm of what I'd like to include in our image by default. If that changes in the future I would be happy to revisit.

**Comment by HannesJo0139** [comment]
Fair point
