### ISSUE TITLE
[BUG] Issue with latest version of nextcloud and PHP version

### ISSUE THREAD

**Issue by babyhuey** [linuxserver/docker-nextcloud#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following when I navigate to the Nextcloud webpage

```
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.

### Expected Behavior

Nextcloud page should load

### Steps To Reproduce

Using this image lscr.io/linuxserver/nextcloud:latest 

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - OWNCLOUD_UPLOAD_CONFLICT_FILES=1
    volumes:
      - /share/Public/configs/nextcloud:/config
      - /share/Public/nextcloud:/data
    ports:
      - 8443:443
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started

[migrations] 01-nginx-site-confs-default: skipped

[migrations] done

usermod: no changes

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    911

User gid:    911

-------------------------------------

using keys found in /config/keys

**** The following active confs have different version dates than the samples that are shipped. ****

**** This may be due to user customization or an update to the samples. ****

**** You should compare the following files to the samples in the same folder and update them. ****

**** Use the link at the top of the file to view the changelog. ****

┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐

│  old date  │  new date  │ path                                                                   │

├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤

│ 2018-08-16 │ 2022-08-16 │ /config/nginx/nginx.conf                                               │

│            │ 2022-08-20 │ /config/nginx/site-confs/default.conf                                  │

└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘

[custom-init] No custom files found, skipping...

[ls.io-init] done.
```

**Comment by aptalca** [comment]
It means you updated the image and the container, but you haven't been updating the app. Switch to an older tag, and update Nextcloud.
https://github.com/linuxserver/docker-nextcloud#application-setup

**Comment by babyhuey** [comment]
> It means you updated the image and the container, but you haven't been updating the app. Switch to an older tag, and update Nextcloud. https://github.com/linuxserver/docker-nextcloud#application-setup

Doh! Thanks for the quick support. Didn't even realize I needed to log into the web app.

I was on version 21!

**Comment by aptalca** [comment]
Nextcloud is one of very few images we provide that need updating in the app itself as well as container updates

**Comment by PilaScat** [comment]
updated with updater.phar and download latest but same problem

**Comment by thespad** [comment]
The updater will only update one major version at a time, if your install is behind you may need multiple rounds of updates to get up to date.

**Comment by PilaScat** [comment]
I've never updated this way, so yes, I was at version 20

**Comment by zizilka321** [comment]
Hi, i went trough this update method mentioned in the Application backup:


"Use the CLI version by running docker exec -it nextcloud updater.phar (Both of these are described [here](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html))
Note: Both occ and updater.phar can be run without prepending with sudo -u abc php or sudo -u www-data php

If you are not customizing our default nginx configuration you will need to remove the file:

/config/nginx/site-confs/default.conf
Then restart the container to replace it with the latest one."

Since i'm not using any custom config, I removed the default config, and restarted the docker. It created the default config, but since then The log shows this nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:9 .

I came across a forum that a user said they added the lines 
ssl_certificate /config/keys/cert.crt;
ssl_certificate_key /config/keys/cert.key;
But if i add this two records I'm back to the old error: 
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.

Any solution?

**Comment by thespad** [comment]
> Hi, i went trough this update method mentioned in the Application backup:
> 
> "Use the CLI version by running docker exec -it nextcloud updater.phar (Both of these are described [here](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html)) Note: Both occ and updater.phar can be run without prepending with sudo -u abc php or sudo -u www-data php
> 
> If you are not customizing our default nginx configuration you will need to remove the file:
> 
> /config/nginx/site-confs/default.conf Then restart the container to replace it with the latest one."
> 
> Since i'm not using any custom config, I removed the default config, and restarted the docker. It created the default config, but since then The log shows this nginx: [emerg] no "ssl_certificate" is defined for the "listen ... ssl" directive in /config/nginx/site-confs/default.conf:9 .
> 
> I came across a forum that a user said they added the lines ssl_certificate /config/keys/cert.crt; ssl_certificate_key /config/keys/cert.key; But if i add this two records I'm back to the old error: This version of Nextcloud is not compatible with > PHP 8.0. You are currently running 8.1.16.
> 
> Any solution?

https://github.com/linuxserver/docker-nextcloud/issues/285#issuecomment-1442232313

**Comment by nemchik** [comment]
If you are receiving errors about PHP or issues with nginx or certificates:

- Switch your image to `lscr.io/linuxserver/nextcloud:24.0.6-ls204` and start the container
- Execute `docker exec -it nextcloud updater.phar` repeatedly until you reach version 25
- Switch your image to `lscr.io/linuxserver/nextcloud` (latest, no tag) and start the container
- Execute `docker exec -it nextcloud mv /config/nginx/site-confs/default.conf /config/nginx/site-confs/default.conf.bak`
- Execute `docker exec -it nextcloud mv /config/nginx/nginx.conf /config/nginx/nginx.conf.bak`
- Execute `docker logs nextcloud` and check for any other outdated configs, rename them with a `.bak` extension (like above)
- Restart the container
- Nextcloud should now be in a working state

Optional:

- If you had customized any of the nginx configs that were renamed above, compare the `.bak` file to the new live file and apply any customizations you require
- Remove the `.bak` files

**Comment by nemchik** [comment]
Replacing this issue with https://github.com/linuxserver/docker-nextcloud/issues/288
