### ISSUE TITLE
[BUG] Nextcloud not loading at all after update

### ISSUE THREAD

**Issue by MuQ-dev** [linuxserver/docker-nextcloud#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have updated the docker container yesterday, only to find out, that Nextcloud was not giving any sign of life. No error message, no nothing. Just: Can't reach this page. I don't think it's about the PHP Version as I am running NC 25.0.4. I also updated MariaDB that day, maybe is has something to do with that? Any help would be much appreciated. I have tried the PHP fix, also moving the files to .bak.

### Steps To Reproduce

1. Docker Image of Nextcloud + MariaDB
2. Update to latest docker image
3. 

### Environment

```markdown
- OS: Unraid
- How docker service was installed: Unraid Integrated Docker
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid integrated Docker
```

### Container logs

```bash
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.conf.bak
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
What does your mariadb container logs say?

**Comment by MuQ-dev** [comment]
Oh, my bad, didn't think of that. It wants an upgrade.

#################################################################
#                                                               #
#           An upgrade is required on your databases.           #
#                                                               #
#         Stop any services that are accessing databases        #
#          in this container, and then run the command          #
#                                                               #
#             mariadb-upgrade -u root -p<PASSWORD>              #
#                                                               #
#################################################################

**Comment by MuQ-dev** [comment]
Well that did not fix it. Restarted both containers.

**Comment by nemchik** [comment]
Can you post screenshots of the edit screen for the container in the unraid GUI? (sanitize any sensitive info as needed).

**Comment by MuQ-dev** [comment]
![image](https://user-images.githubusercontent.com/70913488/223244145-c288af7d-b4d8-4e9d-a608-d384b2df726f.png)

**Comment by MuQ-dev** [comment]
I just downgraded the image again, and it did throw me an error about my config needing >=php8, which is to expected with that older image. Pulled the latest again, no change, still Site not reachable.

**Comment by MuQ-dev** [comment]
![image](https://user-images.githubusercontent.com/70913488/223246015-3be16eed-1ef9-4d23-ac23-30ece2ee818b.png)
It gives me a http2 compression error

**Comment by GreyYiFeiLiu** [comment]
> I just downgraded the image again, and it did throw me an error about my config needing >=php8, which is to expected with that older image. Pulled the latest again, no change, still Site not reachable.

same error page 

> This version of Nextcloud is not compatible with > PHP 8.0.
> You are currently running 8.1.16.

donwgrade to 24.0.5, everthing goes right.

**Comment by MuQ-dev** [comment]
Well, I found something else. As it turns out, WebDAV works, it's just the Website, that is broken. Can anyone send me a picture of the nginx and site confs, so I can see, how they should look like?

**Comment by nemchik** [comment]
If downgrading the image fixes the problem, try following the instructions in https://github.com/linuxserver/docker-nextcloud/issues/288

**Comment by nemchik** [comment]
> Well, I found something else. As it turns out, WebDAV works, it's just the Website, that is broken. Can anyone send me a picture of the nginx and site confs, so I can see, how they should look like?

There are `.sample` files in your `/config/nginx` folder that contain the default configs for every nginx file used with the exception of the worker processes and resolver which are generated dynamically the first time you run the container.

**Comment by MuQ-dev** [comment]
Hey there, thanks for all the suggestions. Weirdly enough,  it fixed itself just now and I have no idea why. While being a mildly frustrating and not helpful solution, it still is a solution. You can mark this thread as solved.
