### ISSUE TITLE
Header Error + Php Module After Update to v26.0

### ISSUE THREAD

**Issue by masterwishx** [linuxserver/docker-nextcloud#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Unraid Docker lasted version.
After Updated to Nextcloud v 26.0 ,got 2 errors :
1. header missing HTTP «X-Robots-Tag» not setup to  «noindex, nofollow». 
2. Php module not installed sysvsem

![image](https://user-images.githubusercontent.com/28630321/226697709-b8e9f1b1-0bc5-414a-8028-3b48b8fb6e66.png)

### Expected Behavior

was no errors on previos version

### Steps To Reproduce

..

### Environment

```markdown
Unraid (Linux x64)
```

### CPU architecture

x86-64

### Docker creation

```bash
..
```

### Container logs

```bash
..
```

**Comment by Intenos** [comment]
I have the same. They stay also after updating the docker image to the latest version.

**Comment by sttaelma** [comment]
same

**Comment by stanthewizzard** [comment]
i don't have the 26 update at all after updating the image

**Comment by masterwishx** [comment]
Updated to v26, then updated the image also,
We have now «X-Robots-Tag» none that equal to no index, nofollow I think.
Any fix for missing php module?

**Comment by Proximus888** [comment]
For X-Robot-Tags fix:

Change appdata > nextcloud > nginx > site-confs > default.conf  

From:
```
add_header X-Robots-Tag "none" always;
```
to:
```
add_header X-Robots-Tag "noindex, nofollow" always;
```
Then restart container


For missing php module I still have the warning:
```
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.

    sysvsem
```

**Comment by thespad** [comment]
I have no idea why they can't make their bloody minds up about headers, "X-Robots-Tag: none" is the same effective setting as "X-Robots-Tag: noindex, nofollow".

We will get the additional PHP packages added to the image.

**Comment by h4llm3n** [comment]
> i don't have the 26 update at all after updating the image

Because you have to update Nextcloud itself and not just the image.

**Comment by stanthewizzard** [comment]
> > i don't have the 26 update at all after updating the image
> 
> Because you have to update Nextcloud itself and not just the image.

Yes but no update is showing inside nextcloud. Occ command ?

**Comment by Proximus888** [comment]
> > > i don't have the 26 update at all after updating the image
> > 
> > Because you have to update Nextcloud itself and not just the image.
> 
> Yes but no update is showing inside nextcloud. Occ command ?

sudo docker exec -it nextcloud_container_name updater.phar

**Comment by stanthewizzard** [comment]
Thanks

**Comment by oscarat50** [comment]
I've updated Nextcloud to v26 and followed the X-Robots-Tags fix for the default.conf file. 
I've also updated MariaDB from linuxserver repository. 
But now when I access Nextcloud's WebUI I get an "Internal Server Error" and can't access the webui at all

Checked the logs in the nginx folder and I get this:
```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /config/www/nextcloud/lib/private/DB/Connection.php:142
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1531): OC\DB\Connection->connect()
#1 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /config/www/nextcloud/lib/private/DB/Connection.php(264): Doctrine\DBAL\Connection->executeQuery()
#3 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(280): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /config/www/nextcloud/lib/private/AppConfig.php(418): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#7" while reading response header from upstream, client: 190.152.81.30, server: _, request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "myhost.com"
2023/05/16 19:38:57 [error] 310#310: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 157.100.136.115, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "myhost.com"
```

I'm stuck, hope that someone can help me find a solution. Thanks

**Comment by nemchik** [comment]
Can you post your `/config/www/nextcloud/config/config.php` ?

should look something like this (may not be exact)
```php
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'redacted',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' => 
  array (
    0 => 'redacted',
  ),
  'dbtype' => 'mysql',
  'version' => '26.0.1.1',
  'overwrite.cli.url' => 'https://redacted',
  'dbname' => 'nextcloud',
  'dbhost' => 'mariadb',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'redacted',
  'installed' => true,
  'maintenance' => false,
  'trusted_proxies' => 
  array (
    0 => 'swag',
  ),
  'overwritehost' => 'redacted',
  'overwriteprotocol' => 'https',
  'loglevel' => 2,
  'default_phone_region' => 'US',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_from_address' => 'redacted',
  'mail_domain' => 'redacted',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'tls',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'redacted',
  'mail_smtppassword' => 'redacted',
);
```
