### ISSUE TITLE
NextCloud pm.max_children, consider raising it

### ISSUE THREAD

**Issue by ethanopp** [linuxserver/docker-nextcloud#30]
When trying to load several documents to NextCloud at once through the web gui (clicking and dragging), the following error appears in the php error log:

WARNING: [pool www] server reached pm.max_children setting (5), consider raising it

This parameter resides in the following dir, however I cannot seem to mount it, resulting in the need to manually update on every restart:
/etc/php7/php-fpm.d

Is there anyway this can be more automatically set, perhaps by an environment variable?

Thanks!

**Comment by sparklyballs** [comment]
there's a pending update to the nginx baseimage that will allow a custom php ini

**Comment by Nottt** [comment]
Still having this issue with latest nextcloud docker. I think the php.ini is being ignored.

I'm editing my host `php.ini` which inside the container is `/config/php/php-local.ini`

I added this:

```
memory_limit = 512M
pm = ondemand
pm.max_children = 300
pm.process_idle_timeout = 30s
pm.max_requests = 500
```

But it's just ignored. I keep seeing this error in my logs :(

**Comment by aptalca** [comment]
That should go in /config/php/www2.conf not php.ini

**Comment by Nottt** [comment]
Thanks!

BTW, `memory_limit = 512` should not be placed in `www2.conf` or it won't start.

**Comment by aptalca** [comment]
You should look into what should go where.

There are things that belong in the php.ini and for those, use php-local.ini as the first line of the file instructs.

Then there are things that belong in the php-fpm.conf, and for those, use www2.conf as the first line of the file instructs.

Don't blindly add directives to either file.

**Comment by TobjasR** [comment]
> That should go in /config/php/www2.conf not php.ini

I set it to 100000
still happens within seconds of container start up.
