### ISSUE TITLE
[BUG] PHP ISSUE

### ISSUE THREAD

**Issue by kraveboi** [linuxserver/docker-nextcloud#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This version of Nextcloud is not compatible with > PHP 7.4.
You are currently running 8.1.18.

And it will now load. Running in unraid docker.

### Expected Behavior

N/A

### Steps To Reproduce

Run in docker normally in unraid.

### Environment

```markdown
- OS: unraid
- How docker service was installed: unraid App Store
```

### CPU architecture

x86-64

### Docker creation

```bash
Don’t have, it’s installed via App Store docker in unraid
```

### Container logs

```bash
N/A doesn’t have any data
```

**Comment by Roxedus** [comment]
See https://github.com/linuxserver/docker-nextcloud/issues/288
