### ISSUE TITLE
[BUG] rootcerts.crt in /data directory casues disks to spins up (Unraid)

### ISSUE THREAD

**Issue by Nomelas** [linuxserver/docker-nextcloud#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Unraid, nextcloud has its own share. In Docker, the /data directory is mapped to this share to utilize the array for storage of user-data.

Aside from logs also being written here (which can be overwritten in the config file), there's another problematic file located in /data/files_external/rootcerts.crt

This file is opened periodically and should be in the /config directory, not the /data directory.

### Expected Behavior

/data/files_external/rootcerts.crt moved to /config/files_external/rootcerts.crt to avoid disk spin up in Unraid.

### Steps To Reproduce

1. Create docker container in Unraid
2. Nextcloud share using the array
3. Disks spin up every time nextcloud reads /data/files_external/rootcerts.crt

### Environment

```markdown
- OS: Unraid 6.11.5
- How docker service was installed: Community Applications Template
```

### CPU architecture

x86-64

### Docker creation

```bash
Community Applications Template
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment]
That's a Nextcloud thing. It should be reported to them.

**Comment by nemchik** [comment]
I don't see a way to change this in the documentation for nextcloud's config. You could however try the following:

- stop the nextcloud container
- copy `/mnt/user/somewhere_on_your_array/nextcloud_data/files_external/rootcerts.crt` to `/mnt/user/appdata/nextcloud/data/files_external/rootcerts.crt` (you would need to create the folders first)
- Add a volume to your nextcloud container to map `/data/files_external/rootcerts.crt` to `/mnt/user/appdata/nextcloud/data/files_external/rootcerts.crt`
- start the container and see if it works as desired

While this may work, it is not the best way for it to work. The best way would be for nextcloud to have an option to configure where those files live.

**Comment by chrisborell** [comment]
> looks like it is referenced here:
> 
> ```
> /config/www/nextcloud/lib/private/Security/CertificateManager.php:            $certPath = $path . 'rootcerts.crt';
> /config/www/nextcloud/lib/private/Security/CertificateManager.php:            return $this->getPathToCertificates() . 'rootcerts.crt';
> ```

How did you end up resolving this? Experiencing the same issue!

**Comment by mgabor3141** [comment]
@chrisborell I posted my solution here: https://forums.unraid.net/topic/139010-drive-keeps-spinning-up-how-to-diagnose-the-cause/?do=findComment&comment=1445637

I used the [Mover Tuning](https://forums.unraid.net/topic/70783-plugin-mover-tuning/) unraid plugin to keep this file permanently on the cache pool without having to move it to a different path.
