### ISSUE TITLE
[BUG] This version of Nextcloud is not compatible with PHP>=8.2.

### ISSUE THREAD

**Issue by ps-kl** [linuxserver/docker-nextcloud#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After Update commit c07466d yesterday Nextcloud only shows:
This version of Nextcloud is not compatible with PHP>=8.2.
You are currently running 8.2.6.

I did the steps from pinned Issue but it changed nothing. Going back to [26.0.2-ls246](https://github.com/linuxserver/docker-nextcloud/releases/tag/26.0.2-ls246) works for me. But with Change [26.0.2-ls247](https://github.com/linuxserver/docker-nextcloud/releases/tag/26.0.2-ls247) and php 8.2 it won't work anymore for me even if I update the install as explained. 

### Steps To Reproduce

Use latest Image

### Environment

```markdown
- OS:Unraid 
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Unraid Community Apps
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.bak
/config/nginx/site-confs/default.conf.bak
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment]
What version is your nextcloud? You need to keep updating as long as it lets you. It does incremental updates.

**Comment by paskalll** [comment]
25.0.7 and the support for php 8.2 comes with 26 so I have to change to 26.0.2. 

docker exec -it nextcloud updater.phar
Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.7.

No update available.

Nothing to do.


seems from 25 to 26 is not a auto update at this point. I did go back to [26.0.2-ls246](https://github.com/linuxserver/docker-nextcloud/releases/tag/26.0.2-ls246) update via settings and go back to latest image works. But I guess 25 is still long term stable release from nextcloud and it won't work with php 8.2

**Comment by Biepa** [comment]
Going back to "[26.0.2-ls246](https://github.com/linuxserver/docker-nextcloud/releases/tag/26.0.2-ls246)" like @paskalll mentioned atleast let me use nextcloud again.

**Comment by An4cl3t0** [comment]
Same for me, " This version of Nextcloud is not compatible with PHP>=8.2."

**Comment by j0nnymoe** [comment]
@An4cl3t0 then read the comments above you. It's already well documented what to do.

**Comment by kvn1351** [comment]
If only they had a "stable" tag :/

**Comment by j0nnymoe** [comment]
Or just don't use latest and pin to an actual version tag. If you just run with using `:latest` - you're always running the risk. https://www.linuxserver.io/blog/2018-04-22-the-dangers-of-pulling-latest

The issue so many people are experiencing this issue is due to 
1) running automatic updates (watchtower etc)
2) not updating nextcloud within the container.

Our nextcloud has always been like this.

**Comment by peterge1998** [comment]
> Just add :26.0.2-ls246 Nextcloud starts Update via WEB GUI to 26.0x Remove version tag from image Done

Maintenance mode is active after starting with this tag...

**Comment by jarbelix** [comment]
> Same for me, " This version of Nextcloud is not compatible with PHP>=8.2."

Sema for me: https://nextcloud.tiozaodolinux.com/

This environment is a test environment. I'll leave it until the fix comes out.

**Comment by j0nnymoe** [comment]
There is no "fix" - you need to roll back to a previous image tag, run `updater.phar` to get it up to the latest version that tag supports then switch back.

**Comment by j0nnymoe** [comment]
And to prove a point, my personal instance of nextcloud is on `Linuxserver.io version:- 24.0.12-ls238 Build-date:- 2023-04-20T11:12:06+02:00` and it's picking up v26 update:
![image](https://github.com/linuxserver/docker-nextcloud/assets/10374553/54e405cb-24a8-4e2f-9fb3-11b686613e4e)

**Comment by j0nnymoe** [comment]
To confirm these instructions are still relevant: https://github.com/linuxserver/docker-nextcloud/issues/288
![image](https://github.com/linuxserver/docker-nextcloud/assets/10374553/1a3a603f-5b92-468e-916a-75a447940fee)

**Comment by say-no-to-deer-pressure** [comment]
I also ran into this issue. Setting the container version to :26.0.2-ls246 and running updater.phar afterwards solved it.

**Comment by kman1898** [comment]
I’m running via unraid and am having trouble following how I should go about this fix

**Comment by kman1898** [comment]
> updater

But how do I switch back? I cannot get into the gui and have no place to change the tag. Currently on 25.0.7

**Comment by aptalca** [comment]
Unraid forums and their docker faq have plenty of info on managing docker images and tags and various other aspects of their docker gui management system.

**Comment by kman1898** [comment]
> Unraid forums and their docker faq have plenty of info on managing docker images and tags and various other aspects of their docker gui management system.

Solved. Thanks

**Comment by Nicon4454** [comment]
I am sorry to ask this but how do i fix this? i have looked at the instructions
1. Change Repository to lscr.io/linuxserver/nextcloud:26.0.2-ls246
2. Start Nextcloud
3. Update via WEB GUI to 26.0x
4. Remove version Tag :26.0.2-ls246 from step 1
Done

how do i change the repository? and from now on i should update using the nextcloud gui instead of using he unraid docker management?
i am sorry for the hand holding that is needed.

**Comment by say-no-to-deer-pressure** [comment]
> I am sorry to ask this but how do i fix this? i have looked at the instructions
> 
> 1. Change Repository to lscr.io/linuxserver/nextcloud:26.0.2-ls246
> 2. Start Nextcloud
> 3. Update via WEB GUI to 26.0x
> 4. Remove version Tag :26.0.2-ls246 from step 1
>    Done
> 
> how do i change the repository? and from now on i should update using the nextcloud gui instead of using he unraid docker management? i am sorry for the hand holding that is needed.

How are you running Docker? Installed on Ubuntu,  Unraid etc

**Comment by Nicon4454** [comment]
I was able to figure it out to get back to the nextcloud (NC) ui 

But I am running it in docker on UNRaid.  I am trying to install the updates from the nc ui 

Don't only practice your art, but force your way into its secrets; art deserves that, for it and knowledge can raise man to the Divine. 

— Ludwig van Beethoven

**Comment by FudiHub** [comment]
the instructions above fixed it. Thanks

**Comment by mindtrust80** [comment]
Hello,

i had the same issue und changed Repo to lscr.io/linuxserver/nextcloud:26.0.2-ls246
Now i got this problem:
![grafik](https://github.com/linuxserver/docker-nextcloud/assets/129095167/3806dc1c-9be9-46a3-a21d-7d6d28cb2054)

I tried several times without any change.

Would be nice, if someone could help me, thanks.

**Comment by nemchik** [comment]
> Hello,
> 
> i had the same issue und changed Repo to lscr.io/linuxserver/nextcloud:26.0.2-ls246 Now i got this problem: ![grafik](https://user-images.githubusercontent.com/129095167/243453612-3806dc1c-9be9-46a3-a21d-7d6d28cb2054.png)
> 
> I tried several times without any change.
> 
> Would be nice, if someone could help me, thanks.

DISCLAIMER FOR FUTURE READERS:
DO NOT ATTEMPT TO DO THIS BASED ON HAVING SIMILAR SYMPTOMS! OPEN A NEW ISSUE AND WE WILL INSTRUCT IF THIS METHOD IS NECESSARY!

1. stop your nextcloud container
2. backup your `/config` volume (and if possible, your `/data` volume) and make a backup of your nextcloud database (could be `sqlite`, `mariadb`, or `pgsql`)
3. re-read step 2! I cannot stress enough that skipping step 2 can leave you in a completely unrecoverable state!
4. delete `/config/www/nextcloud/index.php`
5. set your container image tag to `latest`, ex: `lscr.io/linuxserver/nextcloud:latest`
6. start the container
7. watch the container logs
8. if there are any issues in the log, come here and post the log output!
9. if there are no issues in the log, bash (terminal) into the container and run `updater.phar`, otherwise post the log with issues here 
10. if there are no issues still, run `occ update`, otherwise post the log with issues here

With any luck you won't have any issues, and this will reinstall the latest available version of nextcloud.

if

**Comment by olaxe** [comment]
This procedure has worked for me. Careful to read the word repeatedly as there is multiple updates

Execute docker exec -it nextcloud updater.phar repeatedly until there are no more updates

**Comment by sausje** [comment]
Using the updater.phar resulted in error after extracting about the version.php missing?!?! Literally just ran the command and that's it

> [✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[ ] Extracting ...PHP Warning:  require(/config/www/nextcloud/updater/../version.php): Failed to open stream: No such file or directory in phar:///config/www/nextcloud/updater/updater.phar/lib/Updater.php on line 676
PHP Fatal error:  Uncaught Error: Failed opening required '/config/www/nextcloud/updater/../version.php' (include_path='.:/usr/share/php82') in phar:///config/www/nextcloud/updater/updater.phar/lib/Updater.php:676
Stack trace:
#0 phar:///config/www/nextcloud/updater/updater.phar/lib/Updater.php(713): NC\Updater\Updater->getVersionByVersionFile()
#1 phar:///config/www/nextcloud/updater/updater.phar/lib/UpdateCommand.php(372): NC\Updater\Updater->extractDownload()
#2 phar:///config/www/nextcloud/updater/updater.phar/lib/UpdateCommand.php(233): NC\Updater\UpdateCommand->executeStep()
#3 phar:///config/www/nextcloud/updater/updater.phar/vendor/symfony/console/Command/Command.php(256): NC\Updater\UpdateCommand->execute()
#4 phar:///config/www/nextcloud/updater/updater.phar/vendor/symfony/console/Application.php(820): Symfony\Component\Console\Command\Command->run()
#5 phar:///config/www/nextcloud/updater/updater.phar/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///config/www/nextcloud/updater/updater.phar/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application->doRun()
#7 phar:///config/www/nextcloud/updater/updater.phar/updater.php(10): Symfony\Component\Console\Application->run()
#8 /config/www/nextcloud/updater/updater.phar(14): require('...')
#9 {main}
  thrown in phar:///config/www/nextcloud/updater/updater.phar/lib/Updater.php on line 676

**Comment by elforesto** [comment]
> Or just don't use latest and pin to an actual version tag. If you just run with using `:latest` - you're always running the risk. https://www.linuxserver.io/blog/2018-04-22-the-dangers-of-pulling-latest
> 
> The reason so many people are experiencing this issue is due to
> 
> 1. running automatic updates (watchtower etc)
> 2. not updating nextcloud within the container.
> 
> Our nextcloud has always been like this and it's documented in our readme.

I love how every time Linuxserver introduces breaking changes because they are clueless admins they turn around and blame the users. This is why I've been moving away from their images and recommend that everyone I know do so.

**Comment by Beryllium30** [comment]
Hey 

I am a bit confused and not sure how to progress :D 

I basically changed the tag in Unraid to: 
`lscr.io/linuxserver/nextcloud:26.0.2-ls246`

Nextcloud works again then and I wanted to update to the 26 version. 
If I go to the docker terminal and use: updater.phar i get the following message:

`Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.4.

Update to Nextcloud 25.0.7 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.7.zip
Open changelog ↗`


Why can't I update to the 26 version?
Would appreciate any help!

BR
Berry

**Comment by j0nnymoe** [comment]
You have to run the updater multiple times, You can't just jump to the latest version.

**Comment by Beryllium30** [comment]
Is that supported with the docker container? 

but why is there a version missmatch?

**Comment by j0nnymoe** [comment]
Yes it's supported within our container, it's the update process we recommend in our readme.

The tags are for what version is included for a new install. For exisiting installs, you need to make sure you're on a newer tag for the correct dependencies.

**Comment by nemchik** [comment]
The container doesn't update nextcloud automatically when you updated the container image. Updates to nextcloud are done manually.

I am in the process of building nextcloud into the container. Builds that should work are ready, but need more testing than just me. I haven't asked for user testing at this point because testing requires a well planned backup and restore procedure, which is something we advise everyone have in general. If testing is successful, this build could eventually replace our current builds, and it would replace the current manual upgrade process. Tldr: the test builds could break your install in an unrecoverable way.

**Comment by Wigsinator** [comment]
If I attempt to run the updater when on tag 26.0.2 and 26.0.2-247, I receive this: The updater loops infinitely like so, and upgrading to version 26 is impossible. And occ upgrade can't be run after the update.

`
Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.7.

Update to Nextcloud 25.0.7 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.7.zip
Open changelog ↗
`

However, if I try to run the upgrader on tag 26.0.2-ls246 like people are recommending, I get told:

`Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused in /config/www/nextcloud/lib/private/DB/Connection.php:139`

I'm using MariaDB as my database. What should I attempt from here?

**Comment by doreks** [comment]
hi!

same issue here:
This version of Nextcloud is not compatible with PHP>=8.2.
You are currently running 8.2.7.

and here the log after try to upgrade manually:
`root@d2b6296cfc12:/#updater.phar 
Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.7.

Update to Nextcloud 25.0.7 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.7.zip
Open changelog ↗

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] y
This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.7.`


any way to fix it and can work normally?

thanks for the support!

**Comment by nemchik** [comment]
https://github.com/linuxserver/docker-nextcloud/issues/288 has all the instructions needed to fix this issue.

**Comment by GeneralUser-NonDev** [comment]
FINALLY got the update to 26.x.x to work, being new to all this stuff i had to first figure out WHERE to try running these commands. I had to open the containers console (terminal) and run the command "updater.phar" there, no clue where to use "docker exec -it nextcloud updater.phar" as it didn't work in the containers terminal/console window (maybe Unraid terminal window?!). after it finally taking 26 i removed the version tag on the repo line and it works correctly, currently trying to update to 27.x.x (and beyond) the same way, hope it works (knock on wood).

too bad there isn't a way to have the internals of the container to auto-update, or is there and I'm missing something?

**Comment by nemchik** [comment]
> too bad there isn't a way to have the internals of the container to auto-update, or is there and I'm missing something?

It's being worked on https://github.com/linuxserver/docker-nextcloud/pull/317

**Comment by doreks** [comment]
> #288 has all the instructions needed to fix this issue.

i followed the instructions but seems that didnt work it :-(

here the log:

`root@Tower:~# docker exec -it nextcloud updater.phar
Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.7.

Update to Nextcloud 25.0.8 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.8.zip
Open changelog â†—

Steps that will be executed:
[âœ”] Check for expected files
[âœ”] Check for write permissions
[âœ”] Create backup
[âœ”] Downloading
[âœ”] Verify integrity
[âœ”] Extracting
[âœ”] Enable maintenance mode
[âœ”] Replace entry points
[âœ”] Delete old files
[âœ”] Move new files in place
[âœ”] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[âœ”] Check for expected files
[âœ”] Check for write permissions
[âœ”] Create backup
[âœ”] Downloading
[âœ”] Verify integrity
[âœ”] Extracting
[âœ”] Enable maintenance mode
[âœ”] Replace entry points
[âœ”] Delete old files
[âœ”] Move new files in place
[âœ”] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] y
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused in /config/www/nextcloud/lib/private/DB/Connection.php:139
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /config/www/nextcloud/lib/private/DB/Connection.php(261): Doctrine\DBAL\Connection->executeQuery()
#3 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /config/www/nextcloud/lib/private/AppConfig.php(419): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#7 /config/www/nextcloud/lib/private/AppConfig.php(375): OC\AppConfig->getApps()
#8 /config/www/nextcloud/lib/private/legacy/OC_App.php(967): OC\AppConfig->getValues()
#9 /config/www/nextcloud/lib/private/Server.php(725): OC_App::getAppVersions()
#10 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\Server->OC\{closure}()
#11 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#13 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#15 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(185): OC\AppFramework\Utility\SimpleContainer->get()
#16 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#19 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#21 /config/www/nextcloud/lib/private/Server.php(1121): OC\AppFramework\Utility\SimpleContainer->get()
#22 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\Server->OC\{closure}()
#23 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#25 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#27 /config/www/nextcloud/lib/private/Server.php(2072): OC\AppFramework\Utility\SimpleContainer->get()
#28 /config/www/nextcloud/lib/private/Files/View.php(117): OC\Server->getLockingProvider()
#29 /config/www/nextcloud/lib/private/Server.php(462): OC\Files\View->__construct()
#30 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\Server->OC\{closure}()
#31 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#33 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#35 /config/www/nextcloud/lib/private/Server.php(1474): OC\AppFramework\Utility\SimpleContainer->get()
#36 /config/www/nextcloud/lib/base.php(617): OC\Server->boot()
#37 /config/www/nextcloud/lib/base.php(1145): OC::init()
#38 /config/www/nextcloud/console.php(48): require_once('/config/www/nex...')
#39 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#40 {main}
Keep maintenance mode active? [y/N] 
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused in /config/www/nextcloud/lib/private/DB/Connection.php:139
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection->connect()
#1 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /config/www/nextcloud/lib/private/DB/Connection.php(261): Doctrine\DBAL\Connection->executeQuery()
#3 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery()
#4 /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /config/www/nextcloud/lib/private/AppConfig.php(419): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#7 /config/www/nextcloud/lib/private/AppConfig.php(375): OC\AppConfig->getApps()
#8 /config/www/nextcloud/lib/private/legacy/OC_App.php(967): OC\AppConfig->getValues()
#9 /config/www/nextcloud/lib/private/Server.php(725): OC_App::getAppVersions()
#10 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\Server->OC\{closure}()
#11 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#13 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#14 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#15 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(185): OC\AppFramework\Utility\SimpleContainer->get()
#16 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#17 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#19 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#20 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#21 /config/www/nextcloud/lib/private/Server.php(1121): OC\AppFramework\Utility\SimpleContainer->get()
#22 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\Server->OC\{closure}()
#23 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#24 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#25 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#26 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#27 /config/www/nextcloud/lib/private/Server.php(2072): OC\AppFramework\Utility\SimpleContainer->get()
#28 /config/www/nextcloud/lib/private/Files/View.php(117): OC\Server->getLockingProvider()
#29 /config/www/nextcloud/lib/private/Server.php(462): OC\Files\View->__construct()
#30 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(163): OC\Server->OC\{closure}()
#31 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(130): Pimple\Container->offsetGet()
#33 /config/www/nextcloud/lib/private/ServerContainer.php(136): OC\AppFramework\Utility\SimpleContainer->query()
#34 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#35 /config/www/nextcloud/lib/private/Server.php(1474): OC\AppFramework\Utility\SimpleContainer->get()
#36 /config/www/nextcloud/lib/base.php(617): OC\Server->boot()
#37 /config/www/nextcloud/lib/base.php(1145): OC::init()
#38 /config/www/nextcloud/console.php(48): require_once('/config/www/nex...')
#39 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#40 {main}
Maintenance mode is disabled`

**Comment by jkrauss82** [comment]
Don't know why this issue is closed, it should not be.

Just ran into the issue, too. We are on stable channel, **nextcloud version 25.0.10**, non-docker installation. We do not want to switch to a beta channel for production software.

[Documentation says](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html) recommended php is 8.2. We use apache2 and php-fpm.

Request reopening and fixing this problem or update the documentation to be informative about actually supported environment.

**Comment by j0nnymoe** [comment]
You're on a non-docker installation. This support thread isn't relevant for you.

**Comment by jkrauss82** [comment]
Understood, nevermind.
