### ISSUE TITLE
cant upload due to not valid time

### ISSUE THREAD

**Issue by Curtis777** [linuxserver/docker-nextcloud#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my Desktop Client always tells me:
Cannot sync due to invalid modification time

im using 3.8.2 client on windows
[Nextcloud](https://nextcloud.com/) 24.0.6 on my server

### Expected Behavior

upload should pass

### Steps To Reproduce

try to upload some data 

### Environment

```markdown
- OS:
- How docker service was installed: via unraid install, mariadb DB
```

### CPU architecture

x86-64

### Docker creation

```bash
via unraid script
```

### Container logs

```bash
Fehler	PHP	Error: Attempt to read property "uri" on array at /config/www/nextcloud/apps/maps/lib/Listener/CardUpdatedListener.php#53		2023-06-05T10:25:26+0200
Fehler	cron	InvalidArgumentException: This parser can only read from strings or streams.
```

**Comment by drizuid** [comment]
ensure you are using ntp and using the correct tz variable. you're not really providing any info we can use to help you. showing the time on the host and in the container is a good start, the docker run for nextcloud as well
