### ISSUE TITLE
This version of Nextcloud is not compatible with PHP>=8.2. You are currently running 8.2.7.

### ISSUE THREAD

**Issue by Rkenn3dy** [linuxserver/docker-nextcloud#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I don't think this needs anymore, i'm really not sure why after several weeks and several updates this error message is still being displayed.

This version of Nextcloud is not compatible with PHP>=8.2.
You are currently running 8.2.7.

### Steps To Reproduce

Update
Open
Error

### Environment

```markdown
- OS:uNRAID
- How docker service was installed: Using unRAID community apps.
```

### CPU architecture

x86-64

### Docker creation

```bash
Utilizing unRAID community apps/dockers to install
```

### Container logs

```bash
Logs are fine, nothing that logs show point to this web UI message.
```

**Comment by aptalca** [comment]
See pinned issue

**Comment by Rkenn3dy** [comment]
> 

Where? Under Issue & PR Tracker there is nothing in regards to this, other than my closed out request about the php issue.

**Comment by nemchik** [comment]
> > 
> 
> Where? Under Issue & PR Tracker there is nothing in regards to this, other than my closed out request about the php issue.

https://github.com/linuxserver/docker-nextcloud/issues/288
