### ISSUE TITLE
[BUG] HTTP/2 disabled?

### ISSUE THREAD

**Issue by motionthings** [linuxserver/docker-nextcloud#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not really a bug from you.
More a question from me.

After the latest update i got a lot of 504 errors.
I had to disable HTTP/2 in my proxy (HA-proxy) to make it work.
Did someone disable HTTP/2 support in the latest release?

### Expected Behavior

Not really something I need but I had to disable HTTP/2 for the container.

### Steps To Reproduce

OPNsense 23.1.11 with HA-proxy 4.1
Unraid 6.12.2

Enable HTTP/2 in HA-proxy and you'll get 504 errors on the nextcloud instance.
I've had the same config in HA-proxy for years without any problems.

### Environment

```markdown
- OS:Unraid/Slack
- How docker service was installed: Came with Unraid. Docker version is 20.10.24.
```

### CPU architecture

x86-64

### Docker creation

```bash
Created through the Unraid appstore
```

### Container logs

```bash
Logs have no errors since this is a Proxy config problem.
```

**Comment by nemchik** [comment]
As far as I can tell, nginx still does not support proxying http2 (ex: if you were using swag, or another reverse proxy that uses nginx, I am not sure about haproxy). Ref: https://github.com/linuxserver/reverse-proxy-confs/pull/576 we did add the http2 directive to all proxy confs to solve a different issue, and it should also be included by default in the nextcloud nginx confs https://github.com/linuxserver/docker-nextcloud/blob/191b54476295e7dd0f2dc35207c67b598febd1c8/root/defaults/nginx/site-confs/default.conf.sample#L13-L14

Check your container logs to be sure the nginx confs are up to date (it will list which ones are not).

Also, haproxy does not use nginx and you are proxying port 80 it would not have http2 as that's only set on port 443.

If the client connecting to your proxy can connect with http2 to the proxy that should be plenty, and having the connection be http2 from the proxy to nextcloud shouldn't make a huge difference.
