### ISSUE TITLE
[BUG] Some files have not passed the integrity check error

### ISSUE THREAD

**Issue by k-matti** [linuxserver/docker-nextcloud#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the [documentation ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-code-integrity). ([List of invalid files…](https://192.168.0.55/settings/integrity/failed) / [Rescan…](https://192.168.0.55/settings/integrity/rescan?requesttoken=wZ3xhCuYTXOjRzvItLQH%2BW7LxhilOgEnlaVN1GRaXvk%3D%3A%2BO%2Baz2nvFBfidkGS2sB9yxaCpW6OXTdK4ep1vhUMMpI%3D))

### Expected Behavior

No error

### Steps To Reproduce

1. Use the newest image
2. Go to Administration settings

### Environment

```markdown
- OS: linux
- How docker service was installed: apt install
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.7"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Warsaw
    volumes:
      - /share/Nextcloud/config:/config
      - /share/Nextcloud/data:/data
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      default:
      nextcloud:
        ipv4_address: 192.168.0.55

  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - /share/Nextcloud/db:/config
    networks:
    - default
    restart: unless-stopped

networks:
  nextcloud:
    name: nextcloud-network
    external:
      name: qnet-static-eth0-0fa2ce
```

### Container logs

```bash
.
```

**Comment by flowermoron** [comment]
same issue! :(

**Comment by nemchik** [comment]
```
docker exec -it nextcloud touch /config/www/nextcloud/config/needs_migration
docker restart nextcloud
```
There should be a button in the nextcloud admin page to rescan the files after you do that.

Should be a one time issue.

**Comment by austinmini75** [comment]
> ```
> docker exec -it nextcloud touch /config/www/nextcloud/config/needs_migration
> docker restart nextcloud
> ```
> 
> There should be a button in the nextcloud admin page to rescan the files after you do that.
> 
> Should be a one time issue.

thanks for this
