### ISSUE TITLE
[BUG] Configuration File "Resource Busy"

### ISSUE THREAD

**Issue by bconn98** [linuxserver/docker-nextcloud#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sed: can't move '/config/www/nextcloud/config/config.phpmlFMdF' to '/config/www/nextcloud/config/config.php': Resource busy
s6-rc: warning: unable to start service init-nextcloud-config: command exited 1

### Expected Behavior

Server can read configuration and startup. This file had no issue on an Ubuntu system. After migrating the RAID setup to the new Rocky Linux 9 system I have been unable to start a nextcloud instance.

### Steps To Reproduce

1. Define nextcloud-config.php with full open permissions 
   ```bash
    -rwxrwxrwx.  1  myuser        mygroup   916 Jun 25 13:59 nextcloud-config.php
   ```
2. Add as a volume mount in docker-compose.yml
   ```yml
    volumes:
      - /samba/Documents/Containerization/Compose/SWAG/nextcloud-config.php:/config/www/nextcloud/config/config.php:rw
   ```
3. docker logs nextcloud

### Environment

```markdown
- OS: Rocky Linux 9
- How docker service was installed: DNF Package Manager
```

### CPU architecture

x86-64

### Docker creation

```bash
nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud
    deploy:
      replicas: 1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 8182:443
    volumes:
      - /samba/Documents/Containerization/Compose/SWAG/nextcloud-config.php:/config/www/nextcloud/config/config.php:rw
      - /samba/Documents/Containerization/Compose/SWAG/nextcloud-user.ini:/config/www/nextcloud/.user.ini
      - /samba/Nextcloud:/data
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
sed: can't move '/config/www/nextcloud/config/config.phpmMdiMa' to '/config/www/nextcloud/config/config.php': Resource busy
s6-rc: warning: unable to start service init-nextcloud-config: command exited 1
```

**Comment by nemchik** [comment]
We don't recommend (or support) putting your `/config` volume on a network share.

**Comment by bconn98** [comment]
The mount is named "samba" because it is the network mount for other devices. The file is local to the machine executing docker compose.

**Comment by aptalca** [comment]
You need to mount a local _folder_ for `/config`

**Comment by bconn98** [comment]
Yes, please read my previous message. This is a locally mount drive. The hard drives are sata mounted into the same motherboard as the CPU that is executing docker. There is only 1 OS executing on the CPU. The drives are local, ignore the name `samba` it is named as such because my other machine mount it.

**Comment by aptalca** [comment]
Please read my message again, especially the word that's in Italic.

**Comment by bconn98** [comment]
That appeared to resolve the issue. I'm not sure how an OS swap could cause that issue. SELinux?
