### ISSUE TITLE
[BUG] <Cannot upgrade/update docker image from version 21 to 22+>

### ISSUE THREAD

**Issue by squallxb1983** [linuxserver/docker-nextcloud#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I always run nextcloud in the docker container with default tag until I found it cannot start recently.

It says in the log -
Can't start Nextcloud because the version of the data (21.0.6.2) is more than one major version behind the docker image version (27.0.1.2) and upgrading more than one major version is not supported. Please run an image tagged for the major version 22 first.

Then I followed the instructions in this [page](https://info.linuxserver.io/issues/2023-06-25-nextcloud/). I used the oldest version  22.2.3 which is the closest one to my data version. The container can start and I ran the updater, but it said like below:

Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 22.2.3.

Update to Nextcloud 21.0.9 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.9.zip
Open changelog 
....
[✘] Extracting failed
Downloaded version is lower than installed version

Update failed. To resume or retry just execute the updater again.

Is there a major version 21.x.x available besides the 4 in the [instruction](https://info.linuxserver.io/issues/2023-06-25-nextcloud/) which I can use for my case? If not, how can I upgrade the docker image from current version 21?

Thank you for the help.

### Steps To Reproduce

environment - OMV/Portainer

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:version-22.2.3
    container_name: nextcloud
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Stockholm
    volumes:
      - /srv/dev-disk-by-uuid-9dadb505-8d6a-4aba-8700-e4732a27f010/AppData/nextcloud/config:/config
      - /srv/dev-disk-by-uuid-9dadb505-8d6a-4aba-8700-e4732a27f010/Nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=998
      - PGID=100
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Europe/Stockholm
    volumes:
      - /srv/dev-disk-by-uuid-9dadb505-8d6a-4aba-8700-e4732a27f010/AppData/mariadb/config:/config
    restart: unless-stopped
```

### Container logs

```bash
docker exec -it nextcloud updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 22.2.3.

Update to Nextcloud 21.0.9 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.9.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✘] Extracting failed
Downloaded version is lower than installed version

Update failed. To resume or retry just execute the updater again.
```

**Comment by nemchik** [comment]
Try using the image for version 26. Do the updater.phar from there. You might get PHP compatibility errors, post them here and we can pick a different image.

**Comment by squallxb1983** [comment]
> Try using the image for version 26. Do the updater.phar from there. You might get PHP compatibility errors, post them here and we can pick a different image.

Thanks for your comments. I've tried all the 4 proposed docker images. No matter which one I use, the current version is always 22.2.3 and the available version for update is always 21.0.9 after running the updater.

**Comment by nemchik** [comment]
> > Try using the image for version 26. Do the updater.phar from there. You might get PHP compatibility errors, post them here and we can pick a different image.
> 
> Thanks for your comments. I've tried all the 4 proposed docker images. No matter which one I use, the current version is always 22.2.3 and the available version for update is always 21.0.9 after running the updater.

- Switch your image to `lscr.io/linuxserver/nextcloud:version-22.2.3`
- Delete `/config/www/nextcloud/index.php`
- Run `docker exec -it nextcloud updater.phar` multiple times until it says there are no updates or you get a php incompatibility message

Check `/config/www/nextcloud/version.php` and `/config/www/nextcloud/config/config.php` and see if the version listed in each of them matches. If they don't, post both versions here. If they do match, and they are below 26.x switch to the image for the version from https://info.linuxserver.io/issues/2023-06-25-nextcloud/ and run the updater command again. If the version is 26.x or above you should be able to run `lscr.io/linuxserver/nextcloud:latest` and it should work. You may need to watch the container logs for any warnings or mentions of outdated confs to replace.

**Comment by squallxb1983** [comment]
> > > Try using the image for version 26. Do the updater.phar from there. You might get PHP compatibility errors, post them here and we can pick a different image.
> > 
> > 
> > Thanks for your comments. I've tried all the 4 proposed docker images. No matter which one I use, the current version is always 22.2.3 and the available version for update is always 21.0.9 after running the updater.
> 
> * Switch your image to `lscr.io/linuxserver/nextcloud:version-22.2.3`
> * Delete `/config/www/nextcloud/index.php`
> * Run `docker exec -it nextcloud updater.phar` multiple times until it says there are no updates or you get a php incompatibility message
> 
> Check `/config/www/nextcloud/version.php` and `/config/www/nextcloud/config/config.php` and see if the version listed in each of them matches. If they don't, post both versions here. If they do match, and they are below 26.x switch to the image for the version from https://info.linuxserver.io/issues/2023-06-25-nextcloud/ and run the updater command again. If the version is 26.x or above you should be able to run `lscr.io/linuxserver/nextcloud:latest` and it should work. You may need to watch the container logs for any warnings or mentions of outdated confs to replace.

I deleted index.php and then ran the updater once again - same result. 

But I think you identified the problem, the versions in version.php(version is 22.2.3) and config.php(version is 21.0.6.2) are not matching. How should we fix this?

Thank you again for the help.

**Comment by nemchik** [comment]
So the updater still shows the message
`Downloaded version is lower than installed version` ?

**Comment by squallxb1983** [comment]
> So the updater still shows the message `Downloaded version is lower than installed version` ?

Yes, exactly.

**Comment by nemchik** [comment]
Try `lscr.io/linuxserver/nextcloud:version-23.0.4` and again delete index.php, then restart the container and try the updater again.

**Comment by squallxb1983** [comment]
> Try `lscr.io/linuxserver/nextcloud:version-23.0.4` and again delete index.php, then restart the container and try the updater again.

I tried version 23.0.4. Now the current version is 23.0.4. I also deleted index.php. However, the stable version for update is always 21.0.9 after running the updater, so that the "Downloaded version" will be always lower than the installed version, no matter it is 22..2.3, 23.0.4, 24.0.12 or any newer version. Thus the result is still same - Downloaded version is lower than installed version. Update failed. To resume or retry just execute the updater again.

**Comment by nemchik** [comment]
That's strange. I'm unfortunately kind of out of ideas. This may be something you'll need to ask for help on the nextcloud forums. You can reference these comments and ping me there and I can continue helping with the docker specifics. Same username as here.

**Comment by squallxb1983** [comment]
I changed the version data in version.php and was able to update the version of data from 21.0.6.2 to 27.0.1. But now I have a new issue and will create a new post for help.
