### ISSUE TITLE
[BUG] Can't start nextcloud due to data version newer than image version

### ISSUE THREAD

**Issue by evanwht** [linuxserver/docker-nextcloud#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed the steps listed [here](https://info.linuxserver.io/issues/2023-06-25-nextcloud/). 

I ran `docker exec -it nextcloud updater.phar` multiple times with the last update going from `26.0.5` > `27.0.2`. I switched my image to `lscr.io/linuxserver/nextcloud:version-27.0.0` but got an error message saying that the version of data is newer than the image version. I checked docker hub and the newest container image is `27.0.1` which is still behind the data version.

### Expected Behavior

After updating nextcloud on the cmd line, nextcloud starts normally with the latest image version.

### Steps To Reproduce

1. Starting from older versions of nextcloud
2. run `docker exec -it nextcloud updater.phar` until 27.x.x is installed
3. update container image to be latest
4. restart nextcloud

### Environment

```markdown
- OS: ubuntu 20
- How docker service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
nextcloud:
    container_name: nextcloud
    restart: always
    image: lscr.io/linuxserver/nextcloud
    volumes:
      - ${DATADIR}/docker/nextcloud:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - traefik_proxy
      - default
    depends_on:
      - mariadb
```

### Container logs

```bash
using keys found in /config/keys
Can't start Nextcloud because the version of the data (27.0.2.1) is higher than the docker image version (27.0.1.2) and downgrading is not supported. Are you sure you have pulled the newest image version?
```

**Comment by nemchik** [comment]
this is actually pretty obnoxious on NC's part. The latest stable release on https://github.com/nextcloud/server/releases as of writing is [v27.0.1](https://github.com/nextcloud/server/releases/tag/v27.0.1) which means our stable releases are current. they have 27.0.2 RC (release candidate) pre-releases. our image only builds stable releases at the moment.

There isn't a great answer for this other than wait for them to release 27.0.2 as stable.

**Comment by GuiPoM** [comment]
Hello,

There is still something I don't understand, and this is getting "worse" since the image has been switched to the installation self contained.
Nextcloud is asking for an update : 27.0.2.
I can also see that on their github it is not indicated as released. But Nextcloud 27.0.2 IS released here: https://nextcloud.com/fr/changelog/
![image](https://github.com/linuxserver/docker-nextcloud/assets/11942518/5f86522a-8ecf-4637-a5ed-2d741ab7cfca)
Tag exists: https://github.com/nextcloud/server/tree/v27.0.2  https://github.com/nextcloud/server/tree/v27.0.2

So there is something inconsistent with this change, even if the update management is set to enterprise with a update page removed to avoid any issue, we rely on a delivery that is late behind the official release (maybe this is always a question of days, but keeping nextcloud up to date can be an administrative task that keeps sending notifications)

**Comment by j0nnymoe** [comment]
Nextcloud are yet to cut a release on their github https://github.com/nextcloud/server/releases which is why we don't have a tag for it yet.

> this is getting "worse" since the image has been switched to the installation self contained.
This is purely a coincidence. It's not the first time they've messed up their releases.

**Comment by GuiPoM** [comment]
Can we get in touch with them to explain why a proper release process is very important to then be integrated in other services ?
Maybe they are not aware that they are missing some steps after tagging, or they do it intentionnaly for an unknown reason.
But I would expect a tag + a release as soon as they publish the zipfile on their website

I know that this is not the first time it happened, but until now I was able to force update if needed, here there is nothing I can do, and maybe also nothing that could be done here as we rely on nextcloud for getting the proper installation.

**Comment by j0nnymoe** [comment]
Opened an issue here https://github.com/nextcloud/server/issues/39845

Hopefully they see it soon or explain why it hasn't been released.

**Comment by GuiPoM** [comment]
Thank you ! ☺

**Comment by mirisbowring** [comment]
How can we bypass this problem for now? I am stuck with an offline nextcloud instance.
Could i "just paste" the content of their 17.0.2 tag into my www folder?

**Comment by j0nnymoe** [comment]
Simply put, no.
