### ISSUE TITLE
Alpine 3.6 update - webpage not able to log in

### ISSUE THREAD

**Issue by airbillion** [linuxserver/docker-nextcloud#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 Unraid
no errors in the unraid log...

After the latest update to Alpine 3.6 I can no longer login to the web client...
Login button does not function any longer...

Android and desktop clients still work...

**Comment by sparklyballs** [comment]
no issues here, i've used build 59, 60 and latest with 3.6 and can switch between them with the same dataset and log in and out with absolutely no problems.

**Comment by sparklyballs** [comment]
this has been fixed in more recent build.
