### ISSUE TITLE
Nextcloud updater

### ISSUE THREAD

**Issue by fusengine** [linuxserver/docker-nextcloud#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Why you remove Nextcloud updater to manual upgrade version? is very bad choice.

### Expected Behavior

Why you remove Nextcloud updater to manual upgrade version? is very bad choice.

### Steps To Reproduce

Why you remove Nextcloud updater to manual upgrade version? is very bad choice.

### Environment

```markdown
Why you remove Nextcloud updater to manual upgrade version? is very bad choice.
```

### CPU architecture

x86-64

### Docker creation

```bash
Why you remove Nextcloud updater to manual upgrade version? is very bad choice.
```

### Container logs

```bash
Why you remove Nextcloud updater to manual upgrade version? is very bad choice.
```

**Comment by j0nnymoe** [comment]
Because this https://info.linuxserver.io/issues/2023-06-25-nextcloud/

**Comment by fusengine** [comment]
when you decide to remove an option, be sure to follow the update of this one. because version 27.0.2 is out and you are not up to date.

**Comment by Roxedus** [comment]
It is not. 27.0.2 is currently just a release *candidate* https://github.com/nextcloud/server/releases

**Comment by fusengine** [comment]
you are sure really? but why you delete this possibility to upgrade is very very bad is important user have a choice.

**Comment by Roxedus** [comment]
I am sure. Are you sure, did you check the link?

In order to streamline support, we only support one way of upgrading. The changes we made for 27 moves the application inside the container, in line with all our other images, making it impossible to support the legacy way of upgrading.

**Comment by fusengine** [comment]
okay but I m crazy to see this version? 

```text
Une nouvelle version est disponible : Nextcloud 27.0.2
3 applications n'ont pas de version compatible pour cette version de Nextcloud disponible.

Applications n'ayant pas de version compatible 

Admin notifications ↗
Activities for shared file downloads ↗
Activities for shared file downloads, visible to all admins ↗
Applications compatibles avec la nouvelle version 
```

**Comment by fusengine** [comment]
is here https://nextcloud.com/fr/changelog/

**Comment by aptalca** [comment]
Feel free to report to Nextcloud that their Github releases may not be up to date.

Thanks.

**Comment by j0nnymoe** [comment]
To upgrade, you need to change the tag your container uses. If you use latest, you'll get the updates as and when they're built. Everything is explained in our post.

**Comment by fusengine** [comment]
my brother if I make a post it means that this version is not present so please find a way to update manually

**Comment by Roxedus** [comment]
We are picking up releases nextcloud releases on Github. We will not consider manual upgrades.

**Comment by fusengine** [comment]
so thank you for following the updates sir

**Comment by fusengine** [comment]
in GitHub Nextcloud v27.0.2 is here https://github.com/nextcloud/server/tags 😊

**Comment by nemchik** [comment]
> in GitHub Nextcloud v27.0.2 is here https://github.com/nextcloud/server/tags 😊

https://github.com/nextcloud/server/releases currently lists 27.0.2 as pre-release. our image will update once a stable release is available.

**Comment by naelfe** [comment]
Hm... I can see what you linked:
Two tags. One as rc1, one regular.
![image](https://github.com/linuxserver/docker-nextcloud/assets/108142825/2c134a73-4970-4a62-a9e3-8fd56be14be0)
As you said the v27.0.1 release is the "latest" and v27.0.2rc1 as "Pre-release".
![image](https://github.com/linuxserver/docker-nextcloud/assets/108142825/c3f26018-d079-41e1-bd41-bccecda0692a)
Yet they notify users for an available update...
![image](https://github.com/linuxserver/docker-nextcloud/assets/108142825/4aa11604-afb3-4bc5-ac72-aa45668bbc9a)
Seems like they are missing the release for the 27.0.2 tag

Nevermind, there is already an issue :D
https://github.com/nextcloud/server/issues/39845
