### ISSUE TITLE
[BUG] No update notifications for installed apps

### ISSUE THREAD

**Issue by GuiPoM** [linuxserver/docker-nextcloud#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nextcloud is not informing admin users of new apps version. Also no mail received. 
It might be linked to the removal of system update notification.

I am not able to easily reproduce this issue but Recognize app is currently 4.3.0, new version is 4.3.2, and nextcloud is not notifying about the update.
![maj](https://github.com/linuxserver/docker-nextcloud/assets/11942518/70329891-5495-4166-bf10-f7a8a261177a)

### Expected Behavior

I was used to get notifications (both app, webapp or mail) when a new app version is released

### Steps To Reproduce

Nothing special, but a new app version must be available for one installed app

### Environment

```markdown
- OS: OMV 6.7.0-1 (Shaitan)
- How docker service was installed: omv docker compose official plugin
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.8"
services:

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      PUID: 998
      PGID: 100
      TZ: Europe/Paris
    labels:
      diun.enable: true
    volumes:
      - /srv/XXX/nextcloud/config:/config
      - /srv/XXX/appdata/nextcloud/data:/data
      - XXX
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - nextcloud
      - nextcloud_db
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    998
User GID:    100
───────────────────────────────────────
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by nemchik** [comment]
Can you try restarting your container and see if it updates the apps?

That wouldn't be the final recommended solution, but I'm curious if that does it. I was under the impression (and looked at the NC code, but maybe missed something) that the updatenotification app only notifies for updates to NC itself. If this is incorrect, I'd like to find a better solution, and it's easy to add back into our image.

**Comment by GuiPoM** [comment]
Hello. 
Thank you for your answer.
Sadly I updated this app, but next time there is another app update I will check that the notification is not available, and check if the container restart does anything.

**Comment by szaimen** [comment]
The updatenotification app is indeed also responsible for notifying about app updates.

**Comment by GuiPoM** [comment]
I have one app to update, Maps to 1.1.0. 
I do not get the notification and even a container restart does not help here.
