### ISSUE TITLE
[FEAT] Allow tagging with major Nextcloud versions

### ISSUE THREAD

**Issue by alexanderharm** [linuxserver/docker-nextcloud#361]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be great if one could tag the docker image with the latest Nextcloud version, so instead of having to change one's docker-compose file for every version increment of Nextcloud I would love to see the possibility to just tag major versions like

```
image: ghcr.io/linuxserver/nextcloud:26
image: ghcr.io/linuxserver/nextcloud:27
```

### Reason for change

I find running `latest` tag a bit risky because new major releases by Nextcloud seem to be a bit buggy and I prefer to wait some minor version increments before upgrading.

On the other hand, having to follow your releases closely to adjust the tag in all installations in a timely manner seems like a lot of hassle.

I would love to have a more setup and forget approach...

Thanks for your consideration.

**Comment by Roxedus** [comment]
We do have some unofficial tags you can look into, we recently also published this https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time

**Comment by alexanderharm** [comment]
Thanks for the link. However, I failed to see how that could solve my request... I could pin it now at 27.0.2 but I still can't pin it at all releases for 27.x.x

**Comment by aptalca** [comment]
This part explains why what you're trying to do is not a good idea: https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time#semver-info
