### ISSUE TITLE
[BUG] Stuck in Maintenance mode

### ISSUE THREAD

**Issue by rcjcarr** [linuxserver/docker-nextcloud#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installed Nextcloud Hub 6 this morning by pulling a new docker image from  ghcr.io/linuxserver/nextcloud. Afterwards my NC instance was stuck in maintenance mode. I had to manually edit the config.php file to change from 'maintenance' => true to 'maintenance' => false. NC Hub 6 instance seems to work fine now.

### Expected Behavior

NC Instance (27.1.0.7) to restart out of maintenance mode

### Steps To Reproduce

Docker pull latest NC image. Re-boot server.

### Environment

```markdown
- OS:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- How docker service was installed:
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:38 2023
 OS/Arch:           linux/arm64
 Context:           default
```

### CPU architecture

arm64

### Docker creation

```bash
version: "2"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1001 #change PUID if needed
      - PGID=100  #change PGID if needed
      - TZ=America/Toronto #change Time Zone if needed
      - OVERWRITEPROTOCOL=https
    volumes:
      - /SSD/appdata/nextcloud/config:/config #/srv/dev-disk-by-label-disk1 needs to be adjusted
      - /SSD/appdata/nextcloud/data:/data     #/srv/dev-disk-by-label-disk1 needs to be adjusted
    depends_on:
      - mariadb
#    ports: # uncomment this and the next line if you want to bypass the proxy
#      - 450:443
    restart: unless-stopped

  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=1001 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=rampudd  #change password
      - TZ=America/Toronto #Change Time Zone if needed
    volumes:
      - /SSD/appdata/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    hostname: redis
    volumes:
      - /SSD/appdata/redis:/data    #--> needs to be changed to your config
    restart: unless-stopped
networks:
   default:
      name: nginx-proxy
      external: true
```

### Container logs

```bash
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1001
User GID:    100
───────────────────────────────────────

cp: not replacing '/config/custom.cnf'
[custom-init] No custom files found, skipping...
230916 09:03:03 mysqld_safe Logging to '/config/databases/9f99e4d9ed56.err'.
230916 09:03:03 mysqld_safe Starting mariadbd daemon with databases from /config/databases



#################################################################
#                                                               #
#           An upgrade is required on your databases.           #
#                                                               #
#         Stop any services that are accessing databases        #
#          in this container, and then run the command          #
#                                                               #
#             mariadb-upgrade -u root -p<PASSWORD>              #
#                                                               #
#################################################################



[ls.io-init] done.

END OF LINE
█
```

**Comment by rcjcarr** [comment]
I also updated the mariadb as indicated in the above NC container log file. No errors were reported.
`Major version upgrade detected from 10.6.13-MariaDB to 10.11.5-MariaDB. Check required!
Phase 1/8: Checking and upgrading mysql database
Processing databases
mysql
mysql.column_stats                                 OK
mysql.columns_priv                                 OK
mysql.db                                           OK
mysql.event                                        OK
mysql.func                                         OK
mysql.global_priv                                  OK
mysql.gtid_slave_pos                               OK
mysql.help_category                                OK
mysql.help_keyword                                 OK
mysql.help_relation                                OK
mysql.help_topic                                   OK
mysql.index_stats                                  OK
mysql.innodb_index_stats                           OK
mysql.innodb_table_stats                           OK
mysql.plugin                                       OK`
.
.
.
nextcloud.oc_share                                 OK
nextcloud.oc_share_external                        OK
nextcloud.oc_storages                              OK
nextcloud.oc_storages_credentials                  OK
nextcloud.oc_systemtag                             OK
nextcloud.oc_systemtag_group                       OK
nextcloud.oc_systemtag_object_mapping              OK
nextcloud.oc_tables_columns                        OK
nextcloud.oc_tables_log                            OK
nextcloud.oc_tables_rows                           OK
nextcloud.oc_tables_shares                         OK
nextcloud.oc_tables_tables                         OK
nextcloud.oc_tables_views                          OK
nextcloud.oc_text_documents                        OK
nextcloud.oc_text_sessions                         OK
nextcloud.oc_text_steps                            OK
nextcloud.oc_textprocessing_tasks                  OK
nextcloud.oc_trusted_servers                       OK
nextcloud.oc_twofactor_backupcodes                 OK
nextcloud.oc_twofactor_providers                   OK
nextcloud.oc_user_status                           OK
nextcloud.oc_user_transfer_owner                   OK
nextcloud.oc_users                                 OK
nextcloud.oc_vcategory                             OK
nextcloud.oc_vcategory_to_object                   OK
nextcloud.oc_webauthn                              OK
nextcloud.oc_whats_new                             OK
performance_schema
sys
sys.sys_config                                     OK
Phase 7/8: uninstalling plugins
Phase 8/8: Running 'FLUSH PRIVILEGES'
OK
rc@raspberrypi:~ $

**Comment by clowncracker** [comment]
I'm having the same issue, following.

**Comment by drizuid** [comment]
Hi, sorry for the delay. Unfortunately, we don't control nextcloud as we are not the devs, we merely package it in the container. However, you mentioned you edited your config.php and had to restart, you can just `docker exec -it nextcloud occ maintenance:mode --off` next time, no reboot needed.

**Comment by rcjcarr** [comment]
ok sounds good. Thanks for the tip.
