### ISSUE TITLE
Nextcloud Talk Slowdown

### ISSUE THREAD

**Issue by jared2876** [linuxserver/docker-nextcloud#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is an issue i havent seen much about else where. I have a larger nextcloud install consisting of a turn server for talk, redis for caching, and hardware to support.

When more then 2 users go into a nextcloud talk group chat the system will come to a screeching hault by creating latency higher then say 30 seconds. My average latency is in the 100s on average. This is also just with chat no VOIP active.

I am not sure if this is an issue with this image or more aimed at nextcloud itself. I have also been able to consistently reproduce this on a fresh docker install as well. 

### Expected Behavior

See latency with very little change when in group chats.

### Steps To Reproduce

1. go to nextcloud talk.
2. enter a group chat.
3. have 2 other user in group chat.
4. latency spike.

### Environment

```markdown
- OS: alpine linux as well as UNRAID
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose from linuxserver.
```

### Container logs

```bash
as far as i can see there is no logable issues to report.
```

**Comment by KaeTuuN** [comment]
@jared2876 If you havn't found a solution yet: This is the normal NC behaviour if you don't have a High Performance Backend (HBP) installed for Nextcloud.

**Comment by KaeTuuN** [comment]
@jared2876 If you havn't found a solution yet: This is the normal NC behaviour if you don't have a High Performance Backend (HBP) installed for Nextcloud.

**Comment by jared2876** [comment]
I had a feeling that was the issue. The only thing that was odd was i didnt see this behavior in the past. It also only happens in the web-ui. The Talk app does not have this issue.

**Comment by KaeTuuN** [comment]
This will also happen with the app, but you need one or two more participants.
