### ISSUE TITLE
Permissions of mounted /data folder get set to PUID and PGID and all other permissions removed

### ISSUE THREAD

**Issue by rottenkumquat** [linuxserver/docker-nextcloud#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Permissions for the share mounted as /data are set to the permissions of the configured PUID and PGID. All other users and groups get removed.

### Expected Behavior

Leave permissions alone?

### Steps To Reproduce

..

### Environment

```markdown
- OS: Synology DMS 7.2
- How docker service was installed: Container Manager
```

### CPU architecture

x86-64

### Docker creation

```bash
Container Manager
```

### Container logs

```bash
..
```

**Comment by j0nnymoe** [comment]
Permissions of that mount need to be set to the same uid/gid that nextcloud is running as so it can manage those files. Nextcloud is designed to work like this and ideally you shouldn't just be directly accessing that folder.

**Comment by rottenkumquat** [comment]
That is fine and all. But what justification is there for removing other permissions I set there?
