### ISSUE TITLE
[BUG] No more Nextcloud new version notification

### ISSUE THREAD

**Issue by k-matti** [linuxserver/docker-nextcloud#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I notice my Nextcloud instance no longer sends notification about new version. I need to manually check if there is new version release and pull new image

### Expected Behavior

As a user on Nextcloud I get notification about new version

### Steps To Reproduce

1. Open Nextcloud
2. Go to Administration settings
3. Overview tab
4. See version section, no info about new version

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a
```

**Comment by nemchik** [comment]
Your best option is to subscribe to release notifications from this repository
