### ISSUE TITLE
App Shifts cant install

### ISSUE THREAD

**Issue by Router1982** [linuxserver/docker-nextcloud#369]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

https://github.com/csoc-de/Shifts/blob/master/README_INSTALL.md

Can Install but not working

see 

https://github.com/csoc-de/Shifts/issues/44

### Reason for change

https://github.com/csoc-de/Shifts/issues/44

**Comment by nemchik** [comment]
Just to start, I am assuming the language written in the readme and the linked issue is German. I don't know German, but I did at least use Google Translate.

You haven't described the specific issue you're having, just that you want to install an application and it didn't seem to work. Based on the readme for the file (translated) it looks like it requires node.js. We don't include that in our image, but you can use https://github.com/linuxserver/docker-mods/tree/universal-package-install `nodejs` and `npm`. Also our image does not have `www-data` but instead we have a user named `abc`. We don't install nextcloud to `/var/www/nextcloud` but instead we install it to `/app/www/public`, but the apps folder you want to be in is `/config/www/nextcloud/apps/`. The instructions mention doing some things in `/var/www/` but I don't know if that's just supposed to be the parent directory of nextcloud, or if it's hard coded to that location. You would need to ask the dev. Either way, both places it could be are not part of the user `/config` volume and would need a special volume mount to work (possibly multiple).

There might be other things required as well, but I can't tell as the install instructions are fairly limited.
