### ISSUE TITLE
[FEAT] Continue to build images for supported Nextcloud versions

### ISSUE THREAD

**Issue by teambvd** [linuxserver/docker-nextcloud#370]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It'd be great if we could have container images built for earlier versions of nextcloud which are still 'supported' (still getting updates) by the nextcloud team.

For example, nextcloud continues to maintain support/updates for versions 25, 26, and 27 per their [release maintenance schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule), with the latest builds being 25.0.12, 26.0.7, and 27.1.2 respectively, while it appears LSIO builds are only available up through 25.0.4 and 26.0.2 for those major release versions.

### Reason for change

With the [announcement back in June](https://info.linuxserver.io/issues/2023-06-25-nextcloud/) regarding the change to the LSIO nextcloud image, it's now required to update the nextcloud container itself as opposed to updating through either `updater.phar` or `occ upgrade` directly.  This leaves users without the option to keep up with maintenance / security updates to the NC deployment unless they migrate to the latest major release.

This typically wouldn't be a problem for many containerized applications, but with nextcloud's app store built in, many of nextcloud's applications lag a bit behind in support for the latest versions. 

Additionally, many find the 'previous major' release to be more stable, choosing to maintain one release behind the current major version (until known bugs are sorted, the next major release after, or otherwise).

Generating images for versions still under maintenance support by the application provider would help enable users to follow the recommended upgrade strategy for LSIO's nextcloud app, while retaining the ability to both maintain the security of their deployment, as well as choose when the right time is to move to the next major release.

**Comment by nemchik** [comment]
We discussed this briefly internally and do not currently have plans to maintain updates for versions of nextcloud that are older than the current major. Our version tagging does allow you to pin to a specific release, but you are correct that you will not receive maintenance or security upgrades when doing so.
