### ISSUE TITLE
[BUG] Weird Docker Setup 

### ISSUE THREAD

**Issue by ItsMeRitch** [linuxserver/docker-nextcloud#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cron location should be /config/www/nextcloud/ however, apparently mine is:

/app/www/public/cron.php

### Expected Behavior

In nextcloud admin interface, it says the cron is running fine however, I'm noticing that the trashbin isnt being emptied automatically (should be called by the cron). Upon checking my cron location, it wasn't in the normal place. 

/var/lib/docker/volumes/nextcloudcfg/_data/crontabs# cat root
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
# nextcloud cron
*/5     *       *       *       *       s6-setuidgid abc php -f /app/www/public/cron.php

Seems to be in a "public" folder - is this normal? 

the folder also contains:

![image](https://github.com/linuxserver/docker-nextcloud/assets/55960162/d611c188-f6ac-4242-a7f6-00200dd69dbe)

### Steps To Reproduce

Screenshot of config from portainer:

![image](https://github.com/linuxserver/docker-nextcloud/assets/55960162/9c499eb3-dc35-4ac1-95fd-c884d8e0f251)

![image](https://github.com/linuxserver/docker-nextcloud/assets/55960162/4f68b0cd-d138-4003-9aff-e45ef5959e93)

### Environment

```markdown
Ubuntu 22 

Nextcloud running in docker using latest image with a separate container for the database.
```

### CPU architecture

x86-64

### Docker creation

```bash
ngl I can't even remember at this point - included screenshots above of portainer gui
```

### Container logs

```bash
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2023-06-24 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
error: failed to rename /config/log/nginx/access.log to /config/log/nginx/access.log.1: Permission denied
error: failed to rename /config/log/php/error.log to /config/log/php/error.log.1: Permission denied
error: failed to rename /config/log/nginx/access.log to /config/log/nginx/access.log.1: Permission denied
error: failed to rename /config/log/php/error.log to /config/log/php/error.log.1: Permission denied
```

**Comment by aptalca** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/trashbin_configuration.html

`default setting. keeps files and folders in the trash bin for 30 days and automatically deletes anytime after that if space is needed (note: files may not be deleted if space is not needed).`

**Comment by ItsMeRitch** [comment]
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/trashbin_configuration.html
> 
> `default setting. keeps files and folders in the trash bin for 30 days and automatically deletes anytime after that if space is needed (note: files may not be deleted if space is not needed).`

This is what I have set :)

**Comment by aptalca** [comment]
Then you see why it doesn't delete things.

Closing

**Comment by ItsMeRitch** [comment]
> Then you see why it doesn't delete things.
> 
> Closing

doesn't answer my question - my storage is full and nextcloud should be deleting files if I have the setting above

**Comment by ItsMeRitch** [comment]
@aptalca 

Eventually figured out that its a bug with nextcloud. It does not use the physical storage space to calculate available space and the user must have a quota set (even if they are the only user). Recycle bin will not automatically empty when low on space if set on unlimited. 

Regarding the original question of my ticket, can you assist with the following?

cron location should be /config/www/nextcloud/ however, apparently mine is:

/app/www/public/cron.php

Is that correct and safe?

**Comment by nemchik** [comment]
> Regarding the original question of my ticket, can you assist with the following?
> 
> cron location should be /config/www/nextcloud/ however, apparently mine is:
> 
> /app/www/public/cron.php
> 
> Is that correct and safe?

The cron location moved when we made a significant change to the image around the release of NextCloud 27.x
https://info.linuxserver.io/issues/2023-06-25-nextcloud/

`/app/www/public/cron.php` is correct and safe.
