### ISSUE TITLE
[BUG] Pulling new image uninstall some apps

### ISSUE THREAD

**Issue by tarbib** [linuxserver/docker-nextcloud#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Most of the time, when I pull the latest image of Nextcloud. Some apps are uninstalled.
When I click on apps, the one uninstalled is marked "Version 0".
I then have to click on uninstall and install again to get them back. No data loss.

### Expected Behavior

Apps should not be uninstalled.

### Steps To Reproduce

Pull Nextcloud latest image.

### Environment

```markdown
- OS:Ubuntu
- How docker service was installed:
I used cosmos-server.io and more precisely this docker compose : 
https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Nextcloud/cosmos-compose.json
```

### CPU architecture

x86-64

### Docker creation

```bash
https://imgur.com/a/7BLFRmu
And used this docker compose :
https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Nextcloud/cosmos-compose.json
```

### Container logs

```bash
100.0.0.91 - admin [25/Oct/2023:20:05:45 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 200 925 "-" "Mozilla/5.0 (Linux) mirall/3.10.0 (build 17672) (Nextcloud, ubuntu-5.4.0-165-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)"
100.0.0.91 - - [25/Oct/2023:20:05:51 +0000] "GET /custom_apps/richdocumentscode/proxy.php?req=/hosting/capabilities HTTP/1.1" 404 638 "-" "Nextcloud Server Crawler"
100.0.0.91 - - [25/Oct/2023:20:05:51 +0000] "GET /custom_apps/richdocumentscode/proxy.php?req=/hosting/capabilities HTTP/1.1" 404 638 "-" "Nextcloud Server Crawler"
100.0.0.91 - - [25/Oct/2023:20:05:51 +0000] "POST /index.php/apps/mail/api/mailboxes/1/sync HTTP/1.1" 200 7204 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
100.0.0.91 - - [25/Oct/2023:20:05:51 +0000] "POST /index.php/apps/mail/api/mailboxes/7/sync HTTP/1.1" 200 6327 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
```

**Comment by j0nnymoe** [comment]
Please post the container logs, not nginx logs. This should show why the apps are getting removed.

**Comment by tarbib** [comment]
![IMG_20231025_222707_334](https://github.com/linuxserver/docker-nextcloud/assets/2255433/21aea722-dff9-43f0-922c-10bb9ada872e)
Screenshot for reference

**Comment by j0nnymoe** [comment]
We need the container logs.

**Comment by j0nnymoe** [comment]
So checking the json file you linked, you're not using our container. That's the official container, you need to seek support from nextcloud directly.

**Comment by tarbib** [comment]
Hello @j0nnymoe thank you for your answer it's actually seems to be using linuxserver image
![image](https://github.com/linuxserver/docker-nextcloud/assets/2255433/6096cf42-32f7-4c3d-aa7b-7e55692e711e)
Here's a screenshot of my logs (don't know if they are relevant though):
![image](https://github.com/linuxserver/docker-nextcloud/assets/2255433/70ec58c0-07ae-4104-995a-3b1303136931)

**Comment by Roxedus** [comment]
Thats not the container logs you get from our container. This is not our container <https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Nextcloud/cosmos-compose.json#L15>, these are not our variables <https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Nextcloud/cosmos-compose.json#L20-L27>

**Comment by j0nnymoe** [comment]
@tarbib then whoever designed that JSON for cosmos needs to recheck their work because the compose you're linking definitely isn't our image.

**Comment by azukaar** [comment]
Sorry it's my bad the app description wasn't properly updated, I have corrected it now
For your problem @tarbib make sure you show the volumes attached to the containers as the issue is probably that by default /var/www/html/custom_apps is not mounted to a volume (if you do it, it should work)
