### ISSUE TITLE
[BUG] Missing 27.1.3 Docker Image

### ISSUE THREAD

**Issue by AdrianSchoennagel** [linuxserver/docker-nextcloud#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I updated my Nextcloud installation using the GUI updater. This brought me to v27.1.3.
Then I updated my Nextcloud Docker container to its latest version, which brought me to v27.1.2.

Now I get the message:
"Can't start Nextcloud because the version of the data (27.1.3.2) is higher than the docker image version (27.1.2.1) and downgrading is not supported. Are you sure you have pulled the newest image version?"

It seems the same issue occurred with 27.0.2:
https://github.com/linuxserver/docker-nextcloud/issues/349
And I can see that NC has 27.1.3 available but not marked as released:
https://github.com/nextcloud/server/tree/v27.1.3

From this I understand that its not your fault, but is there anything I can do to get my instance up and running again?

### Expected Behavior

- GUI updater does not install a version for which no docker container is available.
- Docker Image for version 27.1.3

### Steps To Reproduce

1. start with old nextcloud installation and container (e.g. 27.0.x)
2. update nextcloud in UI
3. update docker container

### Environment

```markdown
- OS: Unraid v6.12.3
- How docker service was installed: Unraid community app store
```

### CPU architecture

x86-64

### Docker creation

```bash
repository: lscr.io/linuxserver/nextcloud
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Can't start Nextcloud because the version of the data (27.1.3.2) is higher than the docker image version (27.1.2.1) and downgrading is not supported. Are you sure you have pulled the newest image version?
```

**Comment by nemchik** [comment]
Unfortunately this is out of our control.

The best thing to do is wait for the release, potentially open an issue on their github requesting it, and in the future do NOT use the web UI to apply updates - only apply updates by updating the docker image.

**Comment by AdrianSchoennagel** [comment]
Thank you for the reply. I opened an issue here: https://github.com/nextcloud/server/issues/41172

Is only updating the container save? I remember having issues with this and needing to first apply updates through the UI.

**Comment by nemchik** [comment]
Yes.

https://info.linuxserver.io/issues/2023-06-25-nextcloud/

We changed the way our image is built to be closer to the official image, which has you only apply updates by updating the image. Web UI updates should be ignored, and CLI updates using `updater.phar` are no longer possible (it's been removed from the image). CLI commands using `occ` are still needed for some things, but the web UI will usually tell you if that needs to be done and will tell you the command you need to run.

**Comment by nemchik** [comment]
The new release is now available.

**Comment by AdrianSchoennagel** [comment]
> https://info.linuxserver.io/issues/2023-06-25-nextcloud/

Must have missed that one, thanks for pointing it out. 

> The new release is now available.

Thank you very much for getting it out quickly :+1:
