### ISSUE TITLE
[FEAT] Fix vulnerable packages.

### ISSUE THREAD

**Issue by bogdanioanliviu** [linuxserver/docker-nextcloud#378]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Update the following: 
ghostscript to 10.02.0-r0
imagemagick to 7.1.1.13-r1

as the existing versions are vulnerable 

### Reason for change

Fix and improve vulnerability of the image

### Proposed code change

Execute ask update && ask -U upgrade on every image creation

**Comment by thespad** [comment]
Every build uses the latest packages available at build time and we run weekly package checks to identify any packages that have changed in-between upstream releases.

The last build was 4 days ago and the releases you're referencing were published less than 4 days ago so obviously cannot be on the currently published image. When the next package check or upstream releases build is triggered, it will incorporable the updated versions.
