### ISSUE TITLE
[BUG] <Can't start Nexcloud after yesterday update>

### ISSUE THREAD

**Issue by stephanej30** [linuxserver/docker-nextcloud#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Next cloud won't start after yesterday update. was working fine before. this is the log. 

using keys found in /config/keys
Can't start Nextcloud because the version of the data (25.0.2.3) is more than one major version behind the docker image version (27.1.4.1) and upgrading more than one major version is not supported. Please run an image tagged for the major version 26 first.

### Expected Behavior

next cloud should work. 

### Steps To Reproduce

just won't start

### Environment

```markdown
- OS:Unraid
- How docker service was installed: via Unraid. 
updated via Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
Click in Unraid
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Can't start Nextcloud because the version of the data (25.0.2.3) is more than one major version behind the docker image version (27.1.4.1) and upgrading more than one major version is not supported. Please run an image tagged for the major version 26 first.
```

**Comment by aptalca** [comment]
Please run an image tagged for the major version 26 first as the log suggests

**Comment by stephanej30** [comment]
OK. and How??  i use docker so i don't have to go on the command line..

Stephane Jacob
***@***.***

Sent with Proton Mail secure email.

**Comment by j0nnymoe** [comment]
You can do this from the unraid template within the advanced editing option of the container. This is the issue you're facing: https://info.linuxserver.io/issues/2023-06-25-nextcloud/

**Comment by stephanej30** [comment]
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-20 │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.

**Comment by nemchik** [comment]
- Set your image to `lscr.io/linuxserver/nextcloud:version-26.0.2`
- Run `docker exec -it nextcloud updater.phar` in your unraid terminal (or if you open the container terminal it would just be `updater.phar`)
- Repeat the step above until there are no available updates
- Set your image to `lscr.io/linuxserver/nextcloud:latest` and check the container logs for mention of any outdated confs (update them if so - compare the sample file to the conf in the listing to apply any new changes)
- Optionally: pin your image to a specific version if you want to perform updates manually, ex: `lscr.io/linuxserver/nextcloud:version-27.1.4`

**Comment by stephanej30** [comment]
i have set the image to 26.0.2  and i tried from the unraid and the container terminal.
both give me the same error. 


[✔] Check for expected files[✘] Check for write permissions failed
The following places can not be written to:
    /config/www/nextcloud/updater/../index.php
    /config/www/nextcloud/updater/../remote.php
    /config/www/nextcloud/updater/../index.html
    /config/www/nextcloud/updater/../robots.txt
    /config/www/nextcloud/updater/../occ
    /config/www/nextcloud/updater/../AUTHORS
    /config/www/nextcloud/updater/../.htaccess
    /config/www/nextcloud/updater/../version.php
    /config/www/nextcloud/updater/../cron.php
    /config/www/nextcloud/updater/../console.php
    /config/www/nextcloud/updater/../status.php

Update failed. To resume or retry just execute the updater again.

Stephane Jacob
***@***.***

Sent with Proton Mail secure email.

**Comment by nemchik** [comment]
Can you post the contents of your config.php here? Sanitize any sensitive info like passwords or salts.

**Comment by nemchik** [comment]
Can you try to reset the file permissions?

From the unRAID terminal you should be able to run
```
chown -R 99:100 /mnt/user/appdata/nextcloud
```
(Pretty sure that's the right path, but you should confirm on your end before running)

Then restart the container and rerun the updater command

**Comment by stephanej30** [comment]
ok, now that fix the access error.  but i have a new error
now it's telling me i am trying to downgrade.
i the container setting i did put: `lscr.io/linuxserver/nextcloud:version-26.0.2`

[✘] Extracting failedDownloaded version is lower than installed version

Update failed. To resume or retry just execute the updater again.


***@***.***:~# sudo docker exec -it nextcloud updater.phar
Nextcloud Updater - version: v26.0.0beta2-9-g64e2e4c dirty

Current version is 26.0.2.

Update to Nextcloud 25.0.13 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.13.zip
Open changelog ↗

Stephane Jacob
***@***.***

Sent with Proton Mail secure email.

**Comment by nemchik** [comment]
Edit the version in your config.php to 25.0.0.0 and try again

**Comment by stephanej30** [comment]
i did change the version in config.php but i got the same issue. 
i edited /config/www/nextcloud/version.php and put 25.0.0.0.  Finally it did work. 
i had to change the source to lscr.io/linuxserver/nextcloud:26.0.2-ls245 and this fix the PHP error. 
now i have this error. 

[✔] Replace entry points
[ ] Delete old files ...PHP Warning:  rmdir(/config/www/nextcloud/updater/../core/fonts): Directory not empty in phar:///config/www/nextcloud/updater/updater.phar/lib/Updater.php on line 891
[✘] Delete old files failed
Could not rmdir: /config/www/nextcloud/updater/../core/fonts

i run it again and now i have this error. 

[✘] Delete old files failed
core/shipped.json is not available

i change the source back to: lscr.io/linuxserver/nextcloud:version-26.0.2

same. 

extcloud Updater - version: v25.0.11-5-g06c1bad

Current version is 25.0.13.

Update to Nextcloud 26.0.9 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-26.0.9.zip
Open changelog ↗

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✘] Delete old files failed
core/shipped.json is not available

**Comment by stephanej30** [comment]
OK.  it's working now. 

with the doc: Notification: Changes to our Nextcloud image
and your guidance and trying a few thing it's working now. 
i was stuck in maintenance mode, turne it of  et voila. 

thanks for your help.  i know it was painful but my server is back online.
