### ISSUE TITLE
[BUG] Nextcloud Log Error in 28.0.1 fixed but need change default.conf also

### ISSUE THREAD

**Issue by masterwishx** [linuxserver/docker-nextcloud#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/nextcloud/logreader/issues/1073
As issue is fixed by 28.0.1 or can be fixed by console command :

```./occ config:app:set logreader relativedates --value="false"```

but also default.conf is need to be changed to add : 

```
   types {
        text/javascript js mjs;
    }
    ...
    ...
    location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ { ...

```
https://github.com/nextcloud/logreader/issues/1073#issuecomment-1856211939

### Steps To Reproduce

..

### Environment

```markdown
Unraid and all
```

### CPU architecture

x86-64

### Docker creation

```bash
..
```

### Container logs

```bash
...
```

**Comment by masterwishx** [comment]
jest add "mjs" to location and "types{...}"
![image](https://github.com/linuxserver/docker-nextcloud/assets/28630321/ae0787fa-f377-413c-ab45-0dbc121e042c)

**Comment by masterwishx** [comment]
Thanks for the fix , should be nexcloud also updated to v28.0.1 ?

**Comment by thespad** [comment]
Not yet, in classic Nextcloud fashion they haven't done a Github release for 28.0.1 so we haven't picked up the build yet.

**Comment by Intenos** [comment]
I updated from 27.X to the latest docker with 28.0.1 and have a blank logging page. Do I have to do something in addition? I also replaced default.conf by default.conf.sample and haven´t seen the above addition integrated. But adding it manually did also not resolve the issue.
