### ISSUE TITLE
Nextcloud not fully loading in Edge, Chrome works - related somehow to default.conf

### ISSUE THREAD

**Issue by Intenos** [linuxserver/docker-nextcloud#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I upgraded Nextcloud from 27.X to 28.0.1.1 with the latest Docker release build and replaced the default.conf by the newly provided default.conf.sample.

Whereas in Chrom Nextcloud works properly, it doesn´t fully load in Edge. It starts that on the login page that it shows "Anmelden bei {productName}" instead of "Anmelden bei Nextcloud". After loging in and showing the Dashboard, it is neither able to load the files, nor the mails or weather. When switching to the Files App, it doesn´t show any files. In the development sidebar of Edge, a lot "..404 (Not Found)" errors are shown.

![image](https://github.com/linuxserver/docker-nextcloud/assets/44039580/f307e35f-d3f4-46dc-ac01-9fdc953d5ff4)

### Expected Behavior

It should work in Edge as in Chrome

### Steps To Reproduce

After playing around a bit and trying out different things, I found that it works again when removing the following (new) part of the default.conf below "location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ {":

   ```
location ~ \.js$ {
            default_type text/javascript;
        }

        location ~ \.mjs$ {
            default_type text/javascript;
        }
```

Whether the above is just a (not proper workaround) for resolving the actual problem or really the solutions, I don´t know.

### Environment

```markdown
- OS: OpenMediaVault 6.9.11-2 (Shaitan) on Linux 5.10.0-26-amd64
- How docker service was installed: Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
![image](https://github.com/linuxserver/docker-nextcloud/assets/44039580/e9bf3398-dfa0-4b98-a421-85a81e9bb3cf)

```

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-package-install to container
[mod-init] linuxserver/mods:universal-package-install at sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140 has been previously applied skipping
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

using keys found in /config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.conf.20230623
/config/nginx/site-confs/default.conf.20231216
/config/nginx/site-confs/default.conf.20230616
**** Adding nodejs to OS package install list ****
**** Adding npm to OS package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
OK: 361 MiB in 261 packages
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by OvernightPancake** [comment]
I am facing a similar issue on Firefox, albeit I am having far less of the page load than you seem to. Removing those lines seems to only resolve the issue for me if I also spoof my user agent to Chrome.

**Comment by cravas** [comment]
https://github.com/linuxserver/docker-nextcloud/issues/388#issuecomment-1868250993

I saw that issue a while ago.
Had to revert those changes and just live with the warn on the log.

**Comment by drizuid** [comment]
we have a PR being confirmed now to resolve this. applies to #403 also

**Comment by Intenos** [comment]
@drizuid 
Thank you very much for your work. But unfortunately it didn´t solve the issue. I still have to out-comment the mentioned parts.

**Comment by drizuid** [comment]
> @drizuid Thank you very much for your work. But unfortunately it didn´t solve the issue. I still have to out-comment the mentioned parts.

can you provide full container logs

**Comment by Intenos** [comment]
This one?

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-package-install to container
[mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
[mod-init] Installing linuxserver/mods:universal-package-install
[mod-init] linuxserver/mods:universal-package-install applied to container
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 28.0.1.1 (this can take a while) ...
Setting permissions
Initializing finished
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.conf.20230623
/config/nginx/site-confs/default.conf.20240102
/config/nginx/site-confs/default.conf.20230616
**** Adding nodejs to OS package install list ****
**** Adding npm to OS package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/3) Installing c-ares (1.19.1-r0)
(2/3) Installing nodejs (18.18.2-r0)
(3/3) Installing npm (9.6.6-r0)
Executing busybox-1.36.1-r5.trigger
OK: 361 MiB in 261 packages
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by drizuid** [comment]
yep, and this is using the new site-confs/default.conf as shipped, with no changes?

**Comment by Intenos** [comment]
Yes, I copied the default.conf.samle to default.conf to overwrite my adaptations and additionally re-created the container.

**Comment by drizuid** [comment]
ok, thanks! give us a bit

**Comment by drizuid** [comment]
just to be sure, after you copied the sample to default.conf, did you restart the container for the change to take effect?

**Comment by Intenos** [comment]
Yes, I restarted the container. And by the way, the logviewer page in Nextcloud stays empty and doesn´t show anything. This worked in between after it has been fixed by the update to 28.0.1 and the new container.

**Comment by drizuid** [comment]
i can replicate the issue and i am working on a PR

**Comment by Intenos** [comment]
Great! Thanks a lot.

**Comment by drizuid** [comment]
mr pr is here, but isn't covering all the issues yet. you're still welcome to play with it. https://github.com/linuxserver/docker-nextcloud/pull/405

**Comment by drizuid** [comment]
hi guys, please test `lspipepr/nextcloud:amd64-28.0.1-pkg-1497da69-dev-4030be827853102c904c898015197f9583a2f5fb-pr-405` and report back

**Comment by Intenos** [comment]
Great job! It works again. With Chrome, Edge as well as the Nextcloud logging page. Thank you.

**Comment by drizuid** [comment]
sorry for any inconvenience, we caught a couple inconsistencies that have been resolved now. do you mind testing `lspipepr/nextcloud:amd64-28.0.1-pkg-1497da69-dev-ca6cd4b47ecedde586350bba27124a174d9fb14c-pr-405` for me?

**Comment by Intenos** [comment]
Just for completeness. I´m not sure if I tested the logging page with the previous versions on both browsers. I could test it this evening or tomorrow if required. The next hours I´m not available.

**Comment by Intenos** [comment]
@drizuid : Can you reproduce that the logging page is blank with Chrome whereas it shows it in Edge?

**Comment by nemchik** [comment]
I can reproduce the logging page being blank in chrome when I have adblock (ublock origin lite) enabled 😄 It works as expected with adblock disabled though.

**Comment by drizuid** [comment]
i use pihole, without making any adjustments to it, i can access the logging page fine

**Comment by Intenos** [comment]
I´m not aware of any ad-blocker and haven´t found one in the extensions. Anyhow, you might be right. On my mobile phone it shows up in Chrome. Thanks a lot for your support.
