### ISSUE TITLE
[FEAT] Add additional APKs as OCRmyPDF 

### ISSUE THREAD

**Issue by lodzen** [linuxserver/docker-nextcloud#407]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hello
is there a way to add additional APKs to the Nextcloud instance as OCRmyPDF?

### Reason for change

I need this to be able to run the OCR Workflow

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by lodzen** [comment]
Ok really easy, thank you got it working now
