### ISSUE TITLE
[BUG] Missing image for 27.1.5

### ISSUE THREAD

**Issue by bdcarr** [linuxserver/docker-nextcloud#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm pretty much having the exact same issue as #349, where the CLI updater brought me to a higher data version than the latest available 27.x Linuxserver container version. Same steps and behaviour, just a different 27.x version.

### Steps To Reproduce

Followed the steps [here](https://info.linuxserver.io/issues/2023-06-25-nextcloud/) to update from 24.x:
1. Updated to image version-24.0.12
2. Ran updater.phar repeatedly until the final update was from 26.0.10 -> 27.1.5
3. Updated to image version-27.0.0 and started the container
4. Got the error in the logs: "Can't start Nextcloud because the version of the data (27.1.5.1) is higher than the docker image version (27.0.0.8) and downgrading is not supported"
5. Updated to image version-27.1.4, same error just with a different image version

### Environment

```markdown
- OS: Raspberry Pi OS v12 64-bit 
- How docker service was installed: The script from get.docker.com
```

### CPU architecture

arm64

### Docker creation

docker-compose:
```bash
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:version-27.1.4
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /media/pi/storage/.config/nextcloud:/config
      - /media/pi/storage/data/nextcloud:/data
    depends_on:
      - mariadb
    restart: always
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
Can't start Nextcloud because the version of the data (27.1.5.1) is higher than the docker image version (27.1.4.1) and downgrading is not supported. Are you sure you have pulled the newest image version?
```

**Comment by Roxedus** [comment]
When 28 arrived, we stopped building 27 releases.

**Comment by bdcarr** [comment]
@Roxedus okay. Do you know how I can update from an older version then? Am I stuck unless I do a fresh install or something?

**Comment by Roxedus** [comment]
Tried lates?

**Comment by bdcarr** [comment]
Oh yeah! 27->28 is an allowed update. For some reason I was thinking I was still technically on 26 or something because it hadn't started up yet. Using a 28.x image seems to have worked, thank you very much.
