### ISSUE TITLE
[BUG] how can I build a newer nextcloud version since this docker donot follow the newest nextcloud version?

### ISSUE THREAD

**Issue by DingYuan0118** [linuxserver/docker-nextcloud#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

can only upgrade to 26.0.2. since there is not a 26.0.13 version docker
<img width="532" alt="image" src="https://github.com/linuxserver/docker-nextcloud/assets/42141845/cfeacbbc-c093-4b04-9bb9-5a8b7895943c">

### Expected Behavior

can upgrade to the newest support version

### Steps To Reproduce

1. doceker pull image
2. replace old image
3. upgrade nextcloud

### Environment

```markdown
- OS: debian PVE 5.19.17-2
- How docker service was installed: 
docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
nextcloud:
    image: linuxserver/nextcloud:26.0.1
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai

    volumes: 
      - /zfspool/AppData/NextCloud/config:/config
      - /zfspool/media/nextcloud/data:/data
    ports:
      - 10001:443
    expose:  
      - 80
```

### Container logs

```bash
no
```

**Comment by aptalca** [comment]
The newest version is 28.0.3 and we build that.
https://github.com/nextcloud/server/releases/tag/v28.0.3

What we don't build is patch releases for older versions.

You can always build them locally. Instructions are in the readme.
