### ISSUE TITLE
[FEAT] Add paxctl and set the correct flags on multiple binaries

### ISSUE THREAD

**Issue by thedeadliestcatch** [linuxserver/docker-nextcloud#429]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like paxctl to be added to the packages available in the image. This can enable some hardened environments to set the appropriate flags in multiple ELF files/executables.

Like so:

`RUN apk add --no-cache paxctl`

The end-user can then configure these as needed (ex. for PHP JIT you would need RUN paxctl -cm /usr/bin/php).

### Reason for change

Adds support for hardened environments that build/modify the image, without requiring external repository access.

### Proposed code change

In Dockerfile:

`RUN apk add --no-cache paxctl`

**Comment by aptalca** [comment]
I don't follow. What is adding `paxctl` supposed to accomplish by itself?
