### ISSUE TITLE
Unraid (current) update locked into maintenance mode. 

### ISSUE THREAD

**Issue by TheShillsYT** [linuxserver/docker-nextcloud#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

upon updating this using Unraid (current version) nextcloud no longer runs and I am locked into maintenance mode. It is late in the evening so I will gather better logs if this one posted below isn't the one needed in the AM, sorry. Just wanted to post in case it saves anyone from the loop I am in. 

### Expected Behavior

Was expecting a simple restart and it would work as before. 

### Steps To Reproduce

I can't do anything now as I will have to try and revert I think.

### Environment

```markdown
- OS:UnRaid Version: 6.12.6 
- How docker service was installed:using community applications built into Unraid.
```

### CPU architecture

x86-64

### Docker creation

```bash
was installed using the GUI for community applications.
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 28.0.4.1 (this can take a while) ...
Setting permissions
Initializing finished
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2024-01-03 │ 2024-04-02 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by WernerFettke** [comment]
I have the same issue, where you able to resolve it ?

**Comment by tatezach** [comment]
Happened to me by an update in the past, I think it was 28.0.3. Iwas able to resolve it by just deactivating maintenance mode via docker cli command. Did you try this?

**Comment by WernerFettke** [comment]
Hi,

Tried with the following:

root@UNRaid01:~# docker exec -it nextcloud occ maintenance:mode --off
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode already disabled

Got rid of the maintenance mode, however when I try run the upgrade I'm getting a malformed error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 11 database disk image is malformed

Tried running:
docker exec -it nextcloud occ maintenance:repair

However I get:

- ERROR: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 11 database disk image is malformed

I'm assuming I need to re-install ?

Thanks for your suggestion.

Werner

**Comment by ThElement12** [comment]
I have the same

**Comment by al73rus** [comment]
After todays update i got the same msg

**Comment by sf281** [comment]
I have the same issue... after updating nextcloud docker to 29.0.2 I either can't access or if I can only see Maintenance mode.

**Comment by J0hn-Lawrence** [comment]
I have the same issue. After updating (via unraid GUI) from 29.0.1.1 to 29.0.2.2 my instance is stuck. It is not reachable via web and seems to do nothing as CPU utilisation by the container is virtually 0%. 
The log shows the following:
`Initializing nextcloud 29.0.2.2 (this can take a while) ...
Upgrading nextcloud from 29.0.1.1 ...`
It does not go past this stage no matter how long I wait.

I checked the "config/www/nextcloud/config/config.php" file, but the maintenance parameter is set to false (in the past sometimes it got stuck in maintenance=true and changing it in this config file fixed the issue). I am not sure what could be the issue.

**Comment by J0hn-Lawrence** [comment]
> I have the same issue. After updating (via unraid GUI) from 29.0.1.1 to 29.0.2.2 my instance is stuck. It is not reachable via web and seems to do nothing as CPU utilisation by the container is virtually 0%. The log shows the following: `Initializing nextcloud 29.0.2.2 (this can take a while) ... Upgrading nextcloud from 29.0.1.1 ...` It does not go past this stage no matter how long I wait.
> 
> I checked the "config/www/nextcloud/config/config.php" file, but the maintenance parameter is set to false (in the past sometimes it got stuck in maintenance=true and changing it in this config file fixed the issue). I am not sure what could be the issue.

I was able to solve the problem by reinstalling the Nextcloud Docker container. I do not know what caused this upgrading issue.
