### ISSUE TITLE
[FEAT] Add python

### ISSUE THREAD

**Issue by ConfusedAlex** [linuxserver/docker-nextcloud#432]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would love to see python added to the docker image

### Reason for change

Nextcloud really adveritse with their local AI featues, but to use them Nextcloud needs python, which can't be found in the Docker Image.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by ConfusedAlex** [comment]
As is turn out, to use the large language models in Nextcloud you need to use x84, which is not supported with LSIO

**Comment by Roxedus** [comment]
You probably meant to write x86, which we do support. 

However, this image is using musl and glibc, which probably is the real reason.

**Comment by ConfusedAlex** [comment]
Oopsie yeah, as the app [readme states](https://github.com/nextcloud/llm), musl isn't supported
