### ISSUE TITLE
How to update to bugfix versions, no docker image provided for version 29.0.1

### ISSUE THREAD

**Issue by useross** [linuxserver/docker-nextcloud#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For a typical Nextcloud update, we usually should use `docker-compose pull` with `docker-compose up -d`. See [here](https://docs.linuxserver.io/images/docker-nextcloud/#updating-info).

Few days ago, i received an update notification from my Nextcloud server, for version `29.0.1`. The Nextcloud integrated updater seems to be enabled again (what was disabled in the past). I am also wondering, why there is no official Nextcloud version tag of Nextcloud itself for the bugfix-version `29.0.1`, and no docker image update provided by linuxserver.io. 

My question: Should we update trough the web-integrated updater instead of waiting for an updated docker-image?

### Steps To Reproduce

1. Open Nextcloud web interface as an admin and search for updates 
2. See version `29.0.1` is available (current used version is `29.0.0`)
3. But no docker image is available for the latest version

### Environment

```markdown
- OS:debian
- How docker service was installed:apt
```

### CPU architecture

x86-64

### Docker creation

```bash
--
```

### Container logs

```bash
--
```

**Comment by aptalca** [comment]
They did not release a stable 29.0.1 yet: 
https://github.com/nextcloud/server/releases

**Comment by useross** [comment]
Released from Nextcloud as well as linuxserver.io. Thanks!
