### ISSUE TITLE
Unable to establish TOTP.

### ISSUE THREAD

**Issue by Welved** [linuxserver/docker-nextcloud#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had to wipe my container because some instance breaking change I have made. Upon re-installation it's as if I have already established a TOTP. All that I am able to do is generate backup codes. There isn't a option to reset the TOTP or even establish it in the first place.

I've went through all the relevant forums and stumbled on this:
**docker exec -it -u www-data <nc container name> php occ twofactorauth:disable <uid of user> totp**

But, when I try it; it just gives me this error: 
**unable to find user www-data: no matching entries in passwd file**

### Expected Behavior

Get either a TOTP secret to input manually or scan the TOTP QR code to establish TOTP.

### Steps To Reproduce

1. Wipe and re-install Nextcloud.
2. Install Nextcloud as normal.
3. Go through the admin settings to the security tab.
4. Click the radio button to force 2FA.
5. Go to admin's personal settings to do a TOTP.
6. Only able to establish backup codes.

### Environment

```markdown
- OS: RaspberryPi4
- How docker service was installed: Can't recall.
```

### CPU architecture

arm64

### Docker creation

```bash
Used portianer to pull from docker hub and followed the configuration that is laid out on the linuxserver docker hub documentation.
```

### Container logs

```bash
Setting resolver to  192.168.x.x
Setting worker_processes to 4
generating self-signed keys in /config/keys, you can replace these with your own keys if required
[KEY]
Initializing nextcloud 29.0.3.4 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by drizuid** [comment]
i suggest coming on discord for support, however, note that we do not support deploying our container with portainer or other UIs.
