### ISSUE TITLE
[FEAT] Fulfill apple cert requirements

### ISSUE THREAD

**Issue by mgerhardy** [linuxserver/docker-nextcloud#461]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be great to fulfill apple cert requirements (https://support.apple.com/en-us/103769)

It would also be cool to create a self signed CA to generate the self signed certs from. As the CA validity can be longer than 365 days - so using the 3650 might work here. Now you only have to import the PEM of the root cert in your phone once (hopefully) - otherwise you would have to re-import the PEM every year (the max allowed cert validity is 365 days for).

### Reason for change

Nextcloud CalDAV and CardDAV require TLS (since iOS12 afair) - but the default self-signed certs just don't fit the apple requirements.

**Comment by Roxedus** [comment]
This is not made to be exposed directly on the internet, these requirements should be filled by your reverse proxy.

**Comment by mgerhardy** [comment]
Of course not - that's why I use a self-signed cert ;)

The nextcloud instance is only available in the intranet - but my Apple devices are still not able to connect to the addressbook or calendar - because even self-signed certs have to fulfill those guidelines mentioned above.

And having a cert that is allowed to be valid at most 365 days is a hassle when you have to import the new cert on all devices after a year. That's why I proposed to create a CA and then create the 365-days-valid-certs from that CA. This should (??) allow us to only import the CA once (hopefully) and not every year (even though that would be sugar already - being able to just use the local intranet nextcloud instance with Apple devices would already be great on its own)

**Comment by j0nnymoe** [comment]
This sounds like a niche requirement and outside the scope of this container. If you're needing your own CA and creating your own self signed certs, you can easily import those certs into this container.

**Comment by aptalca** [comment]
You can use a reverse proxy with a 3rd party validated cert for intranet access only. SWAG allows for it with dns validation. That's the recommended and supported method. 

We don't recommend or support using a self signed cert in production. It is there for initial setup and troubleshooting.

If you really want to go down the self signed path, you can replace the cert we include with whatever cert you like. It's in the config folder.
