### ISSUE TITLE
Cannot start the docker after updating it, in CasaOS

### ISSUE THREAD

**Issue by gcorucci** [linuxserver/docker-nextcloud#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, thank you very much for your docker.
I have just updated from CasaOS the Nextcloud docker, and unfortunately, even after the rebooting of the server, it won't start.
I am not very sure what the issue could be. Have you by any chance had similar issues?
Thank you very much and have a nice day,
Giacomo Corucci.

### Steps To Reproduce

The settings that I currently use for nextcloud in CasaOS are the following:
tag: 29.0.0 (stable)
docker image: nextcloud
port: 10081
HOST: 10081 container: 80
HOST: 10443 container: 443

### Environment

```markdown
- OS:linux, CasaOS
- How docker service was installed: through the app store of CasaOS
```

### CPU architecture

x86-64

### Docker creation

```bash
The settings are displayed in the section "steps to reproduce"
```

### Container logs

```bash
{"reqId":"6l79KPzxT7j1iXzEosWx","level":2,"time":"2024-08-05T12:27:00+00:00","remoteAddr":"172.22.197.243","user":"Aprile-Lab","app":"no app in context","method":"GET","url":"/cor\
e/preview?fileId=3116&c=775490d225b6092949edb5ebbe0c970d&x=250&y=250&forceIcon=0&a=1","message":"Host 172.22.197.180 was not connected to because it violates local access rules","\
userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36","version":"27.1.3.2","data":[]}
{"reqId":"T7jspm0lirfSVfZY5EII","level":3,"time":"2024-08-05T12:37:27+00:00","remoteAddr":"172.22.197.243","user":"Aprile-Lab","app":"PHP","method":"POST","url":"/remote.php/dav/b\
ulk","message":"file_put_contents(/var/www/html/data/Aprile-Lab/files/Documents/Giacomo/ParD/Libraries_updater/downloadPDB/.listing): Failed to open stream: Permission denied at /\
var/www/html/lib/private/Files/Storage/Local.php#313","userAgent":"Mozilla/5.0 (Linux) mirall/3.10.1 (build 18410) (Nextcloud, ubuntu-6.5.0-45-generic ClientArchitecture: x86_64 O\
sArchitecture: x86_64)","version":"27.1.3.2","data":{"app":"PHP"}}
{"reqId":"T7jspm0lirfSVfZY5EII","level":3,"time":"2024-08-05T12:37:27+00:00","remoteAddr":"172.22.197.243","user":"Aprile-Lab","app":"no app in context","method":"POST","url":"/re\
mote.php/dav/bulk","message":"Could not create path \"/Aprile-Lab/files/Documents/Giacomo/ParD/Libraries_updater/downloadPDB/.listing\"","userAgent":"Mozilla/5.0 (Linux) mirall/3.\
10.1 (build 18410) (Nextcloud, ubuntu-6.5.0-45-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"27.1.3.2","data":{"path":"/Documents/Giacomo/ParD/Libraries_u\
pdater/downloadPDB/.listing"}
```

**Comment by Roxedus** [comment]
These are not complete container logs

**Comment by gcorucci** [comment]
Hi Roxedus, thanks for your quick reply. I copied the last few lines of the file "nextcloud.log" within the nextcloud home directory. Where can I find a more detailed log file?

Thank you very much.

**Comment by Roxedus** [comment]
Those are not container logs, they would be application logs

**Comment by gcorucci** [comment]
Thank you. If helps I just run the command "docker logs nextcloud" and this is the result:
"Initializing nextcloud 29.0.0.19 ...
Can't start Nextcloud because upgrading from 27.1.3.2 to 29.0.0.19 is not supported.
It is only possible to upgrade one major version at a time. For example, if you want to upgrade from version 14 to 16, you will have to upgrade from version 14 to 15, then from 15 to 16."

So I guess the issue is that I updated from 14 to 16 and I should have done it step by step.
How can I solve the issue? Do I need to reinstall it or is there another way to do it?

Thank you very much Roxedus for your help.

**Comment by Roxedus** [comment]
Grab a tag for 28, and let it upgrade.

**Comment by gcorucci** [comment]
Thank you very much for your reply. I'm not really expert in this and my question is surely stupid!
How can I do it? Do I need to pull the version like this: "docker pull nextcloud:28" ?
Where I can find this version? Do I need to download it first? Now if I type the command these versions appear in the terminal:
27.0.0
27.1.3
29.0.0
29.0.4

Thank you so much.

**Comment by Roxedus** [comment]
The tags are on dockerhub https://hub.docker.com/r/linuxserver/nextcloud/tags?page=&page_size=&ordering=&name=version-28

**Comment by gcorucci** [comment]
Hi Roxedus, thank you very much for your reply and link, I successfully updated nextcloud.

Thank you once again and have a nice day.
