### ISSUE TITLE
[BUG] Issue with Real IP when using Cloudflared Tunnel and a Proxy Service

### ISSUE THREAD

**Issue by NoobOfAll** [linuxserver/docker-nextcloud#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The reported IP shows either the internal Proxy IP as the access IP or the Tunnel IP as the access IP

### Expected Behavior

The final User IP should be visible

### Steps To Reproduce

Use cloudlfared Tunnel to connect to a Reverse Proxy which sends the connection to Nextcloud

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Regular setup, nothing complicated
```

### Container logs

```bash
Not really Needed, just checking the access log works, since I have solved the issue, logs wont help anymore, but not confident with my solution, I am submitting a bug with my solution, so that if it makes sense, you can make the update
```

**Comment by NoobOfAll** [comment]
# MY Solution
## NGINX Site conf
> Nextcloud/config/nginx/site-confs/default.conf
```conf  
    # display real ip in nginx logs when connected through reverse proxy via docker network
    set_real_ip_from 172.28.1.254;
    set_real_ip_from 192.168.0.101;    
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
```
The last line is needed for multiple IPs to be considered as internal IPs

**Comment by NoobOfAll** [comment]
# MY Solution
## NGINX Site conf
> Nextcloud/config/nginx/site-confs/default.conf
```conf  
    # display real ip in nginx logs when connected through reverse proxy via docker network
    set_real_ip_from 172.28.1.24;
    set_real_ip_from 192.168.0.10;    
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
```
The last line is needed for multiple IPs to be considered as internal IPs

**Comment by drizuid** [comment]
OP wrote their solution which will suffice, but i will note that putting our containers through cf tunnels, vpns, or proxy services are out of scope for us. Presumably you need the cloudflare real ip mod.. Closing this as out of scope for support.
