### ISSUE TITLE
Crons stopped worked after updating Nextcloud

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-nextcloud#48]
After updating Nextcloud to the latest stable (12.0.4) 4 days ago, I've just noticed `Background jobs  Last job execution ran 4 days ago. Something seems wrong.` in the admin panel. Any ideas?

**Comment by thelamer** [comment]
This issue is extremely old and I want to personally apologize for no one on the team getting back to you in a timely manner. 

I will be closing this issue as their have been many changes to this image since this was filed, and as far as I can tell cron is fully functional.
