### ISSUE TITLE
Is there a way to straight up get rid of maintenance mode?

### ISSUE THREAD

**Issue by Welved** [linuxserver/docker-nextcloud#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once in some blue moon my nextcloud decides to flip to maintenance mode. All the previous versions of Nextcloud (Server/Docker) all I had to do was stop the container and go into www/config.php to modify a line.

Now, if I go and modify that line and restart the container; nextcloud flips maintenance mode back on without any input.

This is honestly driving me insane. I've tried all the forum solutions that are available, none of them work for this version of Nextcloud.

Is there a way to straight up remove this maintenance mode? It is causing me more problems that it solves. I am currently wiping my entire container and setting it up as new.

Every time Nextcloud decides to go into maintenance mode... unfortunately I am having to wipe the container.

### Expected Behavior

Be able to use my containers as I see fit.

### Steps To Reproduce

1. Take my external storage medium containing all my containers and move them to a different machine.
2. Proceed to re-establish containers.
3. Be met with "maintanance mode" being turned on without any input or consent.

### Environment

```markdown
- OS: Ubuntu 24.04 Raspberry Pi5
- How docker service was installed:
sudo curl -sSL https://get.docker.com | sh
```

### CPU architecture

arm64

### Docker creation

```bash
hub.docker.com
portainer pull linuxserver/nextcloud
```

### Container logs

```bash
Irrelevant. I wiped my entire container.
```

**Comment by aptalca** [comment]
It's part of Nextcloud's update mechanism, which gets triggered when you recreate the container with an image that contains an updated Nextcloud version.
