### ISSUE TITLE
Uploading large files fails

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-nextcloud#52]
Uploading large files fails with
```
172.17.0.1 - aaxjDd3W5Dkn8xm [22/Mar/2018:19:18:19 +0200] "PUT /public.php/webdav/PSC_1718_PMW2_1777.MXF HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"

172.17.0.1 - aaxjDd3W5Dkn8xm [22/Mar/2018:19:31:10 +0200] "PUT /public.php/webdav/PSC_1718_PMW2_1777.MXF HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
```

PHP upload limit is set to 128GB and file-size is 20GB. Nothing in the error or `nextcloud.log` files. What can be done to aid this?

**Comment by thelamer** [comment]
We set the default size limit to 512MB in the php.ini, any modification to this and resulting errors you would need to direct those questions to the NextCloud team.

**Comment by thelamer** [comment]
Sorry I spoke too soon, working late and trying to close out old issues. 

There is a directive capping the body size to 10 gigs here: 

https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/default#L33

In your config folder you can modify this: 

```
/config/nginx/site-confs/default
```

**Comment by JendrikDerWeise** [comment]
Hi, I still have this issue after changing every nginx.conf and default file I could find. Also I changed .htaccess and .user.ini - NC shows me in Settings/PHP my chosen max upload value but my Windows client still tells me 413 Error. I really don´t know what to try next. Maybe any idea on your side?
Upload big files on http is working, just the client throws the error.

**Comment by wmutschl** [comment]
For me it helped to set
```
client_max_body_size 0;
```
in `/config/nginx/site-confs/default`.

**Comment by wmutschl** [comment]
Note that when using the official sync client one typically does not run into this issue of not being able to upload large files, because the sync client uploads it in chunks (correct me if I am wrong). At least for me, this happens only if I upload directly via WebDAV.

**Comment by edricus** [comment]
> For me it helped to set
> 
> ```
> client_max_body_size 0;
> ```
> 
> in `/config/nginx/site-confs/default`. Don't forget to restart the container!

still doesn't work on 28.0.4 trying to upload with the web gui...
