### ISSUE TITLE
Not able to logout

### ISSUE THREAD

**Issue by UniverseXXX** [linuxserver/docker-nextcloud#53]
Hi,
I'm using your container together with official nginx container which working as a reverse proxy. I'm having the above issue (after clicking on logout i'm being diverted to the Files page) when I'm accessing Nextcloud from outside of the local network. However, it's working perfectly fine when i'm accessing via local network. Could you please advise if I have to add something to my nginx container configuration?

Nginx container configuration (part for the NextCloud server):
```
server
	{
		listen 443 ssl http2;
		server_name nc.xxxx.com;

		add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
		add_header X-Content-Type-Options nosniff;
		add_header X-Frame-Options "SAMEORIGIN";
		add_header X-XSS-Protection "1; mode=block";
		add_header X-Robots-Tag none;
		add_header X-Download-Options noopen;
		add_header X-Permitted-Cross-Domain-Policies none;
	
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;

		location / {
    		proxy_pass https://172.17.0.1:8000;
			http2_push_preload on;
			auth_basic "Restricted";
			auth_basic_user_file  /config/.htpasswd;
		}
	}
```
Thank you.

**Comment by tobbenb** [comment]
Have a look at this guide to see if you get it working: [https://www.linuxserver.io/2017/05/10/installing-nextcloud-on-unraid-with-letsencrypt-reverse-proxy/](https://www.linuxserver.io/2017/05/10/installing-nextcloud-on-unraid-with-letsencrypt-reverse-proxy/)

**Comment by UniverseXXX** [comment]
Thanks @tobbenb 
I was able to "fix" it by adding 2-factor authentication. However, I'm now not able to login via iOS app using generated password, getting 401 error. Will continue digging.
