### ISSUE TITLE
after 05.09.2018 UPDATE => ***This version of Nextcloud is not compatible with PHP 7.2.***

### ISSUE THREAD

**Issue by DrMythnick** [linuxserver/docker-nextcloud#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 unraid

***
Hi,
I don't run any special settings on this docker container, just the path for the /data .
***

> This version of Nextcloud is not compatible with PHP 7.2.
You are currently running 7.2.8.

**Comment by sparklyballs** [comment]
what version of nextcloud ? 

the app files themselves don't get updated with a new image, so if you have an old version you may need to update it.

**Comment by DrMythnick** [comment]
Version: Nextcloud 12.0.2

i ran an older docker release 140 and after updating the app manually from occ to 13.0.6, updated to the new docker release 143 and it is working ok.

regards,

**Comment by sparklyballs** [comment]
cool, glad it works now.

closing this.
