### ISSUE TITLE
Update results in next cloud not loading due to PHP fatal error

### ISSUE THREAD

**Issue by Aterfax** [linuxserver/docker-nextcloud#60]
Recent update results in white blank page on load with the following fatal error message in Nginx error.log

`
2018/09/11 16:14:23 [error] 307#307: *151 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of OC\Files\Storage\Local::copyFromStorage(OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OC\Files\Storage\Common::copyFromStorage(OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime = false) in /config/www/nextcloud/lib/private/Files/Storage/Local.php on line 44" while reading response header from upstream, client: 192.168.2.2, server: _, request: "GET /index.php/login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.10.3:8000", referrer: ""`

Error may be related to:   https://github.com/nextcloud/server/pull/5072

	

OS:  Unraid_ 6.5.3

**Comment by Aterfax** [comment]
Found a solution here  and leaving this open for investigation:

https://github.com/nextcloud/server/issues/9588#issuecomment-394061799

**Comment by Aterfax** [comment]
Think this might be related to the docker image updating to use PHP 7.2 while the Nextcloud App was still in version 12. 

Closing unless someone can reproduce in PHP 7.1 + NextCloud 12
or PHP 7.2 + NextCloud 13.

**Comment by tomchiverton** [comment]
This occurs on a fresh install on Fedora 29, with their Nextcloud package during install :


# sudo -u apache php occ maintenance:install --data-dir /var/lib/nextcloud/data/ --database "mysql" --database-name "nextcloud"  --database-user "nextcloud" --database-pass "..." --admin-user "nextcloud_admin" --admin-pass "notqaz" --database-host 127.0.0.1
Nextcloud is not installed - only a limited number of commands are available
PHP Fatal error:  Declaration of OC\Files\Storage\Local::copyFromStorage(OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OC\Files\Storage\Common::copyFromStorage(OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime = false) in /usr/share/nextcloud/lib/private/Files/Storage/Local.php on line 43

**Comment by sparklyballs** [comment]
@tomchiverton 

3 things....

1. you've commented on a closed issue with something not related to the original issue.
2. the user for our nextcloud image is abc, not apache
3. and if you're using our image, we don't have mysql/mariadb installed so localhost/127.0.0.1 is not going to work for connecting to a database..

**Comment by tomchiverton** [comment]
I won't bother helping then.

**Comment by sparklyballs** [comment]
@tomchiverton are you even using our docker image ?
