### ISSUE TITLE
Using wrong PHP version - 7.2.8 in use, needs PHP (>= 5.6, 7.0 or 7.1)

### ISSUE THREAD

**Issue by Aterfax** [linuxserver/docker-nextcloud#61]
Project needs rebasing to a supported PHP version, as detailed here: https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html

![image](https://user-images.githubusercontent.com/8648058/45582344-db1c9c00-b8a5-11e8-947b-a92512ef54d2.png)

The usage of PHP 7.2 is causing errors:

Error | PHP | Function create_function() is deprecated at /config/www/nextcloud/lib/private/Route/Route.php#155 | 2018-09-15T05:03:16+0100
-- | -- | -- | --

As explained further here:
https://github.com/nextcloud/server/issues/6882#issuecomment-338602433

PHP version therefore needs changing.

**Comment by aptalca** [comment]
You need to update your nextcloud

**Comment by Aterfax** [comment]
Not according to my dash:

![image](https://user-images.githubusercontent.com/8648058/45582791-102cec80-b8ae-11e8-9fb6-6ca917e61796.png)

**Comment by aptalca** [comment]
Not the image, the app

**Comment by Aterfax** [comment]
That isn't relevant to the docker being mis-configured and deploying the incorrect version of PHP (or the wrong version of Nextcloud depending on your point of view.)

**Comment by Aterfax** [comment]
Internal NextCloud updater was getting stuck on an extra file being present:

> The following extra files have been found:
.rnd

No idea why this file is there or when it arrived but that would be a cause of desync in updates.

I was under the impression that this docker would keep NextCloud up to date of its own accord rather than require manual user input?

**Comment by j0nnymoe** [comment]
Nope, this is one of few containers we do that needs to be updated manually. See the first post on the unraid support thread https://forums.unraid.net/topic/48383-support-linuxserverio-nextcloud/

**Comment by Aterfax** [comment]
Well, that'd be why its desync'd then.

Might have been an idea to stick with 7.1 for forward/backward compat but that's a bit late now.

Might be an idea to note for future re-basing to try to retain a solution that works for both?

I have no explanation for that random extra file mind you locking the Nextcloud updater but since that is a simple file removal its not worth another ticket.

**Comment by thelamer** [comment]
I have tested all trees of upgrading with success on our latest image. 
I have dived deep into this container and Nextclouds offering. Ours will likely never be perfectly in sync from a php version standpoint. We will always use the system packages provided by Alpine. 

Their update method in Docker is Unique and is kicked off by updating the base image with locks in place to ensure you cannot update from the WebUI. 

I am picking up what you are laying down regarding keeping this up to date from major version changes as you may get stuck on an old version, but I do not see a solution to this problem that we can implement in our container as we have no input into their codebase.
