### ISSUE TITLE
Increase PHP memory limit to 512MB

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-nextcloud#63]
Calling `occ` says that `The current PHP memory limit is below the recommended value of 512MB`. Appending `memory_limit = 512M` to `php-local.ini` fixes this.

**Comment by wecanfuture** [comment]
Appended it in 14.0.4 version. Still getting the warning. 
The current PHP memory limit is below the recommended value of 512MB.

**Comment by alex-phillips** [comment]
This is done: https://github.com/linuxserver/docker-nextcloud/pull/72
