### ISSUE TITLE
Unable to install imagick

### ISSUE THREAD

**Issue by vafanassieff** [linuxserver/docker-nextcloud#64]
Hello,

Thanks for your nice container shipped with smb support but i'm to the docker universe and PHP and  i can't find a way to install imagick extension in the container to use this nextcloud extension [Camera RAW Previews](https://github.com/cowai/camerarawpreviews)

Maybe i missed something but after some long hours of googling my issue i've done nothing, i'm stuck with answer where you have to use apt-get and pecl, which are not in the container.

Cheers.

**Comment by aptalca** [comment]
It's alpine based so you need to use `apk add --no-cache <package>`

**Comment by Dulanic** [comment]
I've been trying to install imagick myself and havent been successful. Is it possible to add a ENV variable to auto install this? This is a very useful extension for speed and raw camera files.

https://github.com/docker-library/php/issues/105

**Comment by thelamer** [comment]
We install imagemagick and php7-imagick in this container . They are both enabled and functional.
