### ISSUE TITLE
SSL should be optional.

### ISSUE THREAD

**Issue by lukasmrtvy** [linuxserver/docker-nextcloud#65]
SSL should be optional. There is no point to double SSL offloading (more performance impact), In case if You want to use custom reverse proxy like Traefik, etc. 
Most users will run this on localhost even with reverse proxy anyway. 

For example:
```
docker run -e DONT_USE_SSL=true linuxserver/docker-nextcloud
```
```
if [ "${DONT_USE_SSL,,}" == true ];then
   rm -rf ..../default_https
else
   rm -rf ..../default_http
fi
```
`default_http` should contain nginx config for http listerner only
`default_https` should contain nginx config for http(redirect)->https(SSL)

https://github.com/linuxserver/docker-baseimage-alpine-nginx should be edited for /default_https and /default_http

**Comment by bliekp** [comment]
+1

**Comment by sparklyballs** [comment]
it is optional...


just edit the default file in the mounted volume......

**Comment by bliekp** [comment]
Pity you close this. Editing the default file is a hack IMHO. A more elegant solution would be preferable.

**Comment by aptalca** [comment]
OP's solution would break all other downstream images based on the nginx baseimage.

Also, reverse proxying nextcloud already requires editing other files. Editing one more is no different.

**Comment by lukasmrtvy** [comment]
This image is bad by design anyway. 
Additional edit inside container / volume to configure application is anti-pattern in this case.

**Comment by aptalca** [comment]
I honestly can't tell if you're being sarcastic or just defensive because I said your solution would break a lot of things.

Nextcloud config files are meant to be user edited even with an official install on a supported os. 

By default, this image works through 443 with ssl for security reasons. If you want to change that behavior or reverse proxy it via http, you can do so by editing the files that are conveniently placed in the persistent path labeled "config". 

If you're not happy with that, feel free to fork it or use a different image. That's the beauty of open source. No need to call our hard (volunteer) work "bad"

**Comment by timothystewart6** [comment]
Can someone please give an example?  I have been trying to disable ssl redirect in `site-conf/default` and nothing seems to work.  When switching the containers port to 80 instead of 443 it doesn't respond.

**Comment by lbischof** [comment]
@timothystewart6 Replace `listen 443 ssl;` with `listen 443;`

**Comment by lukasmrtvy** [comment]
> OP's solution would break all other downstream images based on the nginx baseimage.
> 
> Also, reverse proxying nextcloud already requires editing other files. Editing one more is no different.



@aptalca  Of course it will not break downstream images....
## Add nginx configs - for HTTP and HTTPS
https://github.com/lukasmrtvy/lsiobase-aria2-webui/tree/master/root/defaults
## Add cont-init config 
https://github.com/lukasmrtvy/lsiobase-aria2-webui/blob/master/root/etc/cont-init.d/19-config
## Run image with `-e SKIP_SSL=true`

**Comment by timdonovanuk** [comment]
> @timothystewart6 Replace `listen 443 ssl;` with `listen 443;`

This works but breaks login. Just a spinning wheel. Nothing in logs.

Webdav still works fine though so...yey?
