### ISSUE TITLE
Is binlog format still relevant?

### ISSUE THREAD

**Issue by Ryonez** [linuxserver/docker-nextcloud#67]
Looking at the readme, the following is mentioned:

> Please note you will need a MySQL/MariaDB or other backend database to set this up.  Also please look [here](https://docs.nextcloud.com/server/11/admin_manual/installation/system_requirements.html#database-requirements-for-mysql-mariadb) for how to configure your database with regard to binlog format and installation.

This links to a guide that's for Nextcloud 11 (Current is 14). I note this guide also shows you how to enable Emoji (UTF8 4-byte) support with MySQL / MariaDB. I had major issues with this with the MariDB docker (See: https://github.com/linuxserver/docker-mariadb/issues/22). A title change by @sparklyballs suggests this is actually considered experimental.

So I'm checking is to see if the documentation is out of date. I have already followed the guide for changing the binlog format, and now I'm wondering if I should revert/restart the database. At the moment I wouldn't face major loss, as I'm having other issues at present as well.

**Comment by thelamer** [comment]
No with this project now at version 15 none of this information is relevant. I will earmark this for changes, especially because in most scenarios for basic home usage the sqlite default is just fine.

**Comment by thelamer** [comment]
@Ryonez thanks for the report, we will pull this info out when this is merged https://github.com/linuxserver/docker-nextcloud/pull/88

**Comment by Ryonez** [comment]
All good, though I'm still curious about those of use who do use external databases.

**Comment by thelamer** [comment]
These are the current requirements: 
https://docs.nextcloud.com/server/15/admin_manual/installation/system_requirements.html#database-requirements-for-mysql-mariadb
