### ISSUE TITLE
Expose www.conf to config volume

### ISSUE THREAD

**Issue by rcdailey** [linuxserver/docker-nextcloud#68]
Per the [server tuning](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/server_tuning.html) guide for Nextcloud, this requires access to the following file inside the container:

```
/etc/php7/php-fpm.d/www.conf
```

However, there is no way to override this configuration from the `/config` volume. Please add a way to specify this configuration from the mounted volume for more control over the performance of Nextcloud.

**Comment by tobbenb** [comment]
You can use a volume mount for that file only.

**Comment by LeoVerto** [comment]
You can already edit `/config/php/www2.conf` to overwrite values in `www.conf` and `php-fpm.conf`.
