### ISSUE TITLE
[Request] Make the `php occ` tool available to configure Nextcloud.

### ISSUE THREAD

**Issue by hitech95** [linuxserver/docker-nextcloud#69]
I'm new on Docker containers, this is the first time that I use Docker so I don't have much experience.
Lots of stuff is done by using the occ tool in the Nextcloud install dir. I tried to get a shell but the `docker attach` command doesn't do what I expected.

I also tried the command `docker exec -it <id> bash` but in this case, I cannot run the command due to the fact that I'm not user `abc`.

Is this a bug, my fault or a missing feature of this docker?

**Comment by aptalca** [comment]
What exactly are you trying to do?

**Comment by tobbenb** [comment]
You can use `docker exec -it -u abc <id> bash` to use the abc user.

**Comment by hitech95** [comment]
> 
> 
> You can use `docker exec -it -u abc <id> bash` to use the abc user.

This looks fine, thanks! I'm a noob with Docker.
