### ISSUE TITLE
Mobile App Timeout issues. Nothing is syncing or saving. 

### ISSUE THREAD

**Issue by RussellG89** [linuxserver/docker-nextcloud#70]
Only on mobile app, I am seeing timeout issues and the following in the screenshot. I have 0 errors using desktop app or web gui on laptop/PC. 

![img_2206](https://user-images.githubusercontent.com/20692895/49111263-9b870e80-f25d-11e8-8610-d40df0e2e7f9.jpg)

 

Running unRAID.

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing...
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing...
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
(Nothing past this since started up)

Just have linuxserver mariadb and letsencrypt containers running. Nothing else.

**Comment by tobbenb** [comment]
If it's working from the desktop app and browser, it's almost certain the phone app.

**Comment by michitux** [comment]
I had the same issue, no files were showing up in the mobile app. I solved it by replacing all location rules in the nginx configuration by the corresponding parts of the nginx configuration from the [manual](https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html). I don't know what particular part was the issue though. I noticed that the file included in this docker image contains special rules for `remote.php` which are not present in the configuration from the manual. Possibly that's the issue?

**Comment by homerr** [comment]
@michitux pull from latest, see if the changes made have resolved your issue.

**Comment by thelamer** [comment]
@michitux these commands should get you sorted : 

```
rm -f /path/to/your/config/nginx/site-confs/default
sudo docker run --rm \
-v /var/run/docker.sock:/var/run/docker.sock taisun/updater \
--oneshot nextcloud
```
Please let us know if this is working the the latest container and Nginx Config.

**Comment by homerr** [comment]
Hoping the above resolved your issue, if not please join Discord and somebody should be able to assist further.
