### ISSUE TITLE
Need Nextcloud + MariaDb + Airsonic + LetsEncrypt docker-compose.yaml, please

### ISSUE THREAD

**Issue by qwertyuser1983** [linuxserver/docker-nextcloud#74]
I have been trying to "migrate" from Nextcloud Snap with LetsEncrypt + Ampache setup wth no avail. My current setup is a modified methods from https://arielelkin.github.io/articles/easily-sync-and-stream-your-entire-music-collection-using-docker.html (please see my comment there).

I have said migrate, but in reality, I am starting from blank data.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

I have tried a modification from https://blog.linuxserver.io/2017/05/10/installing-nextcloud-on-unraid-with-letsencrypt-reverse-proxy/ with no avail. :(

An example docker-compose.yaml file with tutorial for Nextcloud + MariaDB + LetsEncrypt, preferably including AirSonic would be highly appreciated.

Renan

**Comment by aptalca** [comment]
you're better off using our discord for this: https://discord.gg/YWrKVTn
