### ISSUE TITLE
Update to 15.0.2?

### ISSUE THREAD

**Issue by kohlsalem** [linuxserver/docker-nextcloud#79]
Dear linuxxerver team, 

I just  noticed, that my nextcloud image was from april last year. After pulling a new one, it is version 13.0.1.

Iooking at nextcloud homepage, current stable version is 15.0.2.

Are there any plans to upgrade the version?

Thanks 
Michael

**Comment by tobbenb** [comment]
You have to update nextcloud manually. Instructions are in the Readme.
Nextcloud is only installed during first run of this container. After this you need to pull a fresh image and then update nextcloud as per the Readme.
