### ISSUE TITLE
Include upstream nginx improvements

### ISSUE THREAD

**Issue by neersighted** [linuxserver/docker-nextcloud#8]
https://docs.nextcloud.com/server/9/admin_manual/installation/nginx_nextcloud_9x.html

The upstream developers have published an example config (which this repos appears to be derived from) with some improvements, such as 'index.php-less' URLs among other things.

It'd be nice to see this improvements incorporated into the default nginx config (I can provide my merged version if you'd like as well).

**Comment by j0nnymoe** [comment]
Hi neersighted, Please could you provide a PR for this and we will look into it.

Thanks

**Comment by j0nnymoe** [comment]
Closing issue as no update on this for issue for over a month.
Please re-open if needed.

**Comment by djmattyg007** [comment]
If this is included in a PHP block:

    fastcgi_param front_controller_active true;

NextCloud will automatically use "pretty URLs" (URLs without `index.php` in them). This would be desirable to have out of the box.
