### ISSUE TITLE
Avatar generation does not work 

### ISSUE THREAD

**Issue by realies** [linuxserver/docker-nextcloud#81]
Using latest stable Nextcloud with the latest container image and upon creation, user avatars look like

![image](https://user-images.githubusercontent.com/5107843/52178982-7672c700-27dd-11e9-8363-1f355bb60b21.png)

Nothing related in the logging section of Nextcloud

**Comment by ajayramaswamy** [comment]
I had the same thing happen to me, and I fixed it by using the nginx config from nextcloud.com, over time the location setting for various bits have changed

**Comment by thelamer** [comment]
@ajayramaswamy can you post a working config, I just tried out their current one with some slight pathing mods and I get the same results as @realies

**Comment by ajayramaswamy** [comment]
https://paste.fedoraproject.org/paste/6iuFD-sWrndENZg5QsUq~g

or

https://paste.fedoraproject.org/paste/hRh5TAxKK3ayQoJheCAXoA

**Comment by thelamer** [comment]
@ajayramaswamy thanks for the info, will get this tested.

**Comment by thelamer** [comment]
@ajayramaswamy I still get the error with these configs, and there is nothing logged. Are you sure you made no other modifications ?

**Comment by ajayramaswamy** [comment]
You will have to comment out access_log off; on lines 142, 148 etc to see logs

if the avatar is there then the log entry will look like this

"GET /nextcloud/remote.php/dav/avatars/myusername/128.png HTTP/2.0" 200 1194

so the next point of debugging s to see if the file exists at that path

**Comment by thelamer** [comment]
@ajayramaswamy files are present and I have logs enabled across the board. It is just that the files look like they are reported in this issue, tiny white box and a background. 

Makes me think we are missing some kind of image manipulation dependency. Do yours look normal?

**Comment by homerr** [comment]
Hi @ajayramaswamy could you update this please

**Comment by thelamer** [comment]
I have dug deep into this and I am unable to find a solution, the only difference between our env and the official container with the most recent modification I made here  https://github.com/linuxserver/docker-nextcloud/pull/87 is dependency versions. This might simply be a side effect of using Alpine system packages for PHP and its deps.

**Comment by neckos** [comment]
I have the same issue on Alpine.

**Comment by CHBMB** [comment]
@thelamer Looks like the issue has been found by another Nextcloud container author.

https://github.com/crazy-max/docker-nextcloud/blob/363005714646a29bea09405371d59915ff8cd0d2/Dockerfile-13#L69-L71

**Comment by thelamer** [comment]
Yeah just tested GD from edge locally to confirm, it looks like v16 fixes this upstream so when we have a new version we can close this out.

**Comment by CHBMB** [comment]
They're already on [RC2](https://github.com/nextcloud/server/releases) so I agree we might as well wait for upstream fix.

**Comment by thelamer** [comment]
This is fixed in ```linuxserver/nextcloud:16.0.0-ls17```
