### ISSUE TITLE
Safety and facility warnings 

### ISSUE THREAD

**Issue by taobyebye** [linuxserver/docker-nextcloud#84]
Nextcloud indicates to me:
"There are some warnings with your system configuration.

Some columns in the database are not converted to big int. Due to the fact that changing column types for large tables can take some time, they were not changed automatically. By executing "occ db:convert-filecache-bigint"; these outstanding changes can be applied manually. This operation must be performed while the instance is offline. Further details can be found on the corresponding documentation page.
filecache. mtime
filecache. storage_mtime
The "referrer policy"; HTTP header is not set to &quot;no-referrer";, "no-referrer-when-downgrade";, "strict-origin";, "strict-origin-when-cross-origin"; or "same-origin";. This allows reference information to be disclosed. See the W3C recommendation.

Please review the installation instructions ? and check the log for possible errors or warnings.

Check the security of your Nextcloud with our security scanner ?. ."

**Comment by homerr** [comment]
@alex-phillips I think this may be better documented than added as any change?

**Comment by thelamer** [comment]
@taobyebye the changes you need to perform are documented with links from those messages. So in this case you would exec into the container : 
```
docker exec -it nextcloud bash
```
then you would run:
```
sudo -u abc php occ db:convert-filecache-bigint
```

As far as HSTS and other warnings we will be making some changes to the nginx config to bring it in line with v15 of Nextcloud. 

I want to point out though that server hardening an application is not really something we should be covering in our documentation given the extremely dynamic nature of it and our lack of control into Nextclouds checks. 

We will make every effort to ensure that the defaults we put into the container are as up to date and secure as possible.
