### ISSUE TITLE
Bug with php7.2

### ISSUE THREAD

**Issue by tjaadvd** [linuxserver/docker-nextcloud#89]
When I do a clean create of a container I run into an error, which is presumably this: https://github.com/nextcloud/server/issues/7410. It has to do with PHP7.2 not being supported yet?

**Comment by tjaadvd** [comment]
I've to create a container more recently and I didn't had the issue that I listed above. The issue may be closed.

**Comment by dlecan** [comment]
I have the same issue with a fresh install of Linuxserver Nextcloud.
Context:
- raspberrypios 32bits armhf

Nextcloud logs:
```

{"reqId":"tZ32z8ouHFetdCpIxlhe","level":3,"time":"2021-02-20T17:42:09+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /config/www/nextcloud/config/config.php:1) at /config/www/nextcloud/lib/base.php#492","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":492,"function":"header"},{"file":"/config/www/nextcloud/lib/base.php","line":550,"function":"sendSameSiteCookies","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":657,"function":"performSameSiteCookieProtection","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/console.php","line":49,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"},{"file":"/config/www/nextcloud/occ","line":11,"args":["/config/www/nextcloud/console.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"--","version":"20.0.6.1"}
{"reqId":"tZ32z8ouHFetdCpIxlhe","level":3,"time":"2021-02-20T17:42:09+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Cannot modify header information - headers already sent by (output started at /config/www/nextcloud/config/config.php:1) at /config/www/nextcloud/lib/base.php#492","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":492,"function":"header"},{"file":"/config/www/nextcloud/lib/base.php","line":550,"function":"sendSameSiteCookies","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":657,"function":"performSameSiteCookieProtection","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/console.php","line":49,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"},{"file":"/config/www/nextcloud/occ","line":11,"args":["/config/www/nextcloud/console.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"--","version":"20.0.6.1"}
{"reqId":"SXmJd5tEZGTBHuYYpiI9","level":3,"time":"2021-02-20T17:42:44+00:00","remoteAddr":"90.49.194.210","user":"--","app":"PHP","method":"GET","url":"/","message":{"Exception":"Error","Message":"ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /config/www/nextcloud/lib/base.php#409","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":409,"function":"ini_set"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"SXmJd5tEZGTBHuYYpiI9","level":3,"time":"2021-02-20T17:42:44+00:00","remoteAddr":"90.49.194.210","user":"--","app":"PHP","method":"GET","url":"/","message":{"Exception":"Error","Message":"ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /config/www/nextcloud/lib/base.php#413","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":413,"function":"ini_set"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"SXmJd5tEZGTBHuYYpiI9","level":3,"time":"2021-02-20T17:42:44+00:00","remoteAddr":"90.49.194.210","user":"--","app":"PHP","method":"GET","url":"/","message":{"Exception":"Error","Message":"ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /config/www/nextcloud/lib/base.php#417","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":417,"function":"ini_set"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"SXmJd5tEZGTBHuYYpiI9","level":3,"time":"2021-02-20T17:42:44+00:00","remoteAddr":"90.49.194.210","user":"--","app":"base","method":"GET","url":"/","message":{"Exception":"ErrorException","Message":"session_name(): Cannot change session name when headers already sent","Code":0,"Trace":[{"function":"trapError","class":"OC\\Session\\Internal","type":"->"},{"function":"session_name"},{"file":"/config/www/nextcloud/lib/private/Session/Internal.php","line":209,"function":"call_user_func_array"},{"file":"/config/www/nextcloud/lib/private/Session/Internal.php","line":55,"function":"invoke","class":"OC\\Session\\Internal","type":"->"},{"file":"/config/www/nextcloud/lib/base.php","line":424,"function":"__construct","class":"OC\\Session\\Internal","type":"->"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Session/Internal.php","Line":185,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"u1qSEwrm58NCWhegwSMR","level":3,"time":"2021-02-20T17:42:45+00:00","remoteAddr":"90.49.194.210","user":"--","app":"PHP","method":"GET","url":"/js/core/merged-template-prepend.js?v=02b4e8d5-0","message":{"Exception":"Error","Message":"ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /config/www/nextcloud/lib/base.php#409","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":409,"function":"ini_set"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"u1qSEwrm58NCWhegwSMR","level":3,"time":"2021-02-20T17:42:45+00:00","remoteAddr":"90.49.194.210","user":"--","app":"PHP","method":"GET","url":"/js/core/merged-template-prepend.js?v=02b4e8d5-0","message":{"Exception":"Error","Message":"ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /config/www/nextcloud/lib/base.php#413","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":413,"function":"ini_set"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"u1qSEwrm58NCWhegwSMR","level":3,"time":"2021-02-20T17:42:45+00:00","remoteAddr":"90.49.194.210","user":"--","app":"PHP","method":"GET","url":"/js/core/merged-template-prepend.js?v=02b4e8d5-0","message":{"Exception":"Error","Message":"ini_set(): Headers already sent. You cannot change the session module's ini settings at this time at /config/www/nextcloud/lib/base.php#417","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":417,"function":"ini_set"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}
{"reqId":"u1qSEwrm58NCWhegwSMR","level":3,"time":"2021-02-20T17:42:45+00:00","remoteAddr":"90.49.194.210","user":"--","app":"base","method":"GET","url":"/js/core/merged-template-prepend.js?v=02b4e8d5-0","message":{"Exception":"ErrorException","Message":"session_name(): Cannot change session name when headers already sent","Code":0,"Trace":[{"function":"trapError","class":"OC\\Session\\Internal","type":"->"},{"function":"session_name"},{"file":"/config/www/nextcloud/lib/private/Session/Internal.php","line":209,"function":"call_user_func_array"},{"file":"/config/www/nextcloud/lib/private/Session/Internal.php","line":55,"function":"invoke","class":"OC\\Session\\Internal","type":"->"},{"file":"/config/www/nextcloud/lib/base.php","line":424,"function":"__construct","class":"OC\\Session\\Internal","type":"->"},{"file":"/config/www/nextcloud/lib/base.php","line":649,"function":"initSession","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/index.php","line":35,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Session/Internal.php","Line":185,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15","version":"20.0.6.1"}


```

sudo docker inspect d9998a7b0538


[
    {
        "Id": "d9998a7b0538d51f3a90edc95809e45b86d7c9095e483f8c8ccd4d529a6f3be4",
        "Created": "2021-02-20T17:42:02.711938014Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-02-20T17:42:05.546397773Z",
            "FinishedAt": "2021-02-20T17:42:59.57481413Z"
        },
        "Image": "sha256:68788df02268cc8e14c2651803f5c591975e35707c3262b3913de524f3085cd0",
        "ResolvConfPath": "/var/lib/docker/containers/d9998a7b0538d51f3a90edc95809e45b86d7c9095e483f8c8ccd4d529a6f3be4/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/d9998a7b0538d51f3a90edc95809e45b86d7c9095e483f8c8ccd4d529a6f3be4/hostname",
        "HostsPath": "/var/lib/docker/containers/d9998a7b0538d51f3a90edc95809e45b86d7c9095e483f8c8ccd4d529a6f3be4/hosts",
        "LogPath": "/var/lib/docker/containers/d9998a7b0538d51f3a90edc95809e45b86d7c9095e483f8c8ccd4d529a6f3be4/d9998a7b0538d51f3a90edc95809e45b86d7c9095e483f8c8ccd4d529a6f3be4-json.log",
        "Name": "/nextcloud",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/opt/nextcloud/nextcloud/data:/data:rw",
                "/opt/nextcloud/nextcloud/config:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "nextcloud_default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9443"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a17c5edad58f20f610ddc7d4ad532d93d440a84f7378f2ff6fa4fe7520cdccbb-init/diff:/var/lib/docker/overlay2/6a578cbb6df620b0b4d2f53307447a17d6bc105a58ff317075b70a2517bde2bd/diff:/var/lib/docker/overlay2/27825a1dd813ef3e17ec833e8c297acacd0e03c7c9ef1e01a31744a733a4052e/diff:/var/lib/docker/overlay2/21bccabee33b9f1f09610c52ff127d2573b6cf41340b202a36ad6a382b351f90/diff:/var/lib/docker/overlay2/3458f332f3a6e73061b863d8fe200e0c070b71cbb737a4a772539b81a8f6a1d2/diff:/var/lib/docker/overlay2/aa2f06cc0dbbd286907cf55ca5fe445c0c6037adf9018aea4c71e832e1235271/diff:/var/lib/docker/overlay2/56b987618f01e1ef81acad932b793ec1047fc1b8217a7eb3df05c182f605a66e/diff:/var/lib/docker/overlay2/cb48c4fbea85412e21298a98645d95dda1f97d108041985bdd0d42adc096d1dd/diff:/var/lib/docker/overlay2/c02093e2ae9c1e1c948425f309b3ceb62478ba8de5082250a66b4f40e26ada4d/diff:/var/lib/docker/overlay2/eac5564e521447d77c8fbffa18b4d30cec3ee9e39f34d20e8e5cd10a5fce1315/diff:/var/lib/docker/overlay2/73c8c7c676b3920a1ac5b80016b3e87f2962f629ab6b03a21d94a6c270890787/diff",
                "MergedDir": "/var/lib/docker/overlay2/a17c5edad58f20f610ddc7d4ad532d93d440a84f7378f2ff6fa4fe7520cdccbb/merged",
                "UpperDir": "/var/lib/docker/overlay2/a17c5edad58f20f610ddc7d4ad532d93d440a84f7378f2ff6fa4fe7520cdccbb/diff",
                "WorkDir": "/var/lib/docker/overlay2/a17c5edad58f20f610ddc7d4ad532d93d440a84f7378f2ff6fa4fe7520cdccbb/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/opt/nextcloud/nextcloud/data",
                "Destination": "/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/opt/nextcloud/nextcloud/config",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "d9998a7b0538",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PUID=1000",
                "PGID=1000",
                "TZ=Europe/London",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PS1=$(whoami)@$(hostname):$(pwd)\\$ ",
                "HOME=/root",
                "TERM=xterm",
                "NEXTCLOUD_PATH=/config/www/nextcloud",
                "LD_PRELOAD=/usr/lib/preloadable_libiconv.so"
            ],
            "Cmd": null,
            "Image": "linuxserver/nextcloud",
            "Volumes": {
                "/config": {},
                "/data": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "Linuxserver.io version:- 20.0.7-ls121 Build-date:- 2021-02-14T15:45:01+00:00",
                "com.docker.compose.config-hash": "283634953615f4aa356dfc4c5aa47ffd268a3201cae4473606d8218ba7a3943b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "nextcloud",
                "com.docker.compose.service": "nextcloud",
                "com.docker.compose.version": "1.21.0",
                "maintainer": "aptalca",
                "traefik.enable": "true",
                "traefik.http.middlewares.nextcloud-headers.headers.customFrameOptionsValue": "SAMEORIGIN",
                "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds": "15552000",
                "traefik.http.middlewares.nextcloud-regex.redirectregex.permanent": "true",
                "traefik.http.middlewares.nextcloud-regex.redirectregex.regex": "https://(.*)/.well-known/(card|cal)dav",
                "traefik.http.middlewares.nextcloud-regex.redirectregex.replacement": "https://$1/remote.php/dav/",
                "traefik.http.routers.nextcloud.entrypoints": "websecure",
                "traefik.http.routers.nextcloud.middlewares": "nextcloud-regex,nextcloud-headers",
                "traefik.http.routers.nextcloud.service": "nextcloud",
                "traefik.http.routers.nextcloud.tls": "true",
                "traefik.http.routers.nextcloud.tls.certresolver": "myhttpchallenge",
                "traefik.http.services.nextcloud.loadbalancer.server.port": "443",
                "traefik.http.services.nextcloud.loadbalancer.server.scheme": "https"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8d17bae8ba79f39728d1f49f82892cb15934f7af29b22e7d1507d8a51b73bab7",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/8d17bae8ba79",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nextcloud_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "nextcloud",
                        "d9998a7b0538"
                    ],
                    "NetworkID": "292f246442283e5980da4882be25f38fa687ec4427ba2759f69ece19497b927b",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

Any idea to understand  what’s going on?

Thank you

**Comment by j0nnymoe** [comment]
@dlecan Please don't comment on a 2+ year old issue. Please open a new issue and provide the information it requests, Thanks.
