### ISSUE TITLE
nfs share of /data breaks update from 15.0.2 to 15.0.5

### ISSUE THREAD

**Issue by bott0r** [linuxserver/docker-nextcloud#91]
Bug: Install 15.0.2 and update to 15.0.5 stalls at step "Backing up data folder" (step 3)

Steps to Reproduce:
  - Install linuxserver/nextcloud docker container 
  - mount a nfs share to /data
  - update 15.0.2 -> 15.0.5 

cheers.

**Comment by thelamer** [comment]
"Doctor, it hurts when I do this."

Sorry I am not sure what you expect us to do about this, we just wrap their code in a docker container to make it easy for users to spinup and use NextCloud on local setups. 

As we have no control over their upgrade logic I leave it to you to debug something like this and if you discover it has something to do with our Docker codebase please file a new issue explaining what we can change to help.

**Comment by bott0r** [comment]
Well, I just reported a bug, sorry for the inconvenience.

**Comment by thelamer** [comment]
No it's appreciated and you actually reported a bug not a support request like the vast majority of issues we get. 

Don't let my demeanor detract you from further participation, it is just in the particular scenario we do not control the Nextcloud webUI based upgrade process at all.

**Comment by aptalca** [comment]
It is a bit of a sore topic for us because we generally don't recommend in container updates for apps, but for nextcloud, there is no other option as their app requires many steps to be taken during each update, likely unique steps to each update. So it's all outside of our control
