### ISSUE TITLE
Configuration mess

### ISSUE THREAD

**Issue by tomjmul** [linuxserver/docker-nextcloud#92]
I know that a lot of this is down to Nextcloud file structure, but it would be great if the the dockerised version could cut a cleaner path through their configuration mess. It would be nice to simply bind the relevant config from the host without ending up with the entire Nextcloud source code getting saved to the host volume into the bargain.

**Comment by aptalca** [comment]
I'll take a look into it again but iirc, the nextcloud config and data are pretty much intertwined. Unless we work collaboratively and closely with their dev team, there isn't much we can do.

Also, even if we separated the app from the data completely, kept the app in the docker image, we wouldn't be able to simply swap out the app files for a different version through an image update and a container recreation. Nextcloud version updates require complicated steps and are currently done while the container is running. Again, it's near impossible for us to dockerize that process without having direct input from their devs.

So instead, we keep the app and data files together in the config folder, and let nextcloud update itself.

**Comment by aptalca** [comment]
Yup, looked into it again to make sure and my statement above stands. It doesn't seem feasible
