### ISSUE TITLE
nginx does not redirect index.php to /

### ISSUE THREAD

**Issue by Cronus89** [linuxserver/docker-nextcloud#94]
It was discussed on discord that the latest image should autoredirect index.php to / but it seems to not.

I tested directly to the container and get the below url

https://192.168.2.235:444/index.php/apps/files

I would expect to get https://192.168.2.235:444/apps/files

**Comment by aptalca** [comment]
Did you update from an earlier build? You may have to delete your default site config at `/config/nginx/site-confs/default` and restart the container

**Comment by Cronus89** [comment]
it was only a month or two old, but that did it, must have changed real quick after I installed :)

Thanks!
