### ISSUE TITLE
Custom cron job to scan all files

### ISSUE THREAD

**Issue by alesnav** [linuxserver/docker-nextcloud#99]
Hi there,

We use a central NAS, shared via NFS and mounted in Nextcloud for every user in an specific group. If a file is created or deleted in the NAS (outside Nextcloud), Nextcloud will not be able to see these changes.

Is it possible to create a new cron job to scan all files every night? How can I do it?

Thanks,
Best regards

**Comment by CHBMB** [comment]
https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html#file-operations

Which applied to the container here would be

```
sudo -u abc php7 /config/www/nextcloud/occ files:scan --all  
```
but you could run this from the host with 
```
docker exec nextcloud sudo -u abc php7 /config/www/nextcloud/occ files:scan --all
```
and add that to a cron job on your host.

**Comment by alesnav** [comment]
Sorry @CHBMB , in my case is a little more difficult because I'm using a Docker Swarm cluster composed by several hosts. So, I don't know the exact container name nor the host where it is running.

Do you have any other option?

**Comment by CHBMB** [comment]
@alesnav Never used swarm, but I guess you could call cron like is detailed here.

https://docs.nextcloud.com/server/15/admin_manual/configuration_server/background_jobs_configuration.html#cron-jobs

**Comment by j0nnymoe** [comment]
Another option could be to use External Storage app for Nextcloud and mount the folders that way. Though it can't be done via NFS, you can mount SMB/CIFS.

**Comment by CHBMB** [comment]
@alesnav Going to close this again, we're trying to reserve Github for code issues rather than support questions.  Feel free to pop by the [forum](https://discourse.linuxserver.io/) or [Discord](https://discord.gg/YWrKVTn)

**Comment by JOduMonT** [comment]
> ```
> sudo -u abc php7 /config/www/nextcloud/occ files:scan --all  
> ```

it is funny because **sudo** is missing in linuxserver image
